"""Loader — ADGM Data Protection Regulations.

Source folder : New sources/ADGM Data Protection Regulations
Source document(s):
    KB 2/UAE/ADGM Data Protection Regulations.pdf

Graph shape   : 7 node labels, 8 relationship types
Expected size : 748 nodes / 2,184 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/adgm_data_protection_regulations.py --dry-run   # validate, write nothing
    python App_new/adgm_data_protection_regulations.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'ADGM_DATA_PROTECTION_REGULATIONS'
FOLDER = 'ADGM Data Protection Regulations'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS'})
SET f.name = 'ADGM Data Protection Regulations',
    f.jurisdiction = 'United Arab Emirates',
    f.folder = 'ADGM Data Protection Regulations',
    f.source_document = 'KB 2/UAE/ADGM Data Protection Regulations.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS'})
MATCH (n:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS'})
WHERE NOT (:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Definition.csv  (39 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.definition = row.definition,
      n.defined_in_section = row.defined_in_section,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Instrument.csv  (1 rows, key instrument_id)
node_instrument = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.instrument_id})
  SET
      n:Instrument,
      n.instrument_id = row.instrument_id,
      n.title = row.title,
      n.version = row.version,
      n.jurisdiction = row.jurisdiction,
      n.date_of_enactment = row.date_of_enactment,
      n.short_title = row.short_title,
      n.long_title = row.long_title,
      n.enacting_formula = row.enacting_formula,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Paragraph.csv  (355 rows, key paragraph_id)
node_paragraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.paragraph_id})
  SET
      n:Paragraph,
      n.paragraph_id = row.paragraph_id,
      n.number = row.number,
      n.subsection_id = row.subsection_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Part.csv  (8 rows, key part_id)
node_part = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.part_id})
  SET
      n:Part,
      n.part_id = row.part_id,
      n.number = row.number,
      n.title = row.title,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Section.csv  (64 rows, key section_id)
node_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.section_id})
  SET
      n:Section,
      n.section_id = row.section_id,
      n.number = row.number,
      n.title = row.title,
      n.part_id = row.part_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Subparagraph.csv  (39 rows, key subparagraph_id)
node_subparagraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.subparagraph_id})
  SET
      n:Subparagraph,
      n.subparagraph_id = row.subparagraph_id,
      n.number = row.number,
      n.paragraph_id = row.paragraph_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Subsection.csv  (242 rows, key subsection_id)
node_subsection = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.subsection_id})
  SET
      n:Subsection,
      n.subsection_id = row.subsection_id,
      n.number = row.number,
      n.section_id = row.section_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_cross_references.csv -> :CROSS_REFERENCES  (351 rows)
rel_cross_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CROSS_REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.target_id})
  MERGE (s)-[r:CROSS_REFERENCES]->(t)
  SET r.reference = row.reference
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_defines.csv -> :DEFINES  (39 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
  SET r.term = row.term
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_structure.csv -> :HAS_PART  (8 rows)
rel_has_part = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PART'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.target_id})
  MERGE (s)-[r:HAS_PART]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_structure.csv -> :HAS_SECTION  (64 rows)
rel_has_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.target_id})
  MERGE (s)-[r:HAS_SECTION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_structure.csv -> :HAS_SUBSECTION  (242 rows)
rel_has_subsection = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBSECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBSECTION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_structure.csv -> :HAS_PARAGRAPH  (355 rows)
rel_has_paragraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PARAGRAPH'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.target_id})
  MERGE (s)-[r:HAS_PARAGRAPH]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_structure.csv -> :HAS_SUBPARAGRAPH  (39 rows)
rel_has_subparagraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBPARAGRAPH'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBPARAGRAPH]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_uses_term.csv -> :USES_TERM  (1,086 rows)
rel_uses_term = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'USES_TERM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'ADGM_DATA_PROTECTION_REGULATIONS', node_id: row.target_id})
  MERGE (s)-[r:USES_TERM]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='ADGM Data Protection Regulations',
    folder=FOLDER,
    jurisdiction='United Arab Emirates',
    source_document='KB 2/UAE/ADGM Data Protection Regulations.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'definition', 'defined_in_section', 'source_document'],
                 rows=39, loadable=39, cypher=node_definition),
        NodeStep(label='Instrument', csv_name='nodes_Instrument.csv', id_column='instrument_id',
                 properties=['title', 'version', 'jurisdiction', 'date_of_enactment', 'short_title', 'long_title', 'enacting_formula', 'source_document'],
                 rows=1, loadable=1, cypher=node_instrument),
        NodeStep(label='Paragraph', csv_name='nodes_Paragraph.csv', id_column='paragraph_id',
                 properties=['number', 'subsection_id', 'text', 'source_document'],
                 rows=355, loadable=355, cypher=node_paragraph),
        NodeStep(label='Part', csv_name='nodes_Part.csv', id_column='part_id',
                 properties=['number', 'title', 'source_document'],
                 rows=8, loadable=8, cypher=node_part),
        NodeStep(label='Section', csv_name='nodes_Section.csv', id_column='section_id',
                 properties=['number', 'title', 'part_id', 'text', 'source_document'],
                 rows=64, loadable=64, cypher=node_section),
        NodeStep(label='Subparagraph', csv_name='nodes_Subparagraph.csv', id_column='subparagraph_id',
                 properties=['number', 'paragraph_id', 'text', 'source_document'],
                 rows=39, loadable=39, cypher=node_subparagraph),
        NodeStep(label='Subsection', csv_name='nodes_Subsection.csv', id_column='subsection_id',
                 properties=['number', 'section_id', 'text', 'source_document'],
                 rows=242, loadable=242, cypher=node_subsection),
    ],
    rel_steps=[
        RelStep(rel_type='CROSS_REFERENCES', csv_name='rels_cross_references.csv',
                properties=['reference'],
                rows=351, loadable=351, cypher=rel_cross_references),
        RelStep(rel_type='DEFINES', csv_name='rels_defines.csv',
                properties=['term'],
                rows=39, loadable=39, cypher=rel_defines),
        RelStep(rel_type='HAS_PART', csv_name='rels_structure.csv',
                properties=[],
                rows=8, loadable=8, cypher=rel_has_part),
        RelStep(rel_type='HAS_SECTION', csv_name='rels_structure.csv',
                properties=[],
                rows=64, loadable=64, cypher=rel_has_section),
        RelStep(rel_type='HAS_SUBSECTION', csv_name='rels_structure.csv',
                properties=[],
                rows=242, loadable=242, cypher=rel_has_subsection),
        RelStep(rel_type='HAS_PARAGRAPH', csv_name='rels_structure.csv',
                properties=[],
                rows=355, loadable=355, cypher=rel_has_paragraph),
        RelStep(rel_type='HAS_SUBPARAGRAPH', csv_name='rels_structure.csv',
                properties=[],
                rows=39, loadable=39, cypher=rel_has_subparagraph),
        RelStep(rel_type='USES_TERM', csv_name='rels_uses_term.csv',
                properties=[],
                rows=1086, loadable=1086, cypher=rel_uses_term),
    ],
    expected_nodes_total=748,
    expected_rels_total=2184,
)

if __name__ == "__main__":
    run(LOADER)
