"""Loader — Canada PIPEDA.

Source folder : New sources/Canada PIPEDA
Source document(s):
    KB 2/Canada/Personal Information Protection and Electronic Documents Act.pdf

Graph shape   : 14 node labels, 15 relationship types
Expected size : 640 nodes / 738 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/canada_pipeda.py --dry-run   # validate, write nothing
    python App_new/canada_pipeda.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'CANADA_PIPEDA'
FOLDER = 'Canada PIPEDA'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'CANADA_PIPEDA'})
SET f.name = 'Canada PIPEDA',
    f.jurisdiction = 'Canada',
    f.folder = 'Canada PIPEDA',
    f.source_document = 'KB 2/Canada/Personal Information Protection and Electronic Documents Act.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'CANADA_PIPEDA'})
MATCH (n:NewSourceNode {framework_id: 'CANADA_PIPEDA'})
WHERE NOT (:NewSourceNode {framework_id: 'CANADA_PIPEDA'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Clause.csv  (48 rows, key clause_id)
node_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.clause_id})
  SET
      n:Clause,
      n.clause_id = row.clause_id,
      n.number = row.number,
      n.principle_id = row.principle_id,
      n.type = row.type,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ClauseParagraph.csv  (16 rows, key paragraph_id)
node_clauseparagraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.paragraph_id})
  SET
      n:ClauseParagraph,
      n.paragraph_id = row.paragraph_id,
      n.parent_id = row.parent_id,
      n.parent_type = row.parent_type,
      n.label = row.label,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Deadline.csv  (23 rows, key deadline_id)
node_deadline = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.deadline_id})
  SET
      n:Deadline,
      n.deadline_id = row.deadline_id,
      n.provision_id = row.provision_id,
      n.phrase = row.phrase,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (28 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.definition_text = row.definition_text,
      n.french_term = row.french_term,
      n.defined_in_section = row.defined_in_section,
      n.part = row.part,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Division.csv  (6 rows, key division_id)
node_division = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.division_id})
  SET
      n:Division,
      n.division_id = row.division_id,
      n.number = row.number,
      n.title = row.title,
      n.part_id = row.part_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Paragraph.csv  (270 rows, key paragraph_id)
node_paragraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.paragraph_id})
  SET
      n:Paragraph,
      n.paragraph_id = row.paragraph_id,
      n.parent_id = row.parent_id,
      n.parent_type = row.parent_type,
      n.level = row.level,
      n.label = row.label,
      n.text = row.text,
      n.amendment_history = row.amendment_history,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Part.csv  (6 rows, key part_id)
node_part = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.part_id})
  SET
      n:Part,
      n.part_id = row.part_id,
      n.number = row.number,
      n.title = row.title,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Penalty.csv  (2 rows, key penalty_id)
node_penalty = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.penalty_id})
  SET
      n:Penalty,
      n.penalty_id = row.penalty_id,
      n.section_id = row.section_id,
      n.paragraph_id = row.paragraph_id,
      n.offence_type = row.offence_type,
      n.maximum_fine = row.maximum_fine,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_PendingAmendment.csv  (9 rows, key amendment_id)
node_pendingamendment = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.amendment_id})
  SET
      n:PendingAmendment,
      n.amendment_id = row.amendment_id,
      n.citation = row.citation,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Principle.csv  (10 rows, key principle_id)
node_principle = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.principle_id})
  SET
      n:Principle,
      n.principle_id = row.principle_id,
      n.number = row.number,
      n.heading = row.heading,
      n.name = row.name,
      n.text = row.text,
      n.schedule_id = row.schedule_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Schedule.csv  (4 rows, key schedule_id)
node_schedule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.schedule_id})
  SET
      n:Schedule,
      n.schedule_id = row.schedule_id,
      n.number = row.number,
      n.title = row.title,
      n.authority_reference = row.authority_reference,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ScheduleItem.csv  (5 rows, key item_id)
node_scheduleitem = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.item_id})
  SET
      n:ScheduleItem,
      n.item_id = row.item_id,
      n.schedule_id = row.schedule_id,
      n.item = row.item,
      n.column_1 = row.column_1,
      n.column_2 = row.column_2,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Section.csv  (71 rows, key section_id)
node_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.section_id})
  SET
      n:Section,
      n.section_id = row.section_id,
      n.number = row.number,
      n.subheading = row.subheading,
      n.marginal_note = row.marginal_note,
      n.part_id = row.part_id,
      n.division_id = row.division_id,
      n.text = row.text,
      n.amendment_history = row.amendment_history,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Subsection.csv  (142 rows, key subsection_id)
node_subsection = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.subsection_id})
  SET
      n:Subsection,
      n.subsection_id = row.subsection_id,
      n.section_id = row.section_id,
      n.number = row.number,
      n.marginal_note = row.marginal_note,
      n.text = row.text,
      n.amendment_history = row.amendment_history,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_amends.csv -> :AMENDS  (12 rows)
rel_amends = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'AMENDS'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:AMENDS]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :HAS_DIVISION  (6 rows)
rel_has_division = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_DIVISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:HAS_DIVISION]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :HAS_SECTION  (70 rows)
rel_has_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:HAS_SECTION]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :HAS_SUBSECTION  (142 rows)
rel_has_subsection = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBSECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBSECTION]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :HAS_PARAGRAPH  (256 rows)
rel_has_paragraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PARAGRAPH'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:HAS_PARAGRAPH]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :HAS_SUBPARAGRAPH  (30 rows)
rel_has_subparagraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBPARAGRAPH'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBPARAGRAPH]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :HAS_PRINCIPLE  (10 rows)
rel_has_principle = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PRINCIPLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:HAS_PRINCIPLE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :HAS_CLAUSE  (48 rows)
rel_has_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:HAS_CLAUSE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :HAS_ITEM  (5 rows)
rel_has_item = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ITEM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:HAS_ITEM]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_defines.csv -> :DEFINES  (28 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_prescribes_penalty.csv -> :PRESCRIBES_PENALTY  (2 rows)
rel_prescribes_penalty = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'PRESCRIBES_PENALTY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:PRESCRIBES_PENALTY]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_references.csv -> :REFERENCES_CLAUSE  (42 rows)
rel_references_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES_CLAUSE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_references.csv -> :REFERENCES_SCHEDULE  (44 rows)
rel_references_schedule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES_SCHEDULE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES_SCHEDULE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_references.csv -> :REFERENCES_DIVISION  (20 rows)
rel_references_division = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES_DIVISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES_DIVISION]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_states_deadline.csv -> :STATES_DEADLINE  (23 rows)
rel_states_deadline = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'STATES_DEADLINE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CANADA_PIPEDA', node_id: row.target_id})
  MERGE (s)-[r:STATES_DEADLINE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='Canada PIPEDA',
    folder=FOLDER,
    jurisdiction='Canada',
    source_document='KB 2/Canada/Personal Information Protection and Electronic Documents Act.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Clause', csv_name='nodes_Clause.csv', id_column='clause_id',
                 properties=['number', 'principle_id', 'type', 'text', 'source_document'],
                 rows=48, loadable=48, cypher=node_clause),
        NodeStep(label='ClauseParagraph', csv_name='nodes_ClauseParagraph.csv', id_column='paragraph_id',
                 properties=['parent_id', 'parent_type', 'label', 'text', 'source_document'],
                 rows=16, loadable=16, cypher=node_clauseparagraph),
        NodeStep(label='Deadline', csv_name='nodes_Deadline.csv', id_column='deadline_id',
                 properties=['provision_id', 'phrase', 'source_document'],
                 rows=23, loadable=23, cypher=node_deadline),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'definition_text', 'french_term', 'defined_in_section', 'part', 'source_document'],
                 rows=28, loadable=28, cypher=node_definition),
        NodeStep(label='Division', csv_name='nodes_Division.csv', id_column='division_id',
                 properties=['number', 'title', 'part_id', 'source_document'],
                 rows=6, loadable=6, cypher=node_division),
        NodeStep(label='Paragraph', csv_name='nodes_Paragraph.csv', id_column='paragraph_id',
                 properties=['parent_id', 'parent_type', 'level', 'label', 'text', 'amendment_history', 'source_document'],
                 rows=270, loadable=270, cypher=node_paragraph),
        NodeStep(label='Part', csv_name='nodes_Part.csv', id_column='part_id',
                 properties=['number', 'title', 'source_document'],
                 rows=6, loadable=6, cypher=node_part),
        NodeStep(label='Penalty', csv_name='nodes_Penalty.csv', id_column='penalty_id',
                 properties=['section_id', 'paragraph_id', 'offence_type', 'maximum_fine', 'text', 'source_document'],
                 rows=2, loadable=2, cypher=node_penalty),
        NodeStep(label='PendingAmendment', csv_name='nodes_PendingAmendment.csv', id_column='amendment_id',
                 properties=['citation', 'text', 'source_document'],
                 rows=9, loadable=9, cypher=node_pendingamendment),
        NodeStep(label='Principle', csv_name='nodes_Principle.csv', id_column='principle_id',
                 properties=['number', 'heading', 'name', 'text', 'schedule_id', 'source_document'],
                 rows=10, loadable=10, cypher=node_principle),
        NodeStep(label='Schedule', csv_name='nodes_Schedule.csv', id_column='schedule_id',
                 properties=['number', 'title', 'authority_reference', 'source_document'],
                 rows=4, loadable=4, cypher=node_schedule),
        NodeStep(label='ScheduleItem', csv_name='nodes_ScheduleItem.csv', id_column='item_id',
                 properties=['schedule_id', 'item', 'column_1', 'column_2', 'source_document'],
                 rows=5, loadable=5, cypher=node_scheduleitem),
        NodeStep(label='Section', csv_name='nodes_Section.csv', id_column='section_id',
                 properties=['number', 'subheading', 'marginal_note', 'part_id', 'division_id', 'text', 'amendment_history', 'source_document'],
                 rows=71, loadable=71, cypher=node_section),
        NodeStep(label='Subsection', csv_name='nodes_Subsection.csv', id_column='subsection_id',
                 properties=['section_id', 'number', 'marginal_note', 'text', 'amendment_history', 'source_document'],
                 rows=142, loadable=142, cypher=node_subsection),
    ],
    rel_steps=[
        RelStep(rel_type='AMENDS', csv_name='rels_amends.csv',
                properties=['source_document'],
                rows=12, loadable=12, cypher=rel_amends),
        RelStep(rel_type='HAS_DIVISION', csv_name='rels_contains.csv',
                properties=['source_document'],
                rows=6, loadable=6, cypher=rel_has_division),
        RelStep(rel_type='HAS_SECTION', csv_name='rels_contains.csv',
                properties=['source_document'],
                rows=70, loadable=70, cypher=rel_has_section),
        RelStep(rel_type='HAS_SUBSECTION', csv_name='rels_contains.csv',
                properties=['source_document'],
                rows=142, loadable=142, cypher=rel_has_subsection),
        RelStep(rel_type='HAS_PARAGRAPH', csv_name='rels_contains.csv',
                properties=['source_document'],
                rows=256, loadable=256, cypher=rel_has_paragraph),
        RelStep(rel_type='HAS_SUBPARAGRAPH', csv_name='rels_contains.csv',
                properties=['source_document'],
                rows=30, loadable=30, cypher=rel_has_subparagraph),
        RelStep(rel_type='HAS_PRINCIPLE', csv_name='rels_contains.csv',
                properties=['source_document'],
                rows=10, loadable=10, cypher=rel_has_principle),
        RelStep(rel_type='HAS_CLAUSE', csv_name='rels_contains.csv',
                properties=['source_document'],
                rows=48, loadable=48, cypher=rel_has_clause),
        RelStep(rel_type='HAS_ITEM', csv_name='rels_contains.csv',
                properties=['source_document'],
                rows=5, loadable=5, cypher=rel_has_item),
        RelStep(rel_type='DEFINES', csv_name='rels_defines.csv',
                properties=['source_document'],
                rows=28, loadable=28, cypher=rel_defines),
        RelStep(rel_type='PRESCRIBES_PENALTY', csv_name='rels_prescribes_penalty.csv',
                properties=['source_document'],
                rows=2, loadable=2, cypher=rel_prescribes_penalty),
        RelStep(rel_type='REFERENCES_CLAUSE', csv_name='rels_references.csv',
                properties=['source_document'],
                rows=42, loadable=42, cypher=rel_references_clause),
        RelStep(rel_type='REFERENCES_SCHEDULE', csv_name='rels_references.csv',
                properties=['source_document'],
                rows=44, loadable=44, cypher=rel_references_schedule),
        RelStep(rel_type='REFERENCES_DIVISION', csv_name='rels_references.csv',
                properties=['source_document'],
                rows=20, loadable=20, cypher=rel_references_division),
        RelStep(rel_type='STATES_DEADLINE', csv_name='rels_states_deadline.csv',
                properties=['source_document'],
                rows=23, loadable=23, cypher=rel_states_deadline),
    ],
    expected_nodes_total=640,
    expected_rels_total=738,
)

if __name__ == "__main__":
    run(LOADER)
