"""Loader — CCPA 2025.

Source folder : New sources/CCPA 2025
Source document(s):
    California Consumer Privacy Act of 2018, as amended effective 01/01/2025 (SB 1223, AB 1008, AB 1824), posted by the CPPA January 2025 (KB 2/USA/CCPA.pdf)

Graph shape   : 9 node labels, 10 relationship types
Expected size : 716 nodes / 897 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/ccpa_2025.py --dry-run   # validate, write nothing
    python App_new/ccpa_2025.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'CCPA_2025'
FOLDER = 'CCPA 2025'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'CCPA_2025'})
SET f.name = 'CCPA 2025',
    f.jurisdiction = 'United States',
    f.folder = 'CCPA 2025',
    f.source_document = 'California Consumer Privacy Act of 2018, as amended effective 01/01/2025 (SB 1223, AB 1008, AB 1824), posted by the CPPA January 2025 (KB 2/USA/CCPA.pdf)',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'CCPA_2025'})
MATCH (n:NewSourceNode {framework_id: 'CCPA_2025'})
WHERE NOT (:NewSourceNode {framework_id: 'CCPA_2025'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Clause.csv  (550 rows, key clause_id)
node_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.clause_id})
  SET
      n:Clause,
      n.clause_id = row.clause_id,
      n.section_id = row.section_id,
      n.parent_clause_id = row.parent_clause_id,
      n.label = row.label,
      n.level_type = row.level_type,
      n.depth = row.depth,
      n.citation = row.citation,
      n.text = row.text,
      n.modals = row.modals,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (69 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.term_variants = row.term_variants,
      n.section_id = row.section_id,
      n.clause_id = row.clause_id,
      n.citation = row.citation,
      n.definition_text = row.definition_text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_EnforcementBody.csv  (2 rows, key enforcementbody_id)
node_enforcementbody = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.enforcementbody_id})
  SET
      n:EnforcementBody,
      n.enforcementbody_id = row.enforcementbody_id,
      n.name = row.name,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ExternalCitation.csv  (2 rows, key externalcitation_id)
node_externalcitation = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.externalcitation_id})
  SET
      n:ExternalCitation,
      n.externalcitation_id = row.externalcitation_id,
      n.citation = row.citation,
      n.target_section = row.target_section,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_MonetaryAmount.csv  (8 rows, key monetaryamount_id)
node_monetaryamount = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.monetaryamount_id})
  SET
      n:MonetaryAmount,
      n.monetaryamount_id = row.monetaryamount_id,
      n.amount_text = row.amount_text,
      n.amount_usd = row.amount_usd,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Right.csv  (7 rows, key right_id)
node_right = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.right_id})
  SET
      n:Right,
      n.right_id = row.right_id,
      n.right_name = row.right_name,
      n.section_id = row.section_id,
      n.citation = row.citation,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Section.csv  (45 rows, key section_id)
node_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.section_id})
  SET
      n:Section,
      n.section_id = row.section_id,
      n.section_number = row.section_number,
      n.heading = row.heading,
      n.citation = row.citation,
      n.intro_text = row.intro_text,
      n.clause_count = row.clause_count,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Threshold.csv  (7 rows, key threshold_id)
node_threshold = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.threshold_id})
  SET
      n:Threshold,
      n.threshold_id = row.threshold_id,
      n.threshold_text = row.threshold_text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_TimePeriod.csv  (26 rows, key timeperiod_id)
node_timeperiod = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.timeperiod_id})
  SET
      n:TimePeriod,
      n.timeperiod_id = row.timeperiod_id,
      n.period_text = row.period_text,
      n.period_kind = row.period_kind,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_CITES_EXTERNAL.csv -> :CITES_EXTERNAL  (4 rows)
rel_cites_external = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CITES_EXTERNAL'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.target_id})
  MERGE (s)-[r:CITES_EXTERNAL]->(t)
  SET r.mention_count = row.mention_count
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_CROSS_REFERENCES.csv -> :CROSS_REFERENCES  (158 rows)
rel_cross_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CROSS_REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.target_id})
  MERGE (s)-[r:CROSS_REFERENCES]->(t)
  SET r.mention_count = row.mention_count,
      r.citation_text = row.citation_text
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DEFINED_IN.csv -> :DEFINED_IN  (69 rows)
rel_defined_in = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINED_IN'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.target_id})
  MERGE (s)-[r:DEFINED_IN]->(t)
  SET r.term = row.term
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_GRANTS_RIGHT.csv -> :GRANTS_RIGHT  (7 rows)
rel_grants_right = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'GRANTS_RIGHT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.target_id})
  MERGE (s)-[r:GRANTS_RIGHT]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_CLAUSE.csv -> :HAS_CLAUSE  (161 rows)
rel_has_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.target_id})
  MERGE (s)-[r:HAS_CLAUSE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_SUBCLAUSE.csv -> :HAS_SUBCLAUSE  (389 rows)
rel_has_subclause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBCLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBCLAUSE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_REFERS_TO_BODY.csv -> :REFERS_TO_BODY  (30 rows)
rel_refers_to_body = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERS_TO_BODY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.target_id})
  MERGE (s)-[r:REFERS_TO_BODY]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_SETS_THRESHOLD.csv -> :SETS_THRESHOLD  (11 rows)
rel_sets_threshold = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'SETS_THRESHOLD'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.target_id})
  MERGE (s)-[r:SETS_THRESHOLD]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_SPECIFIES_AMOUNT.csv -> :SPECIFIES_AMOUNT  (14 rows)
rel_specifies_amount = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'SPECIFIES_AMOUNT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.target_id})
  MERGE (s)-[r:SPECIFIES_AMOUNT]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_STATES_TIME_PERIOD.csv -> :STATES_TIME_PERIOD  (54 rows)
rel_states_time_period = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'STATES_TIME_PERIOD'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'CCPA_2025', node_id: row.target_id})
  MERGE (s)-[r:STATES_TIME_PERIOD]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='CCPA 2025',
    folder=FOLDER,
    jurisdiction='United States',
    source_document='California Consumer Privacy Act of 2018, as amended effective 01/01/2025 (SB 1223, AB 1008, AB 1824), posted by the CPPA January 2025 (KB 2/USA/CCPA.pdf)',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Clause', csv_name='nodes_Clause.csv', id_column='clause_id',
                 properties=['section_id', 'parent_clause_id', 'label', 'level_type', 'depth', 'citation', 'text', 'modals', 'source_document'],
                 rows=550, loadable=550, cypher=node_clause),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'term_variants', 'section_id', 'clause_id', 'citation', 'definition_text', 'source_document'],
                 rows=69, loadable=69, cypher=node_definition),
        NodeStep(label='EnforcementBody', csv_name='nodes_EnforcementBody.csv', id_column='enforcementbody_id',
                 properties=['name', 'source_document'],
                 rows=2, loadable=2, cypher=node_enforcementbody),
        NodeStep(label='ExternalCitation', csv_name='nodes_ExternalCitation.csv', id_column='externalcitation_id',
                 properties=['citation', 'target_section', 'source_document'],
                 rows=2, loadable=2, cypher=node_externalcitation),
        NodeStep(label='MonetaryAmount', csv_name='nodes_MonetaryAmount.csv', id_column='monetaryamount_id',
                 properties=['amount_text', 'amount_usd', 'source_document'],
                 rows=8, loadable=8, cypher=node_monetaryamount),
        NodeStep(label='Right', csv_name='nodes_Right.csv', id_column='right_id',
                 properties=['right_name', 'section_id', 'citation', 'source_document'],
                 rows=7, loadable=7, cypher=node_right),
        NodeStep(label='Section', csv_name='nodes_Section.csv', id_column='section_id',
                 properties=['section_number', 'heading', 'citation', 'intro_text', 'clause_count', 'source_document'],
                 rows=45, loadable=45, cypher=node_section),
        NodeStep(label='Threshold', csv_name='nodes_Threshold.csv', id_column='threshold_id',
                 properties=['threshold_text', 'source_document'],
                 rows=7, loadable=7, cypher=node_threshold),
        NodeStep(label='TimePeriod', csv_name='nodes_TimePeriod.csv', id_column='timeperiod_id',
                 properties=['period_text', 'period_kind', 'source_document'],
                 rows=26, loadable=26, cypher=node_timeperiod),
    ],
    rel_steps=[
        RelStep(rel_type='CITES_EXTERNAL', csv_name='rels_CITES_EXTERNAL.csv',
                properties=['mention_count'],
                rows=4, loadable=4, cypher=rel_cites_external),
        RelStep(rel_type='CROSS_REFERENCES', csv_name='rels_CROSS_REFERENCES.csv',
                properties=['mention_count', 'citation_text'],
                rows=158, loadable=158, cypher=rel_cross_references),
        RelStep(rel_type='DEFINED_IN', csv_name='rels_DEFINED_IN.csv',
                properties=['term'],
                rows=69, loadable=69, cypher=rel_defined_in),
        RelStep(rel_type='GRANTS_RIGHT', csv_name='rels_GRANTS_RIGHT.csv',
                properties=[],
                rows=7, loadable=7, cypher=rel_grants_right),
        RelStep(rel_type='HAS_CLAUSE', csv_name='rels_HAS_CLAUSE.csv',
                properties=[],
                rows=161, loadable=161, cypher=rel_has_clause),
        RelStep(rel_type='HAS_SUBCLAUSE', csv_name='rels_HAS_SUBCLAUSE.csv',
                properties=[],
                rows=389, loadable=389, cypher=rel_has_subclause),
        RelStep(rel_type='REFERS_TO_BODY', csv_name='rels_REFERS_TO_BODY.csv',
                properties=[],
                rows=30, loadable=30, cypher=rel_refers_to_body),
        RelStep(rel_type='SETS_THRESHOLD', csv_name='rels_SETS_THRESHOLD.csv',
                properties=[],
                rows=11, loadable=11, cypher=rel_sets_threshold),
        RelStep(rel_type='SPECIFIES_AMOUNT', csv_name='rels_SPECIFIES_AMOUNT.csv',
                properties=[],
                rows=14, loadable=14, cypher=rel_specifies_amount),
        RelStep(rel_type='STATES_TIME_PERIOD', csv_name='rels_STATES_TIME_PERIOD.csv',
                properties=[],
                rows=54, loadable=54, cypher=rel_states_time_period),
    ],
    expected_nodes_total=716,
    expected_rels_total=897,
)

if __name__ == "__main__":
    run(LOADER)
