"""Loader — COPPA.

Source folder : New sources/COPPA
Source document(s):
    KB 2/USA/Children's Online Privacy Protection Act.pdf

Graph shape   : 7 node labels, 8 relationship types
Expected size : 182 nodes / 211 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/coppa.py --dry-run   # validate, write nothing
    python App_new/coppa.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'COPPA'
FOLDER = 'COPPA'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'COPPA'})
SET f.name = 'COPPA',
    f.jurisdiction = 'United States',
    f.folder = 'COPPA',
    f.source_document = 'KB 2/USA/Children\\'s Online Privacy Protection Act.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'COPPA'})
MATCH (n:NewSourceNode {framework_id: 'COPPA'})
WHERE NOT (:NewSourceNode {framework_id: 'COPPA'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Deadline.csv  (7 rows, key deadline_id)
node_deadline = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COPPA', node_id: row.deadline_id})
  SET
      n:Deadline,
      n.deadline_id = row.deadline_id,
      n.citation = row.citation,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (17 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COPPA', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.text = row.text,
      n.section_id = row.section_id,
      n.citation = row.citation,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_DefinitionElement.csv  (36 rows, key definitionelement_id)
node_definitionelement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COPPA', node_id: row.definitionelement_id})
  SET
      n:DefinitionElement,
      n.definitionelement_id = row.definitionelement_id,
      n.definition_id = row.definition_id,
      n.label = row.label,
      n.parent_element_id = row.parent_element_id,
      n.text = row.text,
      n.citation = row.citation,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ExternalReference.csv  (8 rows, key externalreference_id)
node_externalreference = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COPPA', node_id: row.externalreference_id})
  SET
      n:ExternalReference,
      n.externalreference_id = row.externalreference_id,
      n.name = row.name,
      n.citation = row.citation,
      n.role_in_this_part = row.role_in_this_part,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Provision.csv  (100 rows, key provision_id)
node_provision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COPPA', node_id: row.provision_id})
  SET
      n:Provision,
      n.provision_id = row.provision_id,
      n.citation = row.citation,
      n.section_id = row.section_id,
      n.parent_provision_id = row.parent_provision_id,
      n.label = row.label,
      n.level = row.level,
      n.heading = row.heading,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Rule.csv  (1 rows, key rule_id)
node_rule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COPPA', node_id: row.rule_id})
  SET
      n:Rule,
      n.rule_id = row.rule_id,
      n.citation = row.citation,
      n.title = row.title,
      n.issuing_authority = row.issuing_authority,
      n.authority_citation = row.authority_citation,
      n.publication = row.publication,
      n.effective_date = row.effective_date,
      n.implements = row.implements,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Section.csv  (13 rows, key section_id)
node_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COPPA', node_id: row.section_id})
  SET
      n:Section,
      n.section_id = row.section_id,
      n.section_number = row.section_number,
      n.citation = row.citation,
      n.heading = row.heading,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_CITES.csv -> :CITES  (6 rows)
rel_cites = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CITES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COPPA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COPPA', node_id: row.target_id})
  MERGE (s)-[r:CITES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DEFINES.csv -> :DEFINES  (17 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COPPA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COPPA', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_DEADLINE.csv -> :HAS_DEADLINE  (7 rows)
rel_has_deadline = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_DEADLINE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COPPA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COPPA', node_id: row.target_id})
  MERGE (s)-[r:HAS_DEADLINE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_ELEMENT.csv -> :HAS_ELEMENT  (36 rows)
rel_has_element = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ELEMENT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COPPA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COPPA', node_id: row.target_id})
  MERGE (s)-[r:HAS_ELEMENT]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_PROVISION.csv -> :HAS_PROVISION  (24 rows)
rel_has_provision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PROVISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COPPA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COPPA', node_id: row.target_id})
  MERGE (s)-[r:HAS_PROVISION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_SECTION.csv -> :HAS_SECTION  (13 rows)
rel_has_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COPPA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COPPA', node_id: row.target_id})
  MERGE (s)-[r:HAS_SECTION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_SUBPROVISION.csv -> :HAS_SUBPROVISION  (76 rows)
rel_has_subprovision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBPROVISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COPPA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COPPA', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBPROVISION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_REFERENCES.csv -> :REFERENCES  (32 rows)
rel_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COPPA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COPPA', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES]->(t)
  SET r.cited_as = row.cited_as
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='COPPA',
    folder=FOLDER,
    jurisdiction='United States',
    source_document="KB 2/USA/Children's Online Privacy Protection Act.pdf",
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Deadline', csv_name='nodes_Deadline.csv', id_column='deadline_id',
                 properties=['citation', 'text', 'source_document'],
                 rows=7, loadable=7, cypher=node_deadline),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'text', 'section_id', 'citation', 'source_document'],
                 rows=17, loadable=17, cypher=node_definition),
        NodeStep(label='DefinitionElement', csv_name='nodes_DefinitionElement.csv', id_column='definitionelement_id',
                 properties=['definition_id', 'label', 'parent_element_id', 'text', 'citation', 'source_document'],
                 rows=36, loadable=36, cypher=node_definitionelement),
        NodeStep(label='ExternalReference', csv_name='nodes_ExternalReference.csv', id_column='externalreference_id',
                 properties=['name', 'citation', 'role_in_this_part', 'source_document'],
                 rows=8, loadable=8, cypher=node_externalreference),
        NodeStep(label='Provision', csv_name='nodes_Provision.csv', id_column='provision_id',
                 properties=['citation', 'section_id', 'parent_provision_id', 'label', 'level', 'heading', 'text', 'source_document'],
                 rows=100, loadable=100, cypher=node_provision),
        NodeStep(label='Rule', csv_name='nodes_Rule.csv', id_column='rule_id',
                 properties=['citation', 'title', 'issuing_authority', 'authority_citation', 'publication', 'effective_date', 'implements', 'source_document'],
                 rows=1, loadable=1, cypher=node_rule),
        NodeStep(label='Section', csv_name='nodes_Section.csv', id_column='section_id',
                 properties=['section_number', 'citation', 'heading', 'text', 'source_document'],
                 rows=13, loadable=13, cypher=node_section),
    ],
    rel_steps=[
        RelStep(rel_type='CITES', csv_name='rels_CITES.csv',
                properties=[],
                rows=6, loadable=6, cypher=rel_cites),
        RelStep(rel_type='DEFINES', csv_name='rels_DEFINES.csv',
                properties=[],
                rows=17, loadable=17, cypher=rel_defines),
        RelStep(rel_type='HAS_DEADLINE', csv_name='rels_HAS_DEADLINE.csv',
                properties=[],
                rows=7, loadable=7, cypher=rel_has_deadline),
        RelStep(rel_type='HAS_ELEMENT', csv_name='rels_HAS_ELEMENT.csv',
                properties=[],
                rows=36, loadable=36, cypher=rel_has_element),
        RelStep(rel_type='HAS_PROVISION', csv_name='rels_HAS_PROVISION.csv',
                properties=[],
                rows=24, loadable=24, cypher=rel_has_provision),
        RelStep(rel_type='HAS_SECTION', csv_name='rels_HAS_SECTION.csv',
                properties=[],
                rows=13, loadable=13, cypher=rel_has_section),
        RelStep(rel_type='HAS_SUBPROVISION', csv_name='rels_HAS_SUBPROVISION.csv',
                properties=[],
                rows=76, loadable=76, cypher=rel_has_subprovision),
        RelStep(rel_type='REFERENCES', csv_name='rels_REFERENCES.csv',
                properties=['cited_as'],
                rows=32, loadable=32, cypher=rel_references),
    ],
    expected_nodes_total=182,
    expected_rels_total=211,
)

if __name__ == "__main__":
    run(LOADER)
