"""Loader — COSO ERM.

Source folder : New sources/COSO ERM
Source document(s):
    COSO Enterprise Risk Management Framework.pdf
    Compliance-Risk-Management-Applying-the-COSO-ERM-Framework.pdf

Graph shape   : 17 node labels, 15 relationship types
Expected size : 890 nodes / 1,022 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/coso_erm.py --dry-run   # validate, write nothing
    python App_new/coso_erm.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'COSO_ERM'
FOLDER = 'COSO ERM'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'COSO_ERM'})
SET f.name = 'COSO ERM',
    f.jurisdiction = 'United States',
    f.folder = 'COSO ERM',
    f.source_document = 'COSO Enterprise Risk Management Framework.pdf | Compliance-Risk-Management-Applying-the-COSO-ERM-Framework.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'COSO_ERM'})
MATCH (n:NewSourceNode {framework_id: 'COSO_ERM'})
WHERE NOT (:NewSourceNode {framework_id: 'COSO_ERM'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Appendix.csv  (6 rows, key appendix_id)
node_appendix = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.appendix_id})
  SET
      n:Appendix,
      n.appendix_id = row.appendix_id,
      n.instrument_id = row.instrument_id,
      n.label = row.label,
      n.heading = row.heading,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Clause.csv  (552 rows, key clause_id)
node_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.clause_id})
  SET
      n:Clause,
      n.clause_id = row.clause_id,
      n.parent_id = row.parent_id,
      n.label = row.label,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Component.csv  (5 rows, key component_id)
node_component = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.component_id})
  SET
      n:Component,
      n.component_id = row.component_id,
      n.number = row.number,
      n.name = row.name,
      n.applied_in_section = row.applied_in_section,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_DefinedTerm.csv  (27 rows, key term_id)
node_definedterm = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.term_id})
  SET
      n:DefinedTerm,
      n.term_id = row.term_id,
      n.term = row.term,
      n.definition = row.definition,
      n.stated_in = row.stated_in,
      n.instrument_id = row.instrument_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ExternalGuidance.csv  (10 rows, key guidance_id)
node_externalguidance = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.guidance_id})
  SET
      n:ExternalGuidance,
      n.guidance_id = row.guidance_id,
      n.jurisdiction = row.jurisdiction,
      n.name = row.name,
      n.description = row.description,
      n.stated_in = row.stated_in,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Figure.csv  (24 rows, key figure_id)
node_figure = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.figure_id})
  SET
      n:Figure,
      n.figure_id = row.figure_id,
      n.label = row.label,
      n.caption = row.caption,
      n.parent_id = row.parent_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Instrument.csv  (2 rows, key instrument_id)
node_instrument = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.instrument_id})
  SET
      n:Instrument,
      n.instrument_id = row.instrument_id,
      n.title = row.title,
      n.volume_part = row.volume_part,
      n.issuing_body = row.issuing_body,
      n.author = row.author,
      n.date = row.date,
      n.copyright = row.copyright,
      n.contents = row.contents,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_KeyCharacteristic.csv  (120 rows, key kc_id)
node_keycharacteristic = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.kc_id})
  SET
      n:KeyCharacteristic,
      n.kc_id = row.kc_id,
      n.principle_id = row.principle_id,
      n.sequence = row.sequence,
      n.text = row.text,
      n.table = row.table,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Principle.csv  (20 rows, key principle_id)
node_principle = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.principle_id})
  SET
      n:Principle,
      n.principle_id = row.principle_id,
      n.number = row.number,
      n.name = row.name,
      n.statement = row.statement,
      n.component_id = row.component_id,
      n.key_characteristics_table = row.key_characteristics_table,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_PrioritizationCriterion.csv  (5 rows, key criterion_id)
node_prioritizationcriterion = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.criterion_id})
  SET
      n:PrioritizationCriterion,
      n.criterion_id = row.criterion_id,
      n.name = row.name,
      n.description = row.description,
      n.stated_in = row.stated_in,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ProgramElement.csv  (8 rows, key element_id)
node_programelement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.element_id})
  SET
      n:ProgramElement,
      n.element_id = row.element_id,
      n.number = row.number,
      n.name = row.name,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_RiskResponse.csv  (7 rows, key response_id)
node_riskresponse = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.response_id})
  SET
      n:RiskResponse,
      n.response_id = row.response_id,
      n.name = row.name,
      n.description = row.description,
      n.stated_in = row.stated_in,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Role.csv  (18 rows, key role_id)
node_role = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.role_id})
  SET
      n:Role,
      n.role_id = row.role_id,
      n.name = row.name,
      n.description = row.description,
      n.stated_in = row.stated_in,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ScaleLevel.csv  (10 rows, key level_id)
node_scalelevel = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.level_id})
  SET
      n:ScaleLevel,
      n.level_id = row.level_id,
      n.figure_id = row.figure_id,
      n.dimension = row.dimension,
      n.scale = row.scale,
      n.label = row.label,
      n.criteria = row.criteria,
      n.second_criteria = row.second_criteria,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Section.csv  (6 rows, key section_id)
node_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.section_id})
  SET
      n:Section,
      n.section_id = row.section_id,
      n.instrument_id = row.instrument_id,
      n.number = row.number,
      n.heading = row.heading,
      n.component_id = row.component_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Subsection.csv  (57 rows, key subsection_id)
node_subsection = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.subsection_id})
  SET
      n:Subsection,
      n.subsection_id = row.subsection_id,
      n.parent_id = row.parent_id,
      n.heading = row.heading,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_USSGProvision.csv  (13 rows, key provision_id)
node_ussgprovision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.provision_id})
  SET
      n:USSGProvision,
      n.provision_id = row.provision_id,
      n.citation = row.citation,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_applies_component.csv -> :APPLIES_COMPONENT  (5 rows)
rel_applies_component = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'APPLIES_COMPONENT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:APPLIES_COMPONENT]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_cites_provision.csv -> :CITES_PROVISION  (13 rows)
rel_cites_provision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CITES_PROVISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:CITES_PROVISION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :CONTAINS  (641 rows)
rel_contains = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CONTAINS'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:CONTAINS]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_cross_reference.csv -> :REFERENCES_PRINCIPLE  (19 rows)
rel_references_principle = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES_PRINCIPLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES_PRINCIPLE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_defines_term.csv -> :DEFINES_TERM  (27 rows)
rel_defines_term = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES_TERM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:DEFINES_TERM]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_element_discussion.csv -> :DISCUSSED_IN  (8 rows)
rel_discussed_in = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DISCUSSED_IN'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:DISCUSSED_IN]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_element_provision.csv -> :BASED_ON_PROVISION  (13 rows)
rel_based_on_provision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'BASED_ON_PROVISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:BASED_ON_PROVISION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_figure.csv -> :HAS_FIGURE  (24 rows)
rel_has_figure = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_FIGURE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:HAS_FIGURE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_key_characteristic.csv -> :HAS_KEY_CHARACTERISTIC  (120 rows)
rel_has_key_characteristic = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_KEY_CHARACTERISTIC'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:HAS_KEY_CHARACTERISTIC]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_principle.csv -> :HAS_PRINCIPLE  (20 rows)
rel_has_principle = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PRINCIPLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:HAS_PRINCIPLE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_scale_level.csv -> :HAS_SCALE_LEVEL  (10 rows)
rel_has_scale_level = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SCALE_LEVEL'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:HAS_SCALE_LEVEL]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_lists_expectation.csv -> :LISTS_EXPECTATION  (50 rows)
rel_lists_expectation = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'LISTS_EXPECTATION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:LISTS_EXPECTATION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_references_guidance.csv -> :REFERENCES_GUIDANCE  (10 rows)
rel_references_guidance = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES_GUIDANCE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES_GUIDANCE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_role_description.csv -> :DESCRIBED_IN  (4 rows)
rel_described_in = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DESCRIBED_IN'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:DESCRIBED_IN]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_role_responsibility.csv -> :HAS_RESPONSIBILITY  (58 rows)
rel_has_responsibility = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_RESPONSIBILITY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'COSO_ERM', node_id: row.target_id})
  MERGE (s)-[r:HAS_RESPONSIBILITY]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='COSO ERM',
    folder=FOLDER,
    jurisdiction='United States',
    source_document='COSO Enterprise Risk Management Framework.pdf | Compliance-Risk-Management-Applying-the-COSO-ERM-Framework.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Appendix', csv_name='nodes_Appendix.csv', id_column='appendix_id',
                 properties=['instrument_id', 'label', 'heading', 'source_document'],
                 rows=6, loadable=6, cypher=node_appendix),
        NodeStep(label='Clause', csv_name='nodes_Clause.csv', id_column='clause_id',
                 properties=['parent_id', 'label', 'text', 'source_document'],
                 rows=552, loadable=552, cypher=node_clause),
        NodeStep(label='Component', csv_name='nodes_Component.csv', id_column='component_id',
                 properties=['number', 'name', 'applied_in_section', 'source_document'],
                 rows=5, loadable=5, cypher=node_component),
        NodeStep(label='DefinedTerm', csv_name='nodes_DefinedTerm.csv', id_column='term_id',
                 properties=['term', 'definition', 'stated_in', 'instrument_id', 'source_document'],
                 rows=27, loadable=27, cypher=node_definedterm),
        NodeStep(label='ExternalGuidance', csv_name='nodes_ExternalGuidance.csv', id_column='guidance_id',
                 properties=['jurisdiction', 'name', 'description', 'stated_in', 'source_document'],
                 rows=10, loadable=10, cypher=node_externalguidance),
        NodeStep(label='Figure', csv_name='nodes_Figure.csv', id_column='figure_id',
                 properties=['label', 'caption', 'parent_id', 'source_document'],
                 rows=24, loadable=24, cypher=node_figure),
        NodeStep(label='Instrument', csv_name='nodes_Instrument.csv', id_column='instrument_id',
                 properties=['title', 'volume_part', 'issuing_body', 'author', 'date', 'copyright', 'contents', 'source_document'],
                 rows=2, loadable=2, cypher=node_instrument),
        NodeStep(label='KeyCharacteristic', csv_name='nodes_KeyCharacteristic.csv', id_column='kc_id',
                 properties=['principle_id', 'sequence', 'text', 'table', 'source_document'],
                 rows=120, loadable=120, cypher=node_keycharacteristic),
        NodeStep(label='Principle', csv_name='nodes_Principle.csv', id_column='principle_id',
                 properties=['number', 'name', 'statement', 'component_id', 'key_characteristics_table', 'source_document'],
                 rows=20, loadable=20, cypher=node_principle),
        NodeStep(label='PrioritizationCriterion', csv_name='nodes_PrioritizationCriterion.csv', id_column='criterion_id',
                 properties=['name', 'description', 'stated_in', 'source_document'],
                 rows=5, loadable=5, cypher=node_prioritizationcriterion),
        NodeStep(label='ProgramElement', csv_name='nodes_ProgramElement.csv', id_column='element_id',
                 properties=['number', 'name', 'source_document'],
                 rows=8, loadable=8, cypher=node_programelement),
        NodeStep(label='RiskResponse', csv_name='nodes_RiskResponse.csv', id_column='response_id',
                 properties=['name', 'description', 'stated_in', 'source_document'],
                 rows=7, loadable=7, cypher=node_riskresponse),
        NodeStep(label='Role', csv_name='nodes_Role.csv', id_column='role_id',
                 properties=['name', 'description', 'stated_in', 'source_document'],
                 rows=18, loadable=18, cypher=node_role),
        NodeStep(label='ScaleLevel', csv_name='nodes_ScaleLevel.csv', id_column='level_id',
                 properties=['figure_id', 'dimension', 'scale', 'label', 'criteria', 'second_criteria', 'source_document'],
                 rows=10, loadable=10, cypher=node_scalelevel),
        NodeStep(label='Section', csv_name='nodes_Section.csv', id_column='section_id',
                 properties=['instrument_id', 'number', 'heading', 'component_id', 'source_document'],
                 rows=6, loadable=6, cypher=node_section),
        NodeStep(label='Subsection', csv_name='nodes_Subsection.csv', id_column='subsection_id',
                 properties=['parent_id', 'heading', 'source_document'],
                 rows=57, loadable=57, cypher=node_subsection),
        NodeStep(label='USSGProvision', csv_name='nodes_USSGProvision.csv', id_column='provision_id',
                 properties=['citation', 'text', 'source_document'],
                 rows=13, loadable=13, cypher=node_ussgprovision),
    ],
    rel_steps=[
        RelStep(rel_type='APPLIES_COMPONENT', csv_name='rels_applies_component.csv',
                properties=[],
                rows=5, loadable=5, cypher=rel_applies_component),
        RelStep(rel_type='CITES_PROVISION', csv_name='rels_cites_provision.csv',
                properties=[],
                rows=13, loadable=13, cypher=rel_cites_provision),
        RelStep(rel_type='CONTAINS', csv_name='rels_contains.csv',
                properties=[],
                rows=641, loadable=641, cypher=rel_contains),
        RelStep(rel_type='REFERENCES_PRINCIPLE', csv_name='rels_cross_reference.csv',
                properties=[],
                rows=19, loadable=19, cypher=rel_references_principle),
        RelStep(rel_type='DEFINES_TERM', csv_name='rels_defines_term.csv',
                properties=[],
                rows=27, loadable=27, cypher=rel_defines_term),
        RelStep(rel_type='DISCUSSED_IN', csv_name='rels_element_discussion.csv',
                properties=[],
                rows=8, loadable=8, cypher=rel_discussed_in),
        RelStep(rel_type='BASED_ON_PROVISION', csv_name='rels_element_provision.csv',
                properties=[],
                rows=13, loadable=13, cypher=rel_based_on_provision),
        RelStep(rel_type='HAS_FIGURE', csv_name='rels_has_figure.csv',
                properties=[],
                rows=24, loadable=24, cypher=rel_has_figure),
        RelStep(rel_type='HAS_KEY_CHARACTERISTIC', csv_name='rels_has_key_characteristic.csv',
                properties=[],
                rows=120, loadable=120, cypher=rel_has_key_characteristic),
        RelStep(rel_type='HAS_PRINCIPLE', csv_name='rels_has_principle.csv',
                properties=[],
                rows=20, loadable=20, cypher=rel_has_principle),
        RelStep(rel_type='HAS_SCALE_LEVEL', csv_name='rels_has_scale_level.csv',
                properties=[],
                rows=10, loadable=10, cypher=rel_has_scale_level),
        RelStep(rel_type='LISTS_EXPECTATION', csv_name='rels_lists_expectation.csv',
                properties=[],
                rows=50, loadable=50, cypher=rel_lists_expectation),
        RelStep(rel_type='REFERENCES_GUIDANCE', csv_name='rels_references_guidance.csv',
                properties=[],
                rows=10, loadable=10, cypher=rel_references_guidance),
        RelStep(rel_type='DESCRIBED_IN', csv_name='rels_role_description.csv',
                properties=[],
                rows=4, loadable=4, cypher=rel_described_in),
        RelStep(rel_type='HAS_RESPONSIBILITY', csv_name='rels_role_responsibility.csv',
                properties=[],
                rows=58, loadable=58, cypher=rel_has_responsibility),
    ],
    expected_nodes_total=890,
    expected_rels_total=1022,
)

if __name__ == "__main__":
    run(LOADER)
