"""Loader — DIFC Data Protection Law.

Source folder : New sources/DIFC Data Protection Law
Source document(s):
    KB 2/UAE/DIFC Data Protection Law.pdf

Graph shape   : 8 node labels, 11 relationship types
Expected size : 847 nodes / 1,092 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/difc_data_protection_law.py --dry-run   # validate, write nothing
    python App_new/difc_data_protection_law.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'DIFC_DATA_PROTECTION_LAW'
FOLDER = 'DIFC Data Protection Law'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'DIFC_DATA_PROTECTION_LAW'})
SET f.name = 'DIFC Data Protection Law',
    f.jurisdiction = 'United Arab Emirates',
    f.folder = 'DIFC Data Protection Law',
    f.source_document = 'KB 2/UAE/DIFC Data Protection Law.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'DIFC_DATA_PROTECTION_LAW'})
MATCH (n:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW'})
WHERE NOT (:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Article.csv  (66 rows, key article_id)
node_article = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.article_id})
  SET
      n:Article,
      n.article_id = row.article_id,
      n.article_number = row.article_number,
      n.title = row.title,
      n.part_id = row.part_id,
      n.subpart_id = row.subpart_id,
      n.chapeau = row.chapeau,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Clause.csv  (662 rows, key clause_id)
node_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.clause_id})
  SET
      n:Clause,
      n.clause_id = row.clause_id,
      n.clause_ref = row.clause_ref,
      n.article_id = row.article_id,
      n.article_number = row.article_number,
      n.marker = row.marker,
      n.kind = row.kind,
      n.level = row.level,
      n.parent_clause_id = row.parent_clause_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (37 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.definition = row.definition,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Fine.csv  (37 rows, key fine_id)
node_fine = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.fine_id})
  SET
      n:Fine,
      n.fine_id = row.fine_id,
      n.article_reference = row.article_reference,
      n.contravention = row.contravention,
      n.maximum_fine_usd = row.maximum_fine_usd,
      n.currency = row.currency,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_InterpretationRule.csv  (27 rows, key interpretationrule_id)
node_interpretationrule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.interpretationrule_id})
  SET
      n:InterpretationRule,
      n.interpretationrule_id = row.interpretationrule_id,
      n.rule_ref = row.rule_ref,
      n.schedule_paragraph = row.schedule_paragraph,
      n.paragraph_title = row.paragraph_title,
      n.marker = row.marker,
      n.level = row.level,
      n.parent_rule_id = row.parent_rule_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Part.csv  (10 rows, key part_id)
node_part = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.part_id})
  SET
      n:Part,
      n.part_id = row.part_id,
      n.part_number = row.part_number,
      n.title = row.title,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Schedule.csv  (2 rows, key schedule_id)
node_schedule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.schedule_id})
  SET
      n:Schedule,
      n.schedule_id = row.schedule_id,
      n.label = row.label,
      n.description = row.description,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Subpart.csv  (6 rows, key subpart_id)
node_subpart = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.subpart_id})
  SET
      n:Subpart,
      n.subpart_id = row.subpart_id,
      n.subpart_label = row.subpart_label,
      n.title = row.title,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_CONTAINS_ARTICLE.csv -> :CONTAINS_ARTICLE  (66 rows)
rel_contains_article = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CONTAINS_ARTICLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.target_id})
  MERGE (s)-[r:CONTAINS_ARTICLE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_CONTAINS_RULE.csv -> :CONTAINS_RULE  (8 rows)
rel_contains_rule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CONTAINS_RULE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.target_id})
  MERGE (s)-[r:CONTAINS_RULE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_CROSS_REFERENCES.csv -> :CROSS_REFERENCES  (214 rows)
rel_cross_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CROSS_REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.target_id})
  MERGE (s)-[r:CROSS_REFERENCES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DEFINED_IN.csv -> :DEFINED_IN  (6 rows)
rel_defined_in = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINED_IN'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.target_id})
  MERGE (s)-[r:DEFINED_IN]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DEFINES_TERM.csv -> :DEFINES_TERM  (37 rows)
rel_defines_term = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES_TERM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.target_id})
  MERGE (s)-[r:DEFINES_TERM]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_CLAUSE.csv -> :HAS_CLAUSE  (288 rows)
rel_has_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.target_id})
  MERGE (s)-[r:HAS_CLAUSE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_SUBCLAUSE.csv -> :HAS_SUBCLAUSE  (374 rows)
rel_has_subclause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBCLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBCLAUSE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_SUBPART.csv -> :HAS_SUBPART  (6 rows)
rel_has_subpart = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBPART'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBPART]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_SUBRULE.csv -> :HAS_SUBRULE  (19 rows)
rel_has_subrule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBRULE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBRULE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_PENALISES.csv -> :PENALISES  (37 rows)
rel_penalises = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'PENALISES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.target_id})
  MERGE (s)-[r:PENALISES]->(t)
  SET r.maximum_fine_usd = row.maximum_fine_usd
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_SPECIFIES_FINE.csv -> :SPECIFIES_FINE  (37 rows)
rel_specifies_fine = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'SPECIFIES_FINE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'DIFC_DATA_PROTECTION_LAW', node_id: row.target_id})
  MERGE (s)-[r:SPECIFIES_FINE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='DIFC Data Protection Law',
    folder=FOLDER,
    jurisdiction='United Arab Emirates',
    source_document='KB 2/UAE/DIFC Data Protection Law.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Article', csv_name='nodes_Article.csv', id_column='article_id',
                 properties=['article_number', 'title', 'part_id', 'subpart_id', 'chapeau', 'source_document'],
                 rows=66, loadable=66, cypher=node_article),
        NodeStep(label='Clause', csv_name='nodes_Clause.csv', id_column='clause_id',
                 properties=['clause_ref', 'article_id', 'article_number', 'marker', 'kind', 'level', 'parent_clause_id', 'text', 'source_document'],
                 rows=662, loadable=662, cypher=node_clause),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'definition', 'source_document'],
                 rows=37, loadable=37, cypher=node_definition),
        NodeStep(label='Fine', csv_name='nodes_Fine.csv', id_column='fine_id',
                 properties=['article_reference', 'contravention', 'maximum_fine_usd', 'currency', 'source_document'],
                 rows=37, loadable=37, cypher=node_fine),
        NodeStep(label='InterpretationRule', csv_name='nodes_InterpretationRule.csv', id_column='interpretationrule_id',
                 properties=['rule_ref', 'schedule_paragraph', 'paragraph_title', 'marker', 'level', 'parent_rule_id', 'text', 'source_document'],
                 rows=27, loadable=27, cypher=node_interpretationrule),
        NodeStep(label='Part', csv_name='nodes_Part.csv', id_column='part_id',
                 properties=['part_number', 'title', 'source_document'],
                 rows=10, loadable=10, cypher=node_part),
        NodeStep(label='Schedule', csv_name='nodes_Schedule.csv', id_column='schedule_id',
                 properties=['label', 'description', 'source_document'],
                 rows=2, loadable=2, cypher=node_schedule),
        NodeStep(label='Subpart', csv_name='nodes_Subpart.csv', id_column='subpart_id',
                 properties=['subpart_label', 'title', 'source_document'],
                 rows=6, loadable=6, cypher=node_subpart),
    ],
    rel_steps=[
        RelStep(rel_type='CONTAINS_ARTICLE', csv_name='rels_CONTAINS_ARTICLE.csv',
                properties=[],
                rows=66, loadable=66, cypher=rel_contains_article),
        RelStep(rel_type='CONTAINS_RULE', csv_name='rels_CONTAINS_RULE.csv',
                properties=[],
                rows=8, loadable=8, cypher=rel_contains_rule),
        RelStep(rel_type='CROSS_REFERENCES', csv_name='rels_CROSS_REFERENCES.csv',
                properties=[],
                rows=214, loadable=214, cypher=rel_cross_references),
        RelStep(rel_type='DEFINED_IN', csv_name='rels_DEFINED_IN.csv',
                properties=[],
                rows=6, loadable=6, cypher=rel_defined_in),
        RelStep(rel_type='DEFINES_TERM', csv_name='rels_DEFINES_TERM.csv',
                properties=[],
                rows=37, loadable=37, cypher=rel_defines_term),
        RelStep(rel_type='HAS_CLAUSE', csv_name='rels_HAS_CLAUSE.csv',
                properties=[],
                rows=288, loadable=288, cypher=rel_has_clause),
        RelStep(rel_type='HAS_SUBCLAUSE', csv_name='rels_HAS_SUBCLAUSE.csv',
                properties=[],
                rows=374, loadable=374, cypher=rel_has_subclause),
        RelStep(rel_type='HAS_SUBPART', csv_name='rels_HAS_SUBPART.csv',
                properties=[],
                rows=6, loadable=6, cypher=rel_has_subpart),
        RelStep(rel_type='HAS_SUBRULE', csv_name='rels_HAS_SUBRULE.csv',
                properties=[],
                rows=19, loadable=19, cypher=rel_has_subrule),
        RelStep(rel_type='PENALISES', csv_name='rels_PENALISES.csv',
                properties=['maximum_fine_usd'],
                rows=37, loadable=37, cypher=rel_penalises),
        RelStep(rel_type='SPECIFIES_FINE', csv_name='rels_SPECIFIES_FINE.csv',
                properties=[],
                rows=37, loadable=37, cypher=rel_specifies_fine),
    ],
    expected_nodes_total=847,
    expected_rels_total=1092,
)

if __name__ == "__main__":
    run(LOADER)
