"""Loader — EU Cyber Resilience Act.

Source folder : New sources/EU Cyber Resilience Act
Source document(s):
    KB 2/Europe/EU Cyber Resilience Act.pdf

Graph shape   : 11 node labels, 12 relationship types
Expected size : 978 nodes / 1,258 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/eu_cyber_resilience_act.py --dry-run   # validate, write nothing
    python App_new/eu_cyber_resilience_act.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'EU_CYBER_RESILIENCE_ACT'
FOLDER = 'EU Cyber Resilience Act'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'EU_CYBER_RESILIENCE_ACT'})
SET f.name = 'EU Cyber Resilience Act',
    f.jurisdiction = 'European Union',
    f.folder = 'EU Cyber Resilience Act',
    f.source_document = 'KB 2/Europe/EU Cyber Resilience Act.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'EU_CYBER_RESILIENCE_ACT'})
MATCH (n:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT'})
WHERE NOT (:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Annex.csv  (8 rows, key annex_id)
node_annex = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.annex_id})
  SET
      n:Annex,
      n.annex_id = row.annex_id,
      n.number = row.number,
      n.title = row.title,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_AnnexProvision.csv  (142 rows, key annexprovision_id)
node_annexprovision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.annexprovision_id})
  SET
      n:AnnexProvision,
      n.annexprovision_id = row.annexprovision_id,
      n.annex = row.annex,
      n.part = row.part,
      n.label = row.label,
      n.level = row.level,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Article.csv  (71 rows, key article_id)
node_article = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.article_id})
  SET
      n:Article,
      n.article_id = row.article_id,
      n.number = row.number,
      n.title = row.title,
      n.chapter_id = row.chapter_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Chapter.csv  (8 rows, key chapter_id)
node_chapter = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.chapter_id})
  SET
      n:Chapter,
      n.chapter_id = row.chapter_id,
      n.number = row.number,
      n.title = row.title,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Date.csv  (11 rows, key date_id)
node_date = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.date_id})
  SET
      n:Date,
      n.date_id = row.date_id,
      n.date = row.date,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (51 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.number = row.number,
      n.term = row.term,
      n.definition_text = row.definition_text,
      n.full_text = row.full_text,
      n.defined_in = row.defined_in,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Penalty.csv  (3 rows, key penalty_id)
node_penalty = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.penalty_id})
  SET
      n:Penalty,
      n.penalty_id = row.penalty_id,
      n.max_administrative_fine = row.max_administrative_fine,
      n.max_share_of_turnover = row.max_share_of_turnover,
      n.source_provision = row.source_provision,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ProductCategory.csv  (26 rows, key productcategory_id)
node_productcategory = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.productcategory_id})
  SET
      n:ProductCategory,
      n.productcategory_id = row.productcategory_id,
      n.annex = row.annex,
      n.product_class = row.product_class,
      n.item_number = row.item_number,
      n.name = row.name,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Provision.csv  (527 rows, key provision_id)
node_provision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.provision_id})
  SET
      n:Provision,
      n.provision_id = row.provision_id,
      n.article_number = row.article_number,
      n.label = row.label,
      n.level = row.level,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Recital.csv  (130 rows, key recital_id)
node_recital = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.recital_id})
  SET
      n:Recital,
      n.recital_id = row.recital_id,
      n.number = row.number,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Regulation.csv  (1 rows, key regulation_id)
node_regulation = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.regulation_id})
  SET
      n:Regulation,
      n.regulation_id = row.regulation_id,
      n.identifier = row.identifier,
      n.title = row.title,
      n.short_title = row.short_title,
      n.date_of_adoption = row.date_of_adoption,
      n.date_of_publication = row.date_of_publication,
      n.date_of_application = row.date_of_application,
      n.eli = row.eli,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_DEFINES.csv -> :DEFINES  (51 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_ANNEX.csv -> :HAS_ANNEX  (8 rows)
rel_has_annex = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ANNEX'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.target_id})
  MERGE (s)-[r:HAS_ANNEX]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_ANNEX_PROVISION.csv -> :HAS_ANNEX_PROVISION  (142 rows)
rel_has_annex_provision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ANNEX_PROVISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.target_id})
  MERGE (s)-[r:HAS_ANNEX_PROVISION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_ARTICLE.csv -> :HAS_ARTICLE  (71 rows)
rel_has_article = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ARTICLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.target_id})
  MERGE (s)-[r:HAS_ARTICLE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_CHAPTER.csv -> :HAS_CHAPTER  (8 rows)
rel_has_chapter = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CHAPTER'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.target_id})
  MERGE (s)-[r:HAS_CHAPTER]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_PROVISION.csv -> :HAS_PROVISION  (527 rows)
rel_has_provision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PROVISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.target_id})
  MERGE (s)-[r:HAS_PROVISION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_RECITAL.csv -> :HAS_RECITAL  (130 rows)
rel_has_recital = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_RECITAL'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.target_id})
  MERGE (s)-[r:HAS_RECITAL]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_IMPOSES_PENALTY.csv -> :IMPOSES_PENALTY  (3 rows)
rel_imposes_penalty = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'IMPOSES_PENALTY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.target_id})
  MERGE (s)-[r:IMPOSES_PENALTY]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_LISTS_PRODUCT_CATEGORY.csv -> :LISTS_PRODUCT_CATEGORY  (26 rows)
rel_lists_product_category = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'LISTS_PRODUCT_CATEGORY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.target_id})
  MERGE (s)-[r:LISTS_PRODUCT_CATEGORY]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_REFERENCES_ANNEX.csv -> :REFERENCES_ANNEX  (121 rows)
rel_references_annex = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES_ANNEX'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES_ANNEX]->(t)
  SET r.citation = row.citation
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_REFERENCES_ARTICLE.csv -> :REFERENCES_ARTICLE  (155 rows)
rel_references_article = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES_ARTICLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES_ARTICLE]->(t)
  SET r.citation = row.citation
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_SETS_DATE.csv -> :SETS_DATE  (16 rows)
rel_sets_date = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'SETS_DATE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'EU_CYBER_RESILIENCE_ACT', node_id: row.target_id})
  MERGE (s)-[r:SETS_DATE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='EU Cyber Resilience Act',
    folder=FOLDER,
    jurisdiction='European Union',
    source_document='KB 2/Europe/EU Cyber Resilience Act.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Annex', csv_name='nodes_Annex.csv', id_column='annex_id',
                 properties=['number', 'title', 'source_document'],
                 rows=8, loadable=8, cypher=node_annex),
        NodeStep(label='AnnexProvision', csv_name='nodes_AnnexProvision.csv', id_column='annexprovision_id',
                 properties=['annex', 'part', 'label', 'level', 'text', 'source_document'],
                 rows=142, loadable=142, cypher=node_annexprovision),
        NodeStep(label='Article', csv_name='nodes_Article.csv', id_column='article_id',
                 properties=['number', 'title', 'chapter_id', 'source_document'],
                 rows=71, loadable=71, cypher=node_article),
        NodeStep(label='Chapter', csv_name='nodes_Chapter.csv', id_column='chapter_id',
                 properties=['number', 'title', 'source_document'],
                 rows=8, loadable=8, cypher=node_chapter),
        NodeStep(label='Date', csv_name='nodes_Date.csv', id_column='date_id',
                 properties=['date', 'source_document'],
                 rows=11, loadable=11, cypher=node_date),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['number', 'term', 'definition_text', 'full_text', 'defined_in', 'source_document'],
                 rows=51, loadable=51, cypher=node_definition),
        NodeStep(label='Penalty', csv_name='nodes_Penalty.csv', id_column='penalty_id',
                 properties=['max_administrative_fine', 'max_share_of_turnover', 'source_provision', 'text', 'source_document'],
                 rows=3, loadable=3, cypher=node_penalty),
        NodeStep(label='ProductCategory', csv_name='nodes_ProductCategory.csv', id_column='productcategory_id',
                 properties=['annex', 'product_class', 'item_number', 'name', 'source_document'],
                 rows=26, loadable=26, cypher=node_productcategory),
        NodeStep(label='Provision', csv_name='nodes_Provision.csv', id_column='provision_id',
                 properties=['article_number', 'label', 'level', 'text', 'source_document'],
                 rows=527, loadable=527, cypher=node_provision),
        NodeStep(label='Recital', csv_name='nodes_Recital.csv', id_column='recital_id',
                 properties=['number', 'text', 'source_document'],
                 rows=130, loadable=130, cypher=node_recital),
        NodeStep(label='Regulation', csv_name='nodes_Regulation.csv', id_column='regulation_id',
                 properties=['identifier', 'title', 'short_title', 'date_of_adoption', 'date_of_publication', 'date_of_application', 'eli', 'source_document'],
                 rows=1, loadable=1, cypher=node_regulation),
    ],
    rel_steps=[
        RelStep(rel_type='DEFINES', csv_name='rels_DEFINES.csv',
                properties=[],
                rows=51, loadable=51, cypher=rel_defines),
        RelStep(rel_type='HAS_ANNEX', csv_name='rels_HAS_ANNEX.csv',
                properties=[],
                rows=8, loadable=8, cypher=rel_has_annex),
        RelStep(rel_type='HAS_ANNEX_PROVISION', csv_name='rels_HAS_ANNEX_PROVISION.csv',
                properties=[],
                rows=142, loadable=142, cypher=rel_has_annex_provision),
        RelStep(rel_type='HAS_ARTICLE', csv_name='rels_HAS_ARTICLE.csv',
                properties=[],
                rows=71, loadable=71, cypher=rel_has_article),
        RelStep(rel_type='HAS_CHAPTER', csv_name='rels_HAS_CHAPTER.csv',
                properties=[],
                rows=8, loadable=8, cypher=rel_has_chapter),
        RelStep(rel_type='HAS_PROVISION', csv_name='rels_HAS_PROVISION.csv',
                properties=[],
                rows=527, loadable=527, cypher=rel_has_provision),
        RelStep(rel_type='HAS_RECITAL', csv_name='rels_HAS_RECITAL.csv',
                properties=[],
                rows=130, loadable=130, cypher=rel_has_recital),
        RelStep(rel_type='IMPOSES_PENALTY', csv_name='rels_IMPOSES_PENALTY.csv',
                properties=[],
                rows=3, loadable=3, cypher=rel_imposes_penalty),
        RelStep(rel_type='LISTS_PRODUCT_CATEGORY', csv_name='rels_LISTS_PRODUCT_CATEGORY.csv',
                properties=[],
                rows=26, loadable=26, cypher=rel_lists_product_category),
        RelStep(rel_type='REFERENCES_ANNEX', csv_name='rels_REFERENCES_ANNEX.csv',
                properties=['citation'],
                rows=121, loadable=121, cypher=rel_references_annex),
        RelStep(rel_type='REFERENCES_ARTICLE', csv_name='rels_REFERENCES_ARTICLE.csv',
                properties=['citation'],
                rows=155, loadable=155, cypher=rel_references_article),
        RelStep(rel_type='SETS_DATE', csv_name='rels_SETS_DATE.csv',
                properties=[],
                rows=16, loadable=16, cypher=rel_sets_date),
    ],
    expected_nodes_total=978,
    expected_rels_total=1258,
)

if __name__ == "__main__":
    run(LOADER)
