"""Loader — FedRAMP.

Source folder : New sources/FedRAMP
Source document(s):
    KB 2/USA/FedRAMP.pdf

Graph shape   : 13 node labels, 10 relationship types
Expected size : 141 nodes / 180 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/fedramp.py --dry-run   # validate, write nothing
    python App_new/fedramp.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'FEDRAMP'
FOLDER = 'FedRAMP'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'FEDRAMP'})
SET f.name = 'FedRAMP',
    f.jurisdiction = 'United States',
    f.folder = 'FedRAMP',
    f.source_document = 'KB 2/USA/FedRAMP.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'FEDRAMP'})
MATCH (n:NewSourceNode {framework_id: 'FEDRAMP'})
WHERE NOT (:NewSourceNode {framework_id: 'FEDRAMP'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_AuthorizationPath.csv  (2 rows, key authorizationpath_id)
node_authorizationpath = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.authorizationpath_id})
  SET
      n:AuthorizationPath,
      n.authorizationpath_id = row.authorizationpath_id,
      n.name = row.name,
      n.route = row.route,
      n.slide_id = row.slide_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Benefit.csv  (4 rows, key benefit_id)
node_benefit = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.benefit_id})
  SET
      n:Benefit,
      n.benefit_id = row.benefit_id,
      n.label = row.label,
      n.text = row.text,
      n.slide_id = row.slide_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ChangeTheme.csv  (4 rows, key changetheme_id)
node_changetheme = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.changetheme_id})
  SET
      n:ChangeTheme,
      n.changetheme_id = row.changetheme_id,
      n.name = row.name,
      n.fiscal_year = row.fiscal_year,
      n.slide_id = row.slide_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Concept.csv  (6 rows, key concept_id)
node_concept = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.concept_id})
  SET
      n:Concept,
      n.concept_id = row.concept_id,
      n.term = row.term,
      n.text = row.text,
      n.slide_id = row.slide_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Goal.csv  (3 rows, key goal_id)
node_goal = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.goal_id})
  SET
      n:Goal,
      n.goal_id = row.goal_id,
      n.number = row.number,
      n.name = row.name,
      n.text = row.text,
      n.slide_id = row.slide_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_GovernanceBody.csv  (10 rows, key governancebody_id)
node_governancebody = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.governancebody_id})
  SET
      n:GovernanceBody,
      n.governancebody_id = row.governancebody_id,
      n.name = row.name,
      n.kind = row.kind,
      n.slide_id = row.slide_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_LegalAuthority.csv  (4 rows, key legalauthority_id)
node_legalauthority = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.legalauthority_id})
  SET
      n:LegalAuthority,
      n.legalauthority_id = row.legalauthority_id,
      n.short_name = row.short_name,
      n.full_name = row.full_name,
      n.slide_id = row.slide_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_PathStep.csv  (5 rows, key pathstep_id)
node_pathstep = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.pathstep_id})
  SET
      n:PathStep,
      n.pathstep_id = row.pathstep_id,
      n.authorizationpath_id = row.authorizationpath_id,
      n.order = row.order,
      n.text = row.text,
      n.slide_id = row.slide_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Responsibility.csv  (7 rows, key responsibility_id)
node_responsibility = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.responsibility_id})
  SET
      n:Responsibility,
      n.responsibility_id = row.responsibility_id,
      n.governancebody_id = row.governancebody_id,
      n.text = row.text,
      n.slide_id = row.slide_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Slide.csv  (13 rows, key slide_id)
node_slide = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.slide_id})
  SET
      n:Slide,
      n.slide_id = row.slide_id,
      n.slide_number = row.slide_number,
      n.title = row.title,
      n.layout_note = row.layout_note,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_StakeholderGroup.csv  (3 rows, key stakeholdergroup_id)
node_stakeholdergroup = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.stakeholdergroup_id})
  SET
      n:StakeholderGroup,
      n.stakeholdergroup_id = row.stakeholdergroup_id,
      n.name = row.name,
      n.count = row.count,
      n.note = row.note,
      n.slide_id = row.slide_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Statement.csv  (74 rows, key statement_id)
node_statement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.statement_id})
  SET
      n:Statement,
      n.statement_id = row.statement_id,
      n.slide_id = row.slide_id,
      n.heading = row.heading,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Worklane.csv  (6 rows, key worklane_id)
node_worklane = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.worklane_id})
  SET
      n:Worklane,
      n.worklane_id = row.worklane_id,
      n.name = row.name,
      n.slide_id = row.slide_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_body_has_responsibility.csv -> :HAS_RESPONSIBILITY  (7 rows)
rel_has_responsibility = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_RESPONSIBILITY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.target_id})
  MERGE (s)-[r:HAS_RESPONSIBILITY]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_changetheme_has_action.csv -> :HAS_ACTION  (8 rows)
rel_has_action = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ACTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.target_id})
  MERGE (s)-[r:HAS_ACTION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_path_body.csv -> :AUTHORIZED_BY  (1 rows)
rel_authorized_by = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'AUTHORIZED_BY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.target_id})
  MERGE (s)-[r:AUTHORIZED_BY]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_path_body.csv -> :PACKAGE_SUBMITTED_TO  (1 rows)
rel_package_submitted_to = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'PACKAGE_SUBMITTED_TO'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.target_id})
  MERGE (s)-[r:PACKAGE_SUBMITTED_TO]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_path_has_step.csv -> :HAS_STEP  (5 rows)
rel_has_step = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_STEP'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.target_id})
  MERGE (s)-[r:HAS_STEP]->(t)
  SET r.order = row.order
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_pmo_operates_worklane.csv -> :OPERATES_WORKLANE  (6 rows)
rel_operates_worklane = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'OPERATES_WORKLANE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.target_id})
  MERGE (s)-[r:OPERATES_WORKLANE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_slide_has_statement.csv -> :HAS_STATEMENT  (74 rows)
rel_has_statement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_STATEMENT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.target_id})
  MERGE (s)-[r:HAS_STATEMENT]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_slide_next.csv -> :NEXT_SLIDE  (12 rows)
rel_next_slide = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'NEXT_SLIDE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.target_id})
  MERGE (s)-[r:NEXT_SLIDE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_slide_presents.csv -> :PRESENTS  (42 rows)
rel_presents = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'PRESENTS'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.target_id})
  MERGE (s)-[r:PRESENTS]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_worklane_has_activity.csv -> :HAS_ACTIVITY  (24 rows)
rel_has_activity = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ACTIVITY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FEDRAMP', node_id: row.target_id})
  MERGE (s)-[r:HAS_ACTIVITY]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='FedRAMP',
    folder=FOLDER,
    jurisdiction='United States',
    source_document='KB 2/USA/FedRAMP.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='AuthorizationPath', csv_name='nodes_AuthorizationPath.csv', id_column='authorizationpath_id',
                 properties=['name', 'route', 'slide_id', 'source_document'],
                 rows=2, loadable=2, cypher=node_authorizationpath),
        NodeStep(label='Benefit', csv_name='nodes_Benefit.csv', id_column='benefit_id',
                 properties=['label', 'text', 'slide_id', 'source_document'],
                 rows=4, loadable=4, cypher=node_benefit),
        NodeStep(label='ChangeTheme', csv_name='nodes_ChangeTheme.csv', id_column='changetheme_id',
                 properties=['name', 'fiscal_year', 'slide_id', 'source_document'],
                 rows=4, loadable=4, cypher=node_changetheme),
        NodeStep(label='Concept', csv_name='nodes_Concept.csv', id_column='concept_id',
                 properties=['term', 'text', 'slide_id', 'source_document'],
                 rows=6, loadable=6, cypher=node_concept),
        NodeStep(label='Goal', csv_name='nodes_Goal.csv', id_column='goal_id',
                 properties=['number', 'name', 'text', 'slide_id', 'source_document'],
                 rows=3, loadable=3, cypher=node_goal),
        NodeStep(label='GovernanceBody', csv_name='nodes_GovernanceBody.csv', id_column='governancebody_id',
                 properties=['name', 'kind', 'slide_id', 'source_document'],
                 rows=10, loadable=10, cypher=node_governancebody),
        NodeStep(label='LegalAuthority', csv_name='nodes_LegalAuthority.csv', id_column='legalauthority_id',
                 properties=['short_name', 'full_name', 'slide_id', 'text', 'source_document'],
                 rows=4, loadable=4, cypher=node_legalauthority),
        NodeStep(label='PathStep', csv_name='nodes_PathStep.csv', id_column='pathstep_id',
                 properties=['authorizationpath_id', 'order', 'text', 'slide_id', 'source_document'],
                 rows=5, loadable=5, cypher=node_pathstep),
        NodeStep(label='Responsibility', csv_name='nodes_Responsibility.csv', id_column='responsibility_id',
                 properties=['governancebody_id', 'text', 'slide_id', 'source_document'],
                 rows=7, loadable=7, cypher=node_responsibility),
        NodeStep(label='Slide', csv_name='nodes_Slide.csv', id_column='slide_id',
                 properties=['slide_number', 'title', 'layout_note', 'source_document'],
                 rows=13, loadable=13, cypher=node_slide),
        NodeStep(label='StakeholderGroup', csv_name='nodes_StakeholderGroup.csv', id_column='stakeholdergroup_id',
                 properties=['name', 'count', 'note', 'slide_id', 'source_document'],
                 rows=3, loadable=3, cypher=node_stakeholdergroup),
        NodeStep(label='Statement', csv_name='nodes_Statement.csv', id_column='statement_id',
                 properties=['slide_id', 'heading', 'text', 'source_document'],
                 rows=74, loadable=74, cypher=node_statement),
        NodeStep(label='Worklane', csv_name='nodes_Worklane.csv', id_column='worklane_id',
                 properties=['name', 'slide_id', 'source_document'],
                 rows=6, loadable=6, cypher=node_worklane),
    ],
    rel_steps=[
        RelStep(rel_type='HAS_RESPONSIBILITY', csv_name='rels_body_has_responsibility.csv',
                properties=[],
                rows=7, loadable=7, cypher=rel_has_responsibility),
        RelStep(rel_type='HAS_ACTION', csv_name='rels_changetheme_has_action.csv',
                properties=[],
                rows=8, loadable=8, cypher=rel_has_action),
        RelStep(rel_type='AUTHORIZED_BY', csv_name='rels_path_body.csv',
                properties=[],
                rows=1, loadable=1, cypher=rel_authorized_by),
        RelStep(rel_type='PACKAGE_SUBMITTED_TO', csv_name='rels_path_body.csv',
                properties=[],
                rows=1, loadable=1, cypher=rel_package_submitted_to),
        RelStep(rel_type='HAS_STEP', csv_name='rels_path_has_step.csv',
                properties=['order'],
                rows=5, loadable=5, cypher=rel_has_step),
        RelStep(rel_type='OPERATES_WORKLANE', csv_name='rels_pmo_operates_worklane.csv',
                properties=[],
                rows=6, loadable=6, cypher=rel_operates_worklane),
        RelStep(rel_type='HAS_STATEMENT', csv_name='rels_slide_has_statement.csv',
                properties=[],
                rows=74, loadable=74, cypher=rel_has_statement),
        RelStep(rel_type='NEXT_SLIDE', csv_name='rels_slide_next.csv',
                properties=[],
                rows=12, loadable=12, cypher=rel_next_slide),
        RelStep(rel_type='PRESENTS', csv_name='rels_slide_presents.csv',
                properties=[],
                rows=42, loadable=42, cypher=rel_presents),
        RelStep(rel_type='HAS_ACTIVITY', csv_name='rels_worklane_has_activity.csv',
                properties=[],
                rows=24, loadable=24, cypher=rel_has_activity),
    ],
    expected_nodes_total=141,
    expected_rels_total=180,
)

if __name__ == "__main__":
    run(LOADER)
