"""Loader — FERPA (guidance).

Source folder : New sources/FERPA (guidance)
Source document(s):
    SPPO-21-04 A Parent Guide to the Family Educational Rights and Privacy Act (FERPA), U.S. Department of Education, Student Privacy Policy Office, issued July 9, 2021 (KB 2/USA/A parent guide to ferpa_508.pdf)
    SPPO-23-01 An Eligible Student Guide to the Family Educational Rights and Privacy Act (FERPA), U.S. Department of Education, Student Privacy Policy Office, issued March 8, 2023 (KB 2/USA/Family Educational Rights and Privacy Act.pdf)

Graph shape   : 8 node labels, 11 relationship types
Expected size : 151 nodes / 272 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/ferpa_guidance.py --dry-run   # validate, write nothing
    python App_new/ferpa_guidance.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'FERPA_GUIDANCE'
FOLDER = 'FERPA (guidance)'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'FERPA_GUIDANCE'})
SET f.name = 'FERPA (guidance)',
    f.jurisdiction = 'United States',
    f.folder = 'FERPA (guidance)',
    f.source_document = 'SPPO-21-04 A Parent Guide to the Family Educational Rights and Privacy Act (FERPA), U.S. Department of Education, Student Privacy Policy Office, issued July 9, 2021 (KB 2/USA/A parent guide to ferpa_508.pdf) | SPPO-23-01 An Eligible Student Guide to the Family Educational Rights and Privacy Act (FERPA), U.S. Department of Education, Student Privacy Policy Office, issued March 8, 2023 (KB 2/USA/Family Educational Rights and Privacy Act.pdf)',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'FERPA_GUIDANCE'})
MATCH (n:NewSourceNode {framework_id: 'FERPA_GUIDANCE'})
WHERE NOT (:NewSourceNode {framework_id: 'FERPA_GUIDANCE'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Clause.csv  (71 rows, key clause_id)
node_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.clause_id})
  SET
      n:Clause,
      n.clause_id = row.clause_id,
      n.section_id = row.section_id,
      n.document_id = row.document_id,
      n.label = row.label,
      n.text = row.text,
      n.source_page = row.source_page,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (10 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.verbatim_definition = row.verbatim_definition,
      n.primary_clause_id = row.primary_clause_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_DisclosureException.csv  (14 rows, key disclosureexception_id)
node_disclosureexception = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.disclosureexception_id})
  SET
      n:DisclosureException,
      n.disclosureexception_id = row.disclosureexception_id,
      n.name = row.name,
      n.category = row.category,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Document.csv  (2 rows, key document_id)
node_document = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.document_id})
  SET
      n:Document,
      n.document_id = row.document_id,
      n.title = row.title,
      n.designation = row.designation,
      n.issuing_body = row.issuing_body,
      n.issued_date = row.issued_date,
      n.instrument_type = row.instrument_type,
      n.audience = row.audience,
      n.force_of_law_statement = row.force_of_law_statement,
      n.status_caveat = row.status_caveat,
      n.source_pdf = row.source_pdf,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ExternalReference.csv  (7 rows, key externalreference_id)
node_externalreference = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.externalreference_id})
  SET
      n:ExternalReference,
      n.externalreference_id = row.externalreference_id,
      n.citation = row.citation,
      n.reference_type = row.reference_type,
      n.subject = row.subject,
      n.availability = row.availability,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Resource.csv  (12 rows, key resource_id)
node_resource = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.resource_id})
  SET
      n:Resource,
      n.resource_id = row.resource_id,
      n.name = row.name,
      n.location = row.location,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Right.csv  (8 rows, key right_id)
node_right = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.right_id})
  SET
      n:Right,
      n.right_id = row.right_id,
      n.name = row.name,
      n.verbatim_basis = row.verbatim_basis,
      n.stated_timeframe = row.stated_timeframe,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Section.csv  (27 rows, key section_id)
node_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.section_id})
  SET
      n:Section,
      n.section_id = row.section_id,
      n.document_id = row.document_id,
      n.section_number = row.section_number,
      n.heading = row.heading,
      n.level = row.level,
      n.parent_section_id = row.parent_section_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_CITES_EXTERNAL.csv -> :CITES_EXTERNAL  (21 rows)
rel_cites_external = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CITES_EXTERNAL'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.target_id})
  MERGE (s)-[r:CITES_EXTERNAL]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_CORRESPONDS_TO.csv -> :CORRESPONDS_TO  (31 rows)
rel_corresponds_to = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CORRESPONDS_TO'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.target_id})
  MERGE (s)-[r:CORRESPONDS_TO]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_COVERS_RIGHT.csv -> :COVERS_RIGHT  (16 rows)
rel_covers_right = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'COVERS_RIGHT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.target_id})
  MERGE (s)-[r:COVERS_RIGHT]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DEFINES_TERM.csv -> :DEFINES_TERM  (19 rows)
rel_defines_term = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES_TERM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.target_id})
  MERGE (s)-[r:DEFINES_TERM]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DESCRIBES_EXCEPTION.csv -> :DESCRIBES_EXCEPTION  (26 rows)
rel_describes_exception = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DESCRIBES_EXCEPTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.target_id})
  MERGE (s)-[r:DESCRIBES_EXCEPTION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DESCRIBES_RIGHT.csv -> :DESCRIBES_RIGHT  (27 rows)
rel_describes_right = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DESCRIBES_RIGHT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.target_id})
  MERGE (s)-[r:DESCRIBES_RIGHT]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_CLAUSE.csv -> :HAS_CLAUSE  (71 rows)
rel_has_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_CLAUSE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_CONDITION.csv -> :HAS_CONDITION  (14 rows)
rel_has_condition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CONDITION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_CONDITION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_SECTION.csv -> :HAS_SECTION  (11 rows)
rel_has_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_SECTION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_SUBSECTION.csv -> :HAS_SUBSECTION  (16 rows)
rel_has_subsection = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBSECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBSECTION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_LINKS_TO.csv -> :LINKS_TO  (20 rows)
rel_links_to = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'LINKS_TO'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FERPA_GUIDANCE', node_id: row.target_id})
  MERGE (s)-[r:LINKS_TO]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='FERPA (guidance)',
    folder=FOLDER,
    jurisdiction='United States',
    source_document='SPPO-21-04 A Parent Guide to the Family Educational Rights and Privacy Act (FERPA), U.S. Department of Education, Student Privacy Policy Office, issued July 9, 2021 (KB 2/USA/A parent guide to ferpa_508.pdf) | SPPO-23-01 An Eligible Student Guide to the Family Educational Rights and Privacy Act (FERPA), U.S. Department of Education, Student Privacy Policy Office, issued March 8, 2023 (KB 2/USA/Family Educational Rights and Privacy Act.pdf)',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Clause', csv_name='nodes_Clause.csv', id_column='clause_id',
                 properties=['section_id', 'document_id', 'label', 'text', 'source_page', 'source_document'],
                 rows=71, loadable=71, cypher=node_clause),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'verbatim_definition', 'primary_clause_id', 'source_document'],
                 rows=10, loadable=10, cypher=node_definition),
        NodeStep(label='DisclosureException', csv_name='nodes_DisclosureException.csv', id_column='disclosureexception_id',
                 properties=['name', 'category', 'source_document'],
                 rows=14, loadable=14, cypher=node_disclosureexception),
        NodeStep(label='Document', csv_name='nodes_Document.csv', id_column='document_id',
                 properties=['title', 'designation', 'issuing_body', 'issued_date', 'instrument_type', 'audience', 'force_of_law_statement', 'status_caveat', 'source_pdf', 'source_document'],
                 rows=2, loadable=2, cypher=node_document),
        NodeStep(label='ExternalReference', csv_name='nodes_ExternalReference.csv', id_column='externalreference_id',
                 properties=['citation', 'reference_type', 'subject', 'availability', 'source_document'],
                 rows=7, loadable=7, cypher=node_externalreference),
        NodeStep(label='Resource', csv_name='nodes_Resource.csv', id_column='resource_id',
                 properties=['name', 'location', 'source_document'],
                 rows=12, loadable=12, cypher=node_resource),
        NodeStep(label='Right', csv_name='nodes_Right.csv', id_column='right_id',
                 properties=['name', 'verbatim_basis', 'stated_timeframe', 'source_document'],
                 rows=8, loadable=8, cypher=node_right),
        NodeStep(label='Section', csv_name='nodes_Section.csv', id_column='section_id',
                 properties=['document_id', 'section_number', 'heading', 'level', 'parent_section_id', 'source_document'],
                 rows=27, loadable=27, cypher=node_section),
    ],
    rel_steps=[
        RelStep(rel_type='CITES_EXTERNAL', csv_name='rels_CITES_EXTERNAL.csv',
                properties=[],
                rows=21, loadable=21, cypher=rel_cites_external),
        RelStep(rel_type='CORRESPONDS_TO', csv_name='rels_CORRESPONDS_TO.csv',
                properties=[],
                rows=31, loadable=31, cypher=rel_corresponds_to),
        RelStep(rel_type='COVERS_RIGHT', csv_name='rels_COVERS_RIGHT.csv',
                properties=[],
                rows=16, loadable=16, cypher=rel_covers_right),
        RelStep(rel_type='DEFINES_TERM', csv_name='rels_DEFINES_TERM.csv',
                properties=[],
                rows=19, loadable=19, cypher=rel_defines_term),
        RelStep(rel_type='DESCRIBES_EXCEPTION', csv_name='rels_DESCRIBES_EXCEPTION.csv',
                properties=[],
                rows=26, loadable=26, cypher=rel_describes_exception),
        RelStep(rel_type='DESCRIBES_RIGHT', csv_name='rels_DESCRIBES_RIGHT.csv',
                properties=[],
                rows=27, loadable=27, cypher=rel_describes_right),
        RelStep(rel_type='HAS_CLAUSE', csv_name='rels_HAS_CLAUSE.csv',
                properties=[],
                rows=71, loadable=71, cypher=rel_has_clause),
        RelStep(rel_type='HAS_CONDITION', csv_name='rels_HAS_CONDITION.csv',
                properties=[],
                rows=14, loadable=14, cypher=rel_has_condition),
        RelStep(rel_type='HAS_SECTION', csv_name='rels_HAS_SECTION.csv',
                properties=[],
                rows=11, loadable=11, cypher=rel_has_section),
        RelStep(rel_type='HAS_SUBSECTION', csv_name='rels_HAS_SUBSECTION.csv',
                properties=[],
                rows=16, loadable=16, cypher=rel_has_subsection),
        RelStep(rel_type='LINKS_TO', csv_name='rels_LINKS_TO.csv',
                properties=[],
                rows=20, loadable=20, cypher=rel_links_to),
    ],
    expected_nodes_total=151,
    expected_rels_total=272,
)

if __name__ == "__main__":
    run(LOADER)
