"""Loader — FFIEC Cybersecurity Assessment Tool.

Source folder : New sources/FFIEC Cybersecurity Assessment Tool
Source document(s):
    KB 2/USA/FFIEC Cybersecurity Assessment Tool.pdf

Graph shape   : 14 node labels, 13 relationship types
Expected size : 873 nodes / 1,598 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/ffiec_cybersecurity_assessment_tool.py --dry-run   # validate, write nothing
    python App_new/ffiec_cybersecurity_assessment_tool.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL'
FOLDER = 'FFIEC Cybersecurity Assessment Tool'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL'})
SET f.name = 'FFIEC Cybersecurity Assessment Tool',
    f.jurisdiction = 'United States',
    f.folder = 'FFIEC Cybersecurity Assessment Tool',
    f.source_document = 'KB 2/USA/FFIEC Cybersecurity Assessment Tool.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL'})
MATCH (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL'})
WHERE NOT (:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_AssessmentFactor.csv  (15 rows, key assessmentfactor_id)
node_assessmentfactor = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.assessmentfactor_id})
  SET
      n:AssessmentFactor,
      n.assessmentfactor_id = row.assessmentfactor_id,
      n.name = row.name,
      n.definition = row.definition,
      n.domain_id = row.domain_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Component.csv  (30 rows, key component_id)
node_component = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.component_id})
  SET
      n:Component,
      n.component_id = row.component_id,
      n.name = row.name,
      n.name_as_printed = row.name_as_printed,
      n.assessmentfactor_id = row.assessmentfactor_id,
      n.domain_id = row.domain_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_DeclarativeStatement.csv  (494 rows, key declarativestatement_id)
node_declarativestatement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.declarativestatement_id})
  SET
      n:DeclarativeStatement,
      n.declarativestatement_id = row.declarativestatement_id,
      n.component_id = row.component_id,
      n.component_name = row.component_name,
      n.assessmentfactor_id = row.assessmentfactor_id,
      n.assessment_factor_name = row.assessment_factor_name,
      n.domain_id = row.domain_id,
      n.domain_name = row.domain_name,
      n.maturity_level = row.maturity_level,
      n.text = row.text,
      n.it_handbook_citation = row.it_handbook_citation,
      n.applicability_note = row.applicability_note,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_DefinedTerm.csv  (2 rows, key definedterm_id)
node_definedterm = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.definedterm_id})
  SET
      n:DefinedTerm,
      n.definedterm_id = row.definedterm_id,
      n.term = row.term,
      n.definition = row.definition,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Domain.csv  (5 rows, key domain_id)
node_domain = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.domain_id})
  SET
      n:Domain,
      n.domain_id = row.domain_id,
      n.number = row.number,
      n.name = row.name,
      n.description = row.description,
      n.part_id = row.part_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ITHandbookReference.csv  (71 rows, key ithandbookreference_id)
node_ithandbookreference = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.ithandbookreference_id})
  SET
      n:ITHandbookReference,
      n.ithandbookreference_id = row.ithandbookreference_id,
      n.citation = row.citation,
      n.booklet = row.booklet,
      n.page = row.page,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Instrument.csv  (1 rows, key instrument_id)
node_instrument = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.instrument_id})
  SET
      n:Instrument,
      n.instrument_id = row.instrument_id,
      n.title = row.title,
      n.issuing_body = row.issuing_body,
      n.version_date = row.version_date,
      n.omb_control_number = row.omb_control_number,
      n.omb_expiration_date = row.omb_expiration_date,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_MaturityLevel.csv  (5 rows, key maturitylevel_id)
node_maturitylevel = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.maturitylevel_id})
  SET
      n:MaturityLevel,
      n.maturitylevel_id = row.maturitylevel_id,
      n.name = row.name,
      n.definition = row.definition,
      n.ordinal = row.ordinal,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Part.csv  (2 rows, key part_id)
node_part = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.part_id})
  SET
      n:Part,
      n.part_id = row.part_id,
      n.title = row.title,
      n.description = row.description,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Resource.csv  (4 rows, key resource_id)
node_resource = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.resource_id})
  SET
      n:Resource,
      n.resource_id = row.resource_id,
      n.title = row.title,
      n.stated_text = row.stated_text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_RiskActivity.csv  (39 rows, key riskactivity_id)
node_riskactivity = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.riskactivity_id})
  SET
      n:RiskActivity,
      n.riskactivity_id = row.riskactivity_id,
      n.activity_service_or_product = row.activity_service_or_product,
      n.riskcategory_id = row.riskcategory_id,
      n.category_name = row.category_name,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_RiskCategory.csv  (5 rows, key riskcategory_id)
node_riskcategory = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.riskcategory_id})
  SET
      n:RiskCategory,
      n.riskcategory_id = row.riskcategory_id,
      n.name = row.name,
      n.description = row.description,
      n.part_id = row.part_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_RiskLevel.csv  (5 rows, key risklevel_id)
node_risklevel = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.risklevel_id})
  SET
      n:RiskLevel,
      n.risklevel_id = row.risklevel_id,
      n.name = row.name,
      n.label = row.label,
      n.definition = row.definition,
      n.ordinal = row.ordinal,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_RiskLevelStatement.csv  (195 rows, key risklevelstatement_id)
node_risklevelstatement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.risklevelstatement_id})
  SET
      n:RiskLevelStatement,
      n.risklevelstatement_id = row.risklevelstatement_id,
      n.riskactivity_id = row.riskactivity_id,
      n.activity_service_or_product = row.activity_service_or_product,
      n.category_name = row.category_name,
      n.risk_level = row.risk_level,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_activity_has_risk_level_statement.csv -> :HAS_RISK_LEVEL_STATEMENT  (195 rows)
rel_has_risk_level_statement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_RISK_LEVEL_STATEMENT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:HAS_RISK_LEVEL_STATEMENT]->(t)
  SET r.risk_level = row.risk_level
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_assessment_factor_has_component.csv -> :HAS_COMPONENT  (30 rows)
rel_has_component = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_COMPONENT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:HAS_COMPONENT]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_category_has_activity.csv -> :HAS_ACTIVITY  (39 rows)
rel_has_activity = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ACTIVITY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:HAS_ACTIVITY]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_component_has_declarative_statement.csv -> :HAS_DECLARATIVE_STATEMENT  (494 rows)
rel_has_declarative_statement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_DECLARATIVE_STATEMENT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:HAS_DECLARATIVE_STATEMENT]->(t)
  SET r.maturity_level = row.maturity_level
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_declarative_statement_at_maturity_level.csv -> :AT_MATURITY_LEVEL  (494 rows)
rel_at_maturity_level = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'AT_MATURITY_LEVEL'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:AT_MATURITY_LEVEL]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_declarative_statement_maps_to_it_handbook.csv -> :MAPS_TO_IT_HANDBOOK  (118 rows)
rel_maps_to_it_handbook = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'MAPS_TO_IT_HANDBOOK'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:MAPS_TO_IT_HANDBOOK]->(t)
  SET r.citation = row.citation
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_domain_has_assessment_factor.csv -> :HAS_ASSESSMENT_FACTOR  (15 rows)
rel_has_assessment_factor = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ASSESSMENT_FACTOR'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:HAS_ASSESSMENT_FACTOR]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_part.csv -> :HAS_PART  (2 rows)
rel_has_part = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PART'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:HAS_PART]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_instrument_defines_term.csv -> :DEFINES_TERM  (2 rows)
rel_defines_term = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES_TERM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:DEFINES_TERM]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_instrument_has_resource.csv -> :HAS_RESOURCE  (4 rows)
rel_has_resource = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_RESOURCE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:HAS_RESOURCE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_part_has_domain.csv -> :HAS_DOMAIN  (5 rows)
rel_has_domain = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_DOMAIN'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:HAS_DOMAIN]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_part_has_risk_category.csv -> :HAS_RISK_CATEGORY  (5 rows)
rel_has_risk_category = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_RISK_CATEGORY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:HAS_RISK_CATEGORY]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_risk_statement_at_risk_level.csv -> :AT_RISK_LEVEL  (195 rows)
rel_at_risk_level = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'AT_RISK_LEVEL'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'FFIEC_CYBERSECURITY_ASSESSMENT_TOOL', node_id: row.target_id})
  MERGE (s)-[r:AT_RISK_LEVEL]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='FFIEC Cybersecurity Assessment Tool',
    folder=FOLDER,
    jurisdiction='United States',
    source_document='KB 2/USA/FFIEC Cybersecurity Assessment Tool.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='AssessmentFactor', csv_name='nodes_AssessmentFactor.csv', id_column='assessmentfactor_id',
                 properties=['name', 'definition', 'domain_id', 'source_document'],
                 rows=15, loadable=15, cypher=node_assessmentfactor),
        NodeStep(label='Component', csv_name='nodes_Component.csv', id_column='component_id',
                 properties=['name', 'name_as_printed', 'assessmentfactor_id', 'domain_id', 'source_document'],
                 rows=30, loadable=30, cypher=node_component),
        NodeStep(label='DeclarativeStatement', csv_name='nodes_DeclarativeStatement.csv', id_column='declarativestatement_id',
                 properties=['component_id', 'component_name', 'assessmentfactor_id', 'assessment_factor_name', 'domain_id', 'domain_name', 'maturity_level', 'text', 'it_handbook_citation', 'applicability_note', 'source_document'],
                 rows=494, loadable=494, cypher=node_declarativestatement),
        NodeStep(label='DefinedTerm', csv_name='nodes_DefinedTerm.csv', id_column='definedterm_id',
                 properties=['term', 'definition', 'source_document'],
                 rows=2, loadable=2, cypher=node_definedterm),
        NodeStep(label='Domain', csv_name='nodes_Domain.csv', id_column='domain_id',
                 properties=['number', 'name', 'description', 'part_id', 'source_document'],
                 rows=5, loadable=5, cypher=node_domain),
        NodeStep(label='ITHandbookReference', csv_name='nodes_ITHandbookReference.csv', id_column='ithandbookreference_id',
                 properties=['citation', 'booklet', 'page', 'source_document'],
                 rows=71, loadable=71, cypher=node_ithandbookreference),
        NodeStep(label='Instrument', csv_name='nodes_Instrument.csv', id_column='instrument_id',
                 properties=['title', 'issuing_body', 'version_date', 'omb_control_number', 'omb_expiration_date', 'source_document'],
                 rows=1, loadable=1, cypher=node_instrument),
        NodeStep(label='MaturityLevel', csv_name='nodes_MaturityLevel.csv', id_column='maturitylevel_id',
                 properties=['name', 'definition', 'ordinal', 'source_document'],
                 rows=5, loadable=5, cypher=node_maturitylevel),
        NodeStep(label='Part', csv_name='nodes_Part.csv', id_column='part_id',
                 properties=['title', 'description', 'source_document'],
                 rows=2, loadable=2, cypher=node_part),
        NodeStep(label='Resource', csv_name='nodes_Resource.csv', id_column='resource_id',
                 properties=['title', 'stated_text', 'source_document'],
                 rows=4, loadable=4, cypher=node_resource),
        NodeStep(label='RiskActivity', csv_name='nodes_RiskActivity.csv', id_column='riskactivity_id',
                 properties=['activity_service_or_product', 'riskcategory_id', 'category_name', 'source_document'],
                 rows=39, loadable=39, cypher=node_riskactivity),
        NodeStep(label='RiskCategory', csv_name='nodes_RiskCategory.csv', id_column='riskcategory_id',
                 properties=['name', 'description', 'part_id', 'source_document'],
                 rows=5, loadable=5, cypher=node_riskcategory),
        NodeStep(label='RiskLevel', csv_name='nodes_RiskLevel.csv', id_column='risklevel_id',
                 properties=['name', 'label', 'definition', 'ordinal', 'source_document'],
                 rows=5, loadable=5, cypher=node_risklevel),
        NodeStep(label='RiskLevelStatement', csv_name='nodes_RiskLevelStatement.csv', id_column='risklevelstatement_id',
                 properties=['riskactivity_id', 'activity_service_or_product', 'category_name', 'risk_level', 'text', 'source_document'],
                 rows=195, loadable=195, cypher=node_risklevelstatement),
    ],
    rel_steps=[
        RelStep(rel_type='HAS_RISK_LEVEL_STATEMENT', csv_name='rels_activity_has_risk_level_statement.csv',
                properties=['risk_level'],
                rows=195, loadable=195, cypher=rel_has_risk_level_statement),
        RelStep(rel_type='HAS_COMPONENT', csv_name='rels_assessment_factor_has_component.csv',
                properties=[],
                rows=30, loadable=30, cypher=rel_has_component),
        RelStep(rel_type='HAS_ACTIVITY', csv_name='rels_category_has_activity.csv',
                properties=[],
                rows=39, loadable=39, cypher=rel_has_activity),
        RelStep(rel_type='HAS_DECLARATIVE_STATEMENT', csv_name='rels_component_has_declarative_statement.csv',
                properties=['maturity_level'],
                rows=494, loadable=494, cypher=rel_has_declarative_statement),
        RelStep(rel_type='AT_MATURITY_LEVEL', csv_name='rels_declarative_statement_at_maturity_level.csv',
                properties=[],
                rows=494, loadable=494, cypher=rel_at_maturity_level),
        RelStep(rel_type='MAPS_TO_IT_HANDBOOK', csv_name='rels_declarative_statement_maps_to_it_handbook.csv',
                properties=['citation'],
                rows=118, loadable=118, cypher=rel_maps_to_it_handbook),
        RelStep(rel_type='HAS_ASSESSMENT_FACTOR', csv_name='rels_domain_has_assessment_factor.csv',
                properties=[],
                rows=15, loadable=15, cypher=rel_has_assessment_factor),
        RelStep(rel_type='HAS_PART', csv_name='rels_has_part.csv',
                properties=[],
                rows=2, loadable=2, cypher=rel_has_part),
        RelStep(rel_type='DEFINES_TERM', csv_name='rels_instrument_defines_term.csv',
                properties=[],
                rows=2, loadable=2, cypher=rel_defines_term),
        RelStep(rel_type='HAS_RESOURCE', csv_name='rels_instrument_has_resource.csv',
                properties=[],
                rows=4, loadable=4, cypher=rel_has_resource),
        RelStep(rel_type='HAS_DOMAIN', csv_name='rels_part_has_domain.csv',
                properties=[],
                rows=5, loadable=5, cypher=rel_has_domain),
        RelStep(rel_type='HAS_RISK_CATEGORY', csv_name='rels_part_has_risk_category.csv',
                properties=[],
                rows=5, loadable=5, cypher=rel_has_risk_category),
        RelStep(rel_type='AT_RISK_LEVEL', csv_name='rels_risk_statement_at_risk_level.csv',
                properties=[],
                rows=195, loadable=195, cypher=rel_at_risk_level),
    ],
    expected_nodes_total=873,
    expected_rels_total=1598,
)

if __name__ == "__main__":
    run(LOADER)
