"""Loader — India IT Act 2000.

Source folder : New sources/India IT Act 2000
Source document(s):
    KB 2/India/Information Technology Act 2000.pdf

Graph shape   : 16 node labels, 6 relationship types
Expected size : 1,255 nodes / 1,344 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/india_it_act_2000.py --dry-run   # validate, write nothing
    python App_new/india_it_act_2000.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'INDIA_IT_ACT_2000'
FOLDER = 'India IT Act 2000'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'INDIA_IT_ACT_2000'})
SET f.name = 'India IT Act 2000',
    f.jurisdiction = 'India',
    f.folder = 'India IT Act 2000',
    f.source_document = 'KB 2/India/Information Technology Act 2000.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'INDIA_IT_ACT_2000'})
MATCH (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000'})
WHERE NOT (:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Acronym.csv  (17 rows, key acronym_id)
node_acronym = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.acronym_id})
  SET
      n:Acronym,
      n.acronym_id = row.acronym_id,
      n.schedule_id = row.schedule_id,
      n.acronym = row.acronym,
      n.expansion = row.expansion,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Committee.csv  (1 rows, key committee_id)
node_committee = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.committee_id})
  SET
      n:Committee,
      n.committee_id = row.committee_id,
      n.name = row.name,
      n.constituted_under = row.constituted_under,
      n.notification_id = row.notification_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_CommitteeMember.csv  (21 rows, key committeemember_id)
node_committeemember = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.committeemember_id})
  SET
      n:CommitteeMember,
      n.committeemember_id = row.committeemember_id,
      n.committee_id = row.committee_id,
      n.position = row.position,
      n.designation = row.designation,
      n.role = row.role,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (25 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.definition = row.definition,
      n.source_provision_id = row.source_provision_id,
      n.instrument_part = row.instrument_part,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Form.csv  (4 rows, key form_id)
node_form = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.form_id})
  SET
      n:Form,
      n.form_id = row.form_id,
      n.schedule_id = row.schedule_id,
      n.ruleset_id = row.ruleset_id,
      n.title = row.title,
      n.see = row.see,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_FormField.csv  (79 rows, key formfield_id)
node_formfield = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.formfield_id})
  SET
      n:FormField,
      n.formfield_id = row.formfield_id,
      n.form_id = row.form_id,
      n.field_number = row.field_number,
      n.label = row.label,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_GlossaryTerm.csv  (213 rows, key glossaryterm_id)
node_glossaryterm = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.glossaryterm_id})
  SET
      n:GlossaryTerm,
      n.glossaryterm_id = row.glossaryterm_id,
      n.schedule_id = row.schedule_id,
      n.term = row.term,
      n.definition = row.definition,
      n.act_section_refs = row.act_section_refs,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Guideline.csv  (87 rows, key guideline_id)
node_guideline = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.guideline_id})
  SET
      n:Guideline,
      n.guideline_id = row.guideline_id,
      n.schedule_id = row.schedule_id,
      n.number = row.number,
      n.title = row.title,
      n.parent_guideline_id = row.parent_guideline_id,
      n.act_section_refs = row.act_section_refs,
      n.schedule_refs = row.schedule_refs,
      n.para_refs = row.para_refs,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_GuidelineProvision.csv  (456 rows, key guidelineprovision_id)
node_guidelineprovision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.guidelineprovision_id})
  SET
      n:GuidelineProvision,
      n.guidelineprovision_id = row.guidelineprovision_id,
      n.guideline_id = row.guideline_id,
      n.schedule_id = row.schedule_id,
      n.label = row.label,
      n.level = row.level,
      n.text = row.text,
      n.act_section_refs = row.act_section_refs,
      n.schedule_refs = row.schedule_refs,
      n.para_refs = row.para_refs,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Instrument.csv  (1 rows, key instrument_id)
node_instrument = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.instrument_id})
  SET
      n:Instrument,
      n.instrument_id = row.instrument_id,
      n.title = row.title,
      n.jurisdiction = row.jurisdiction,
      n.issuing_authority = row.issuing_authority,
      n.date = row.date,
      n.gazette = row.gazette,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Notification.csv  (4 rows, key notification_id)
node_notification = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.notification_id})
  SET
      n:Notification,
      n.notification_id = row.notification_id,
      n.number = row.number,
      n.text = row.text,
      n.enabling_power = row.enabling_power,
      n.date = row.date,
      n.issuing_authority = row.issuing_authority,
      n.file_number = row.file_number,
      n.act_section_refs = row.act_section_refs,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Provision.csv  (268 rows, key provision_id)
node_provision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.provision_id})
  SET
      n:Provision,
      n.provision_id = row.provision_id,
      n.rule_id = row.rule_id,
      n.ruleset_id = row.ruleset_id,
      n.label = row.label,
      n.level = row.level,
      n.text = row.text,
      n.act_section_refs = row.act_section_refs,
      n.rule_refs = row.rule_refs,
      n.schedule_refs = row.schedule_refs,
      n.para_refs = row.para_refs,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Rule.csv  (62 rows, key rule_id)
node_rule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.rule_id})
  SET
      n:Rule,
      n.rule_id = row.rule_id,
      n.ruleset_id = row.ruleset_id,
      n.rule_number = row.rule_number,
      n.title = row.title,
      n.chapeau = row.chapeau,
      n.act_section_refs = row.act_section_refs,
      n.rule_refs = row.rule_refs,
      n.schedule_refs = row.schedule_refs,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_RuleSet.csv  (2 rows, key ruleset_id)
node_ruleset = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.ruleset_id})
  SET
      n:RuleSet,
      n.ruleset_id = row.ruleset_id,
      n.title = row.title,
      n.made_under = row.made_under,
      n.notification_id = row.notification_id,
      n.commencement = row.commencement,
      n.rule_count = row.rule_count,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Schedule.csv  (5 rows, key schedule_id)
node_schedule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.schedule_id})
  SET
      n:Schedule,
      n.schedule_id = row.schedule_id,
      n.ruleset_id = row.ruleset_id,
      n.label = row.label,
      n.see_rule = row.see_rule,
      n.title = row.title,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Standard.csv  (10 rows, key standard_id)
node_standard = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.standard_id})
  SET
      n:Standard,
      n.standard_id = row.standard_id,
      n.product = row.product,
      n.standard = row.standard,
      n.rule_id = row.rule_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_contains.csv -> :CONTAINS  (1,197 rows)
rel_contains = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CONTAINS'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.target_id})
  MERGE (s)-[r:CONTAINS]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :CONSTITUTES  (1 rows)
rel_constitutes = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CONSTITUTES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.target_id})
  MERGE (s)-[r:CONSTITUTES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_defines.csv -> :DEFINES  (25 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_member.csv -> :HAS_MEMBER  (21 rows)
rel_has_member = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_MEMBER'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.target_id})
  MERGE (s)-[r:HAS_MEMBER]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_prescribes_standard.csv -> :PRESCRIBES_STANDARD  (10 rows)
rel_prescribes_standard = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'PRESCRIBES_STANDARD'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.target_id})
  MERGE (s)-[r:PRESCRIBES_STANDARD]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_references.csv -> :REFERENCES  (90 rows)
rel_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'INDIA_IT_ACT_2000', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES]->(t)
  SET r.ref_kind = row.ref_kind
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='India IT Act 2000',
    folder=FOLDER,
    jurisdiction='India',
    source_document='KB 2/India/Information Technology Act 2000.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Acronym', csv_name='nodes_Acronym.csv', id_column='acronym_id',
                 properties=['schedule_id', 'acronym', 'expansion', 'source_document'],
                 rows=17, loadable=17, cypher=node_acronym),
        NodeStep(label='Committee', csv_name='nodes_Committee.csv', id_column='committee_id',
                 properties=['name', 'constituted_under', 'notification_id', 'source_document'],
                 rows=1, loadable=1, cypher=node_committee),
        NodeStep(label='CommitteeMember', csv_name='nodes_CommitteeMember.csv', id_column='committeemember_id',
                 properties=['committee_id', 'position', 'designation', 'role', 'source_document'],
                 rows=21, loadable=21, cypher=node_committeemember),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'definition', 'source_provision_id', 'instrument_part', 'source_document'],
                 rows=25, loadable=25, cypher=node_definition),
        NodeStep(label='Form', csv_name='nodes_Form.csv', id_column='form_id',
                 properties=['schedule_id', 'ruleset_id', 'title', 'see', 'source_document'],
                 rows=4, loadable=4, cypher=node_form),
        NodeStep(label='FormField', csv_name='nodes_FormField.csv', id_column='formfield_id',
                 properties=['form_id', 'field_number', 'label', 'source_document'],
                 rows=79, loadable=79, cypher=node_formfield),
        NodeStep(label='GlossaryTerm', csv_name='nodes_GlossaryTerm.csv', id_column='glossaryterm_id',
                 properties=['schedule_id', 'term', 'definition', 'act_section_refs', 'source_document'],
                 rows=213, loadable=213, cypher=node_glossaryterm),
        NodeStep(label='Guideline', csv_name='nodes_Guideline.csv', id_column='guideline_id',
                 properties=['schedule_id', 'number', 'title', 'parent_guideline_id', 'act_section_refs', 'schedule_refs', 'para_refs', 'source_document'],
                 rows=87, loadable=87, cypher=node_guideline),
        NodeStep(label='GuidelineProvision', csv_name='nodes_GuidelineProvision.csv', id_column='guidelineprovision_id',
                 properties=['guideline_id', 'schedule_id', 'label', 'level', 'text', 'act_section_refs', 'schedule_refs', 'para_refs', 'source_document'],
                 rows=456, loadable=456, cypher=node_guidelineprovision),
        NodeStep(label='Instrument', csv_name='nodes_Instrument.csv', id_column='instrument_id',
                 properties=['title', 'jurisdiction', 'issuing_authority', 'date', 'gazette', 'source_document'],
                 rows=1, loadable=1, cypher=node_instrument),
        NodeStep(label='Notification', csv_name='nodes_Notification.csv', id_column='notification_id',
                 properties=['number', 'text', 'enabling_power', 'date', 'issuing_authority', 'file_number', 'act_section_refs', 'source_document'],
                 rows=4, loadable=4, cypher=node_notification),
        NodeStep(label='Provision', csv_name='nodes_Provision.csv', id_column='provision_id',
                 properties=['rule_id', 'ruleset_id', 'label', 'level', 'text', 'act_section_refs', 'rule_refs', 'schedule_refs', 'para_refs', 'source_document'],
                 rows=268, loadable=268, cypher=node_provision),
        NodeStep(label='Rule', csv_name='nodes_Rule.csv', id_column='rule_id',
                 properties=['ruleset_id', 'rule_number', 'title', 'chapeau', 'act_section_refs', 'rule_refs', 'schedule_refs', 'source_document'],
                 rows=62, loadable=62, cypher=node_rule),
        NodeStep(label='RuleSet', csv_name='nodes_RuleSet.csv', id_column='ruleset_id',
                 properties=['title', 'made_under', 'notification_id', 'commencement', 'rule_count', 'source_document'],
                 rows=2, loadable=2, cypher=node_ruleset),
        NodeStep(label='Schedule', csv_name='nodes_Schedule.csv', id_column='schedule_id',
                 properties=['ruleset_id', 'label', 'see_rule', 'title', 'source_document'],
                 rows=5, loadable=5, cypher=node_schedule),
        NodeStep(label='Standard', csv_name='nodes_Standard.csv', id_column='standard_id',
                 properties=['product', 'standard', 'rule_id', 'source_document'],
                 rows=10, loadable=10, cypher=node_standard),
    ],
    rel_steps=[
        RelStep(rel_type='CONTAINS', csv_name='rels_contains.csv',
                properties=[],
                rows=1197, loadable=1197, cypher=rel_contains),
        RelStep(rel_type='CONSTITUTES', csv_name='rels_contains.csv',
                properties=[],
                rows=1, loadable=1, cypher=rel_constitutes),
        RelStep(rel_type='DEFINES', csv_name='rels_defines.csv',
                properties=[],
                rows=25, loadable=25, cypher=rel_defines),
        RelStep(rel_type='HAS_MEMBER', csv_name='rels_has_member.csv',
                properties=[],
                rows=21, loadable=21, cypher=rel_has_member),
        RelStep(rel_type='PRESCRIBES_STANDARD', csv_name='rels_prescribes_standard.csv',
                properties=[],
                rows=10, loadable=10, cypher=rel_prescribes_standard),
        RelStep(rel_type='REFERENCES', csv_name='rels_references.csv',
                properties=['ref_kind'],
                rows=90, loadable=90, cypher=rel_references),
    ],
    expected_nodes_total=1255,
    expected_rels_total=1344,
)

if __name__ == "__main__":
    run(LOADER)
