"""Loader — MAS TRM Guidelines.

Source folder : New sources/MAS TRM Guidelines
Source document(s):
    MAS Technology Risk Management Guidelines, January 2021 (KB 2/Singapore/MAS Technology Risk Management Guidelines.pdf)

Graph shape   : 6 node labels, 7 relationship types
Expected size : 433 nodes / 435 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/mas_trm_guidelines.py --dry-run   # validate, write nothing
    python App_new/mas_trm_guidelines.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'MAS_TRM_GUIDELINES'
FOLDER = 'MAS TRM Guidelines'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'MAS_TRM_GUIDELINES'})
SET f.name = 'MAS TRM Guidelines',
    f.jurisdiction = 'Singapore',
    f.folder = 'MAS TRM Guidelines',
    f.source_document = 'MAS Technology Risk Management Guidelines, January 2021 (KB 2/Singapore/MAS Technology Risk Management Guidelines.pdf)',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'MAS_TRM_GUIDELINES'})
MATCH (n:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES'})
WHERE NOT (:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Clause.csv  (255 rows, key clause_id)
node_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.clause_id})
  SET
      n:Clause,
      n.clause_id = row.clause_id,
      n.number = row.number,
      n.section_id = row.section_id,
      n.subsection_id = row.subsection_id,
      n.text = row.text,
      n.page = row.page,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Document.csv  (1 rows, key document_id)
node_document = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.document_id})
  SET
      n:Document,
      n.document_id = row.document_id,
      n.title = row.title,
      n.issuer = row.issuer,
      n.jurisdiction = row.jurisdiction,
      n.issue_date = row.issue_date,
      n.instrument_type = row.instrument_type,
      n.status_statement = row.status_statement,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Footnote.csv  (42 rows, key footnote_id)
node_footnote = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.footnote_id})
  SET
      n:Footnote,
      n.footnote_id = row.footnote_id,
      n.number = row.number,
      n.page = row.page,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Section.csv  (18 rows, key section_id)
node_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.section_id})
  SET
      n:Section,
      n.section_id = row.section_id,
      n.number = row.number,
      n.title = row.title,
      n.kind = row.kind,
      n.page = row.page,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_SubItem.csv  (56 rows, key subitem_id)
node_subitem = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.subitem_id})
  SET
      n:SubItem,
      n.subitem_id = row.subitem_id,
      n.clause_id = row.clause_id,
      n.label = row.label,
      n.ordinal = row.ordinal,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Subsection.csv  (61 rows, key subsection_id)
node_subsection = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.subsection_id})
  SET
      n:Subsection,
      n.subsection_id = row.subsection_id,
      n.number = row.number,
      n.title = row.title,
      n.section_id = row.section_id,
      n.page = row.page,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_clause_has_subitem.csv -> :HAS_SUBITEM  (56 rows)
rel_has_subitem = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBITEM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBITEM]->(t)
  SET r.ordinal = row.ordinal
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_clause_references_section.csv -> :REFERENCES  (3 rows)
rel_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_document_has_section.csv -> :HAS_SECTION  (18 rows)
rel_has_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.target_id})
  MERGE (s)-[r:HAS_SECTION]->(t)
  SET r.ordinal = row.ordinal
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_footnote_annotates_clause.csv -> :ANNOTATES  (42 rows)
rel_annotates = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'ANNOTATES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.target_id})
  MERGE (s)-[r:ANNOTATES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_section_has_clause.csv -> :HAS_CLAUSE  (11 rows)
rel_has_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.target_id})
  MERGE (s)-[r:HAS_CLAUSE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_section_has_subsection.csv -> :HAS_SUBSECTION  (61 rows)
rel_has_subsection = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBSECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBSECTION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_subsection_has_clause.csv -> :HAS_CLAUSE  (244 rows)
rel_has_clause_2 = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MAS_TRM_GUIDELINES', node_id: row.target_id})
  MERGE (s)-[r:HAS_CLAUSE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='MAS TRM Guidelines',
    folder=FOLDER,
    jurisdiction='Singapore',
    source_document='MAS Technology Risk Management Guidelines, January 2021 (KB 2/Singapore/MAS Technology Risk Management Guidelines.pdf)',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Clause', csv_name='nodes_Clause.csv', id_column='clause_id',
                 properties=['number', 'section_id', 'subsection_id', 'text', 'page', 'source_document'],
                 rows=255, loadable=255, cypher=node_clause),
        NodeStep(label='Document', csv_name='nodes_Document.csv', id_column='document_id',
                 properties=['title', 'issuer', 'jurisdiction', 'issue_date', 'instrument_type', 'status_statement', 'source_document'],
                 rows=1, loadable=1, cypher=node_document),
        NodeStep(label='Footnote', csv_name='nodes_Footnote.csv', id_column='footnote_id',
                 properties=['number', 'page', 'text', 'source_document'],
                 rows=42, loadable=42, cypher=node_footnote),
        NodeStep(label='Section', csv_name='nodes_Section.csv', id_column='section_id',
                 properties=['number', 'title', 'kind', 'page', 'source_document'],
                 rows=18, loadable=18, cypher=node_section),
        NodeStep(label='SubItem', csv_name='nodes_SubItem.csv', id_column='subitem_id',
                 properties=['clause_id', 'label', 'ordinal', 'text', 'source_document'],
                 rows=56, loadable=56, cypher=node_subitem),
        NodeStep(label='Subsection', csv_name='nodes_Subsection.csv', id_column='subsection_id',
                 properties=['number', 'title', 'section_id', 'page', 'source_document'],
                 rows=61, loadable=61, cypher=node_subsection),
    ],
    rel_steps=[
        RelStep(rel_type='HAS_SUBITEM', csv_name='rels_clause_has_subitem.csv',
                properties=['ordinal'],
                rows=56, loadable=56, cypher=rel_has_subitem),
        RelStep(rel_type='REFERENCES', csv_name='rels_clause_references_section.csv',
                properties=[],
                rows=3, loadable=3, cypher=rel_references),
        RelStep(rel_type='HAS_SECTION', csv_name='rels_document_has_section.csv',
                properties=['ordinal'],
                rows=18, loadable=18, cypher=rel_has_section),
        RelStep(rel_type='ANNOTATES', csv_name='rels_footnote_annotates_clause.csv',
                properties=[],
                rows=42, loadable=42, cypher=rel_annotates),
        RelStep(rel_type='HAS_CLAUSE', csv_name='rels_section_has_clause.csv',
                properties=[],
                rows=11, loadable=11, cypher=rel_has_clause),
        RelStep(rel_type='HAS_SUBSECTION', csv_name='rels_section_has_subsection.csv',
                properties=[],
                rows=61, loadable=61, cypher=rel_has_subsection),
        RelStep(rel_type='HAS_CLAUSE', csv_name='rels_subsection_has_clause.csv',
                properties=[],
                rows=244, loadable=244, cypher=rel_has_clause_2),
    ],
    expected_nodes_total=433,
    expected_rels_total=435,
)

if __name__ == "__main__":
    run(LOADER)
