"""Loader — Massachusetts Fraud and Abuse Compliance.

Source folder : New sources/Massachusetts Fraud and Abuse Compliance
Source document(s):
    Massachusetts Medical Society, Fraud and Abuse Compliance: Implementing a Compliance Plan (2003) (KB 2/USA/MAfraud.PDF)

Graph shape   : 22 node labels, 28 relationship types
Expected size : 312 nodes / 351 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/massachusetts_fraud_and_abuse_compliance.py --dry-run   # validate, write nothing
    python App_new/massachusetts_fraud_and_abuse_compliance.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE'
FOLDER = 'Massachusetts Fraud and Abuse Compliance'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE'})
SET f.name = 'Massachusetts Fraud and Abuse Compliance',
    f.jurisdiction = 'United States',
    f.folder = 'Massachusetts Fraud and Abuse Compliance',
    f.source_document = 'Massachusetts Medical Society, Fraud and Abuse Compliance: Implementing a Compliance Plan (2003) (KB 2/USA/MAfraud.PDF)',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE'})
MATCH (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE'})
WHERE NOT (:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Chapter.csv  (6 rows, key chapter_id)
node_chapter = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.chapter_id})
  SET
      n:Chapter,
      n.chapter_id = row.chapter_id,
      n.chapter_label = row.chapter_label,
      n.title = row.title,
      n.page = row.page,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ComplianceStep.csv  (7 rows, key compliancestep_id)
node_compliancestep = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.compliancestep_id})
  SET
      n:ComplianceStep,
      n.compliancestep_id = row.compliancestep_id,
      n.step_number = row.step_number,
      n.title = row.title,
      n.summary = row.summary,
      n.detail = row.detail,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (14 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.definition = row.definition,
      n.defined_in = row.defined_in,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_DesignatedHealthService.csv  (10 rows, key designatedhealthservice_id)
node_designatedhealthservice = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.designatedhealthservice_id})
  SET
      n:DesignatedHealthService,
      n.designatedhealthservice_id = row.designatedhealthservice_id,
      n.item_number = row.item_number,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Document.csv  (1 rows, key document_id)
node_document = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.document_id})
  SET
      n:Document,
      n.document_id = row.document_id,
      n.title = row.title,
      n.publisher = row.publisher,
      n.year = row.year,
      n.disclaimer = row.disclaimer,
      n.preparation_note = row.preparation_note,
      n.copyright = row.copyright,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Example.csv  (45 rows, key example_id)
node_example = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.example_id})
  SET
      n:Example,
      n.example_id = row.example_id,
      n.statute_id = row.statute_id,
      n.example_type = row.example_type,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ExclusionGround.csv  (18 rows, key exclusionground_id)
node_exclusionground = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.exclusionground_id})
  SET
      n:ExclusionGround,
      n.exclusionground_id = row.exclusionground_id,
      n.exclusion_type = row.exclusion_type,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ExternalReference.csv  (10 rows, key externalreference_id)
node_externalreference = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.externalreference_id})
  SET
      n:ExternalReference,
      n.externalreference_id = row.externalreference_id,
      n.title = row.title,
      n.issuer = row.issuer,
      n.date = row.date,
      n.url = row.url,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Form.csv  (5 rows, key form_id)
node_form = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.form_id})
  SET
      n:Form,
      n.form_id = row.form_id,
      n.title = row.title,
      n.section_id = row.section_id,
      n.note = row.note,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_FormClause.csv  (21 rows, key formclause_id)
node_formclause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.formclause_id})
  SET
      n:FormClause,
      n.formclause_id = row.formclause_id,
      n.form_id = row.form_id,
      n.clause_number = row.clause_number,
      n.heading = row.heading,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_FraudAlert.csv  (7 rows, key fraudalert_id)
node_fraudalert = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.fraudalert_id})
  SET
      n:FraudAlert,
      n.fraudalert_id = row.fraudalert_id,
      n.title = row.title,
      n.date_issued = row.date_issued,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_GuidanceItem.csv  (27 rows, key guidanceitem_id)
node_guidanceitem = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.guidanceitem_id})
  SET
      n:GuidanceItem,
      n.guidanceitem_id = row.guidanceitem_id,
      n.parent_riskarea_id = row.parent_riskarea_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_OfficerResponsibility.csv  (14 rows, key officerresponsibility_id)
node_officerresponsibility = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.officerresponsibility_id})
  SET
      n:OfficerResponsibility,
      n.officerresponsibility_id = row.officerresponsibility_id,
      n.title = row.title,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Penalty.csv  (6 rows, key penalty_id)
node_penalty = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.penalty_id})
  SET
      n:Penalty,
      n.penalty_id = row.penalty_id,
      n.statute_id = row.statute_id,
      n.title = row.title,
      n.text = row.text,
      n.amount = row.amount,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ProgramComponent.csv  (9 rows, key programcomponent_id)
node_programcomponent = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.programcomponent_id})
  SET
      n:ProgramComponent,
      n.programcomponent_id = row.programcomponent_id,
      n.name = row.name,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_RiskArea.csv  (31 rows, key riskarea_id)
node_riskarea = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.riskarea_id})
  SET
      n:RiskArea,
      n.riskarea_id = row.riskarea_id,
      n.name = row.name,
      n.listing = row.listing,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_SafeHarbor.csv  (8 rows, key safeharbor_id)
node_safeharbor = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.safeharbor_id})
  SET
      n:SafeHarbor,
      n.safeharbor_id = row.safeharbor_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Section.csv  (19 rows, key section_id)
node_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.section_id})
  SET
      n:Section,
      n.section_id = row.section_id,
      n.chapter_id = row.chapter_id,
      n.title = row.title,
      n.page = row.page,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Statement.csv  (13 rows, key statement_id)
node_statement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.statement_id})
  SET
      n:Statement,
      n.statement_id = row.statement_id,
      n.chapter_id = row.chapter_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Statute.csv  (19 rows, key statute_id)
node_statute = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.statute_id})
  SET
      n:Statute,
      n.statute_id = row.statute_id,
      n.short_name = row.short_name,
      n.citation = row.citation,
      n.jurisdiction = row.jurisdiction,
      n.category = row.category,
      n.section_id = row.section_id,
      n.description = row.description,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_StatuteClause.csv  (13 rows, key statuteclause_id)
node_statuteclause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.statuteclause_id})
  SET
      n:StatuteClause,
      n.statuteclause_id = row.statuteclause_id,
      n.statute_id = row.statute_id,
      n.heading = row.heading,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_WorkPlanItem.csv  (9 rows, key workplanitem_id)
node_workplanitem = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.workplanitem_id})
  SET
      n:WorkPlanItem,
      n.workplanitem_id = row.workplanitem_id,
      n.title = row.title,
      n.text = row.text,
      n.fiscal_year = row.fiscal_year,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_contains.csv -> :HAS_CHAPTER  (6 rows)
rel_has_chapter = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CHAPTER'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_CHAPTER]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :HAS_SECTION  (19 rows)
rel_has_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_SECTION]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :HAS_STATEMENT  (13 rows)
rel_has_statement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_STATEMENT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_STATEMENT]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_contains.csv -> :HAS_FORM  (5 rows)
rel_has_form = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_FORM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_FORM]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_definitions.csv -> :DEFINES  (14 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_examples.csv -> :HAS_EXAMPLE  (45 rows)
rel_has_example = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_EXAMPLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_EXAMPLE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_forms.csv -> :HAS_CLAUSE  (21 rows)
rel_has_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_CLAUSE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_forms.csv -> :LISTS_COMPONENT  (9 rows)
rel_lists_component = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'LISTS_COMPONENT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:LISTS_COMPONENT]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_forms.csv -> :HAS_RESPONSIBILITY  (14 rows)
rel_has_responsibility = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_RESPONSIBILITY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_RESPONSIBILITY]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_forms.csv -> :CORRESPONDS_TO_STEP  (7 rows)
rel_corresponds_to_step = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CORRESPONDS_TO_STEP'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:CORRESPONDS_TO_STEP]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_forms.csv -> :REVIEWS_AGAINST  (2 rows)
rel_reviews_against = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REVIEWS_AGAINST'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:REVIEWS_AGAINST]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_forms.csv -> :USES_REFERENCE  (3 rows)
rel_uses_reference = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'USES_REFERENCE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:USES_REFERENCE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_step.csv -> :HAS_STEP  (7 rows)
rel_has_step = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_STEP'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_STEP]->(t)
  SET r.step_number = row.step_number,
      r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_oig_initiatives.csv -> :LISTS_FRAUD_ALERT  (7 rows)
rel_lists_fraud_alert = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'LISTS_FRAUD_ALERT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:LISTS_FRAUD_ALERT]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_oig_initiatives.csv -> :IMPLICATES_STATUTE  (5 rows)
rel_implicates_statute = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'IMPLICATES_STATUTE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:IMPLICATES_STATUTE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_oig_initiatives.csv -> :LISTS_WORK_PLAN_ITEM  (9 rows)
rel_lists_work_plan_item = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'LISTS_WORK_PLAN_ITEM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:LISTS_WORK_PLAN_ITEM]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_penalties.csv -> :HAS_PENALTY  (6 rows)
rel_has_penalty = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PENALTY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_PENALTY]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_penalties.csv -> :HAS_GROUND  (18 rows)
rel_has_ground = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_GROUND'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_GROUND]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_references.csv -> :CITES  (20 rows)
rel_cites = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CITES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:CITES]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_risk_areas.csv -> :IDENTIFIES_RISK_AREA  (31 rows)
rel_identifies_risk_area = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'IDENTIFIES_RISK_AREA'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:IDENTIFIES_RISK_AREA]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_risk_areas.csv -> :HAS_GUIDANCE_ITEM  (27 rows)
rel_has_guidance_item = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_GUIDANCE_ITEM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_GUIDANCE_ITEM]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_risk_areas.csv -> :ADDRESSES_RISK_AREA  (4 rows)
rel_addresses_risk_area = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'ADDRESSES_RISK_AREA'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:ADDRESSES_RISK_AREA]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_risk_areas.csv -> :RELATES_TO_STATUTE  (7 rows)
rel_relates_to_statute = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'RELATES_TO_STATUTE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:RELATES_TO_STATUTE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_scope.csv -> :HAS_SAFE_HARBOR  (8 rows)
rel_has_safe_harbor = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SAFE_HARBOR'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_SAFE_HARBOR]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_scope.csv -> :COVERS_DESIGNATED_SERVICE  (10 rows)
rel_covers_designated_service = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'COVERS_DESIGNATED_SERVICE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:COVERS_DESIGNATED_SERVICE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_statute_structure.csv -> :DESCRIBES_STATUTE  (19 rows)
rel_describes_statute = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DESCRIBES_STATUTE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:DESCRIBES_STATUTE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_statute_structure.csv -> :HAS_CLAUSE  (13 rows)
rel_has_clause_2 = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_CLAUSE]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_statute_structure.csv -> :HAS_PART  (2 rows)
rel_has_part = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PART'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MASSACHUSETTS_FRAUD_AND_ABUSE_COMPLIANCE', node_id: row.target_id})
  MERGE (s)-[r:HAS_PART]->(t)
  SET r.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='Massachusetts Fraud and Abuse Compliance',
    folder=FOLDER,
    jurisdiction='United States',
    source_document='Massachusetts Medical Society, Fraud and Abuse Compliance: Implementing a Compliance Plan (2003) (KB 2/USA/MAfraud.PDF)',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Chapter', csv_name='nodes_Chapter.csv', id_column='chapter_id',
                 properties=['chapter_label', 'title', 'page', 'source_document'],
                 rows=6, loadable=6, cypher=node_chapter),
        NodeStep(label='ComplianceStep', csv_name='nodes_ComplianceStep.csv', id_column='compliancestep_id',
                 properties=['step_number', 'title', 'summary', 'detail', 'source_document'],
                 rows=7, loadable=7, cypher=node_compliancestep),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'definition', 'defined_in', 'source_document'],
                 rows=14, loadable=14, cypher=node_definition),
        NodeStep(label='DesignatedHealthService', csv_name='nodes_DesignatedHealthService.csv', id_column='designatedhealthservice_id',
                 properties=['item_number', 'text', 'source_document'],
                 rows=10, loadable=10, cypher=node_designatedhealthservice),
        NodeStep(label='Document', csv_name='nodes_Document.csv', id_column='document_id',
                 properties=['title', 'publisher', 'year', 'disclaimer', 'preparation_note', 'copyright', 'source_document'],
                 rows=1, loadable=1, cypher=node_document),
        NodeStep(label='Example', csv_name='nodes_Example.csv', id_column='example_id',
                 properties=['statute_id', 'example_type', 'text', 'source_document'],
                 rows=45, loadable=45, cypher=node_example),
        NodeStep(label='ExclusionGround', csv_name='nodes_ExclusionGround.csv', id_column='exclusionground_id',
                 properties=['exclusion_type', 'text', 'source_document'],
                 rows=18, loadable=18, cypher=node_exclusionground),
        NodeStep(label='ExternalReference', csv_name='nodes_ExternalReference.csv', id_column='externalreference_id',
                 properties=['title', 'issuer', 'date', 'url', 'text', 'source_document'],
                 rows=10, loadable=10, cypher=node_externalreference),
        NodeStep(label='Form', csv_name='nodes_Form.csv', id_column='form_id',
                 properties=['title', 'section_id', 'note', 'source_document'],
                 rows=5, loadable=5, cypher=node_form),
        NodeStep(label='FormClause', csv_name='nodes_FormClause.csv', id_column='formclause_id',
                 properties=['form_id', 'clause_number', 'heading', 'text', 'source_document'],
                 rows=21, loadable=21, cypher=node_formclause),
        NodeStep(label='FraudAlert', csv_name='nodes_FraudAlert.csv', id_column='fraudalert_id',
                 properties=['title', 'date_issued', 'text', 'source_document'],
                 rows=7, loadable=7, cypher=node_fraudalert),
        NodeStep(label='GuidanceItem', csv_name='nodes_GuidanceItem.csv', id_column='guidanceitem_id',
                 properties=['parent_riskarea_id', 'text', 'source_document'],
                 rows=27, loadable=27, cypher=node_guidanceitem),
        NodeStep(label='OfficerResponsibility', csv_name='nodes_OfficerResponsibility.csv', id_column='officerresponsibility_id',
                 properties=['title', 'text', 'source_document'],
                 rows=14, loadable=14, cypher=node_officerresponsibility),
        NodeStep(label='Penalty', csv_name='nodes_Penalty.csv', id_column='penalty_id',
                 properties=['statute_id', 'title', 'text', 'amount', 'source_document'],
                 rows=6, loadable=6, cypher=node_penalty),
        NodeStep(label='ProgramComponent', csv_name='nodes_ProgramComponent.csv', id_column='programcomponent_id',
                 properties=['name', 'text', 'source_document'],
                 rows=9, loadable=9, cypher=node_programcomponent),
        NodeStep(label='RiskArea', csv_name='nodes_RiskArea.csv', id_column='riskarea_id',
                 properties=['name', 'listing', 'text', 'source_document'],
                 rows=31, loadable=31, cypher=node_riskarea),
        NodeStep(label='SafeHarbor', csv_name='nodes_SafeHarbor.csv', id_column='safeharbor_id',
                 properties=['text', 'source_document'],
                 rows=8, loadable=8, cypher=node_safeharbor),
        NodeStep(label='Section', csv_name='nodes_Section.csv', id_column='section_id',
                 properties=['chapter_id', 'title', 'page', 'source_document'],
                 rows=19, loadable=19, cypher=node_section),
        NodeStep(label='Statement', csv_name='nodes_Statement.csv', id_column='statement_id',
                 properties=['chapter_id', 'text', 'source_document'],
                 rows=13, loadable=13, cypher=node_statement),
        NodeStep(label='Statute', csv_name='nodes_Statute.csv', id_column='statute_id',
                 properties=['short_name', 'citation', 'jurisdiction', 'category', 'section_id', 'description', 'source_document'],
                 rows=19, loadable=19, cypher=node_statute),
        NodeStep(label='StatuteClause', csv_name='nodes_StatuteClause.csv', id_column='statuteclause_id',
                 properties=['statute_id', 'heading', 'text', 'source_document'],
                 rows=13, loadable=13, cypher=node_statuteclause),
        NodeStep(label='WorkPlanItem', csv_name='nodes_WorkPlanItem.csv', id_column='workplanitem_id',
                 properties=['title', 'text', 'fiscal_year', 'source_document'],
                 rows=9, loadable=9, cypher=node_workplanitem),
    ],
    rel_steps=[
        RelStep(rel_type='HAS_CHAPTER', csv_name='rels_contains.csv',
                properties=['source_document'],
                rows=6, loadable=6, cypher=rel_has_chapter),
        RelStep(rel_type='HAS_SECTION', csv_name='rels_contains.csv',
                properties=['source_document'],
                rows=19, loadable=19, cypher=rel_has_section),
        RelStep(rel_type='HAS_STATEMENT', csv_name='rels_contains.csv',
                properties=['source_document'],
                rows=13, loadable=13, cypher=rel_has_statement),
        RelStep(rel_type='HAS_FORM', csv_name='rels_contains.csv',
                properties=['source_document'],
                rows=5, loadable=5, cypher=rel_has_form),
        RelStep(rel_type='DEFINES', csv_name='rels_definitions.csv',
                properties=['source_document'],
                rows=14, loadable=14, cypher=rel_defines),
        RelStep(rel_type='HAS_EXAMPLE', csv_name='rels_examples.csv',
                properties=['source_document'],
                rows=45, loadable=45, cypher=rel_has_example),
        RelStep(rel_type='HAS_CLAUSE', csv_name='rels_forms.csv',
                properties=['source_document'],
                rows=21, loadable=21, cypher=rel_has_clause),
        RelStep(rel_type='LISTS_COMPONENT', csv_name='rels_forms.csv',
                properties=['source_document'],
                rows=9, loadable=9, cypher=rel_lists_component),
        RelStep(rel_type='HAS_RESPONSIBILITY', csv_name='rels_forms.csv',
                properties=['source_document'],
                rows=14, loadable=14, cypher=rel_has_responsibility),
        RelStep(rel_type='CORRESPONDS_TO_STEP', csv_name='rels_forms.csv',
                properties=['source_document'],
                rows=7, loadable=7, cypher=rel_corresponds_to_step),
        RelStep(rel_type='REVIEWS_AGAINST', csv_name='rels_forms.csv',
                properties=['source_document'],
                rows=2, loadable=2, cypher=rel_reviews_against),
        RelStep(rel_type='USES_REFERENCE', csv_name='rels_forms.csv',
                properties=['source_document'],
                rows=3, loadable=3, cypher=rel_uses_reference),
        RelStep(rel_type='HAS_STEP', csv_name='rels_has_step.csv',
                properties=['step_number', 'source_document'],
                rows=7, loadable=7, cypher=rel_has_step),
        RelStep(rel_type='LISTS_FRAUD_ALERT', csv_name='rels_oig_initiatives.csv',
                properties=['source_document'],
                rows=7, loadable=7, cypher=rel_lists_fraud_alert),
        RelStep(rel_type='IMPLICATES_STATUTE', csv_name='rels_oig_initiatives.csv',
                properties=['source_document'],
                rows=5, loadable=5, cypher=rel_implicates_statute),
        RelStep(rel_type='LISTS_WORK_PLAN_ITEM', csv_name='rels_oig_initiatives.csv',
                properties=['source_document'],
                rows=9, loadable=9, cypher=rel_lists_work_plan_item),
        RelStep(rel_type='HAS_PENALTY', csv_name='rels_penalties.csv',
                properties=['source_document'],
                rows=6, loadable=6, cypher=rel_has_penalty),
        RelStep(rel_type='HAS_GROUND', csv_name='rels_penalties.csv',
                properties=['source_document'],
                rows=18, loadable=18, cypher=rel_has_ground),
        RelStep(rel_type='CITES', csv_name='rels_references.csv',
                properties=['source_document'],
                rows=20, loadable=20, cypher=rel_cites),
        RelStep(rel_type='IDENTIFIES_RISK_AREA', csv_name='rels_risk_areas.csv',
                properties=['source_document'],
                rows=31, loadable=31, cypher=rel_identifies_risk_area),
        RelStep(rel_type='HAS_GUIDANCE_ITEM', csv_name='rels_risk_areas.csv',
                properties=['source_document'],
                rows=27, loadable=27, cypher=rel_has_guidance_item),
        RelStep(rel_type='ADDRESSES_RISK_AREA', csv_name='rels_risk_areas.csv',
                properties=['source_document'],
                rows=4, loadable=4, cypher=rel_addresses_risk_area),
        RelStep(rel_type='RELATES_TO_STATUTE', csv_name='rels_risk_areas.csv',
                properties=['source_document'],
                rows=7, loadable=7, cypher=rel_relates_to_statute),
        RelStep(rel_type='HAS_SAFE_HARBOR', csv_name='rels_scope.csv',
                properties=['source_document'],
                rows=8, loadable=8, cypher=rel_has_safe_harbor),
        RelStep(rel_type='COVERS_DESIGNATED_SERVICE', csv_name='rels_scope.csv',
                properties=['source_document'],
                rows=10, loadable=10, cypher=rel_covers_designated_service),
        RelStep(rel_type='DESCRIBES_STATUTE', csv_name='rels_statute_structure.csv',
                properties=['source_document'],
                rows=19, loadable=19, cypher=rel_describes_statute),
        RelStep(rel_type='HAS_CLAUSE', csv_name='rels_statute_structure.csv',
                properties=['source_document'],
                rows=13, loadable=13, cypher=rel_has_clause_2),
        RelStep(rel_type='HAS_PART', csv_name='rels_statute_structure.csv',
                properties=['source_document'],
                rows=2, loadable=2, cypher=rel_has_part),
    ],
    expected_nodes_total=312,
    expected_rels_total=351,
)

if __name__ == "__main__":
    run(LOADER)
