"""Loader — MITRE ATTACK.

Source folder : New sources/MITRE ATTACK
Source document(s):
    KB 2/USA/Mitre Att&ck.pdf

Graph shape   : 3 node labels, 2 relationship types
Expected size : 221 nodes / 220 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/mitre_attack.py --dry-run   # validate, write nothing
    python App_new/mitre_attack.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'MITRE_ATTACK'
FOLDER = 'MITRE ATTACK'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'MITRE_ATTACK'})
SET f.name = 'MITRE ATTACK',
    f.jurisdiction = 'United States',
    f.folder = 'MITRE ATTACK',
    f.source_document = 'KB 2/USA/Mitre Att&ck.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'MITRE_ATTACK'})
MATCH (n:NewSourceNode {framework_id: 'MITRE_ATTACK'})
WHERE NOT (:NewSourceNode {framework_id: 'MITRE_ATTACK'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Framework.csv  (1 rows, key framework_id)
node_framework = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MITRE_ATTACK', node_id: row.framework_id})
  SET
      n:Framework,
      n.csv_framework_id = row.framework_id,
      n.name = row.name,
      n.version = row.version,
      n.currency = row.currency,
      n.publisher = row.publisher,
      n.url = row.url,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Tactic.csv  (14 rows, key tactic_id)
node_tactic = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MITRE_ATTACK', node_id: row.tactic_id})
  SET
      n:Tactic,
      n.tactic_id = row.tactic_id,
      n.name = row.name,
      n.column_order = row.column_order,
      n.stated_technique_count_text = row.stated_technique_count_text,
      n.stated_technique_count = row.stated_technique_count,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Technique.csv  (206 rows, key technique_id)
node_technique = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'MITRE_ATTACK', node_id: row.technique_id})
  SET
      n:Technique,
      n.technique_id = row.technique_id,
      n.name_as_ocr = row.name_as_ocr,
      n.tactic_id = row.tactic_id,
      n.column_sequence = row.column_sequence,
      n.ocr_confidence = row.ocr_confidence,
      n.ocr_source_lines = row.ocr_source_lines,
      n.ocr_note = row.ocr_note,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_HAS_TACTIC.csv -> :HAS_TACTIC  (14 rows)
rel_has_tactic = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_TACTIC'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MITRE_ATTACK', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MITRE_ATTACK', node_id: row.target_id})
  MERGE (s)-[r:HAS_TACTIC]->(t)
  SET r.column_order = row.column_order
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_TECHNIQUE.csv -> :HAS_TECHNIQUE  (206 rows)
rel_has_technique = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_TECHNIQUE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'MITRE_ATTACK', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'MITRE_ATTACK', node_id: row.target_id})
  MERGE (s)-[r:HAS_TECHNIQUE]->(t)
  SET r.ocr_confidence = row.ocr_confidence
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='MITRE ATTACK',
    folder=FOLDER,
    jurisdiction='United States',
    source_document='KB 2/USA/Mitre Att&ck.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Framework', csv_name='nodes_Framework.csv', id_column='framework_id',
                 properties=['name', 'version', 'currency', 'publisher', 'url', 'source_document'],
                 rows=1, loadable=1, cypher=node_framework),
        NodeStep(label='Tactic', csv_name='nodes_Tactic.csv', id_column='tactic_id',
                 properties=['name', 'column_order', 'stated_technique_count_text', 'stated_technique_count', 'source_document'],
                 rows=14, loadable=14, cypher=node_tactic),
        NodeStep(label='Technique', csv_name='nodes_Technique.csv', id_column='technique_id',
                 properties=['name_as_ocr', 'tactic_id', 'column_sequence', 'ocr_confidence', 'ocr_source_lines', 'ocr_note', 'source_document'],
                 rows=206, loadable=206, cypher=node_technique),
    ],
    rel_steps=[
        RelStep(rel_type='HAS_TACTIC', csv_name='rels_HAS_TACTIC.csv',
                properties=['column_order'],
                rows=14, loadable=14, cypher=rel_has_tactic),
        RelStep(rel_type='HAS_TECHNIQUE', csv_name='rels_HAS_TECHNIQUE.csv',
                properties=['ocr_confidence'],
                rows=206, loadable=206, cypher=rel_has_technique),
    ],
    expected_nodes_total=221,
    expected_rels_total=220,
)

if __name__ == "__main__":
    run(LOADER)
