"""Loader — Nigeria Data Protection Act 2023.

Source folder : New sources/Nigeria Data Protection Act 2023
Source document(s):
    Nigeria Data Protection Act (NDP Act) 2023 General Application and Implementation Directive (GAID) 2024, ref. NDPC/NDP ACT-GAID/001/2024 (KB 2/Africa/Nigeria-Data-Protection-Act(NDP ACT)2023(GAID)2024.pdf)
    Nigeria Data Protection Act, 2023 (Act No. 37), Federal Republic of Nigeria Official Gazette No. 119, Vol. 110, 1 July 2023 (KB 2/Africa/Nigeria_Data_Protection_Act_2023.pdf)

Graph shape   : 20 node labels, 22 relationship types
Expected size : 1,405 nodes / 1,518 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/nigeria_data_protection_act_2023.py --dry-run   # validate, write nothing
    python App_new/nigeria_data_protection_act_2023.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'NIGERIA_DATA_PROTECTION_ACT_2023'
FOLDER = 'Nigeria Data Protection Act 2023'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023'})
SET f.name = 'Nigeria Data Protection Act 2023',
    f.jurisdiction = 'Nigeria',
    f.folder = 'Nigeria Data Protection Act 2023',
    f.source_document = 'Nigeria Data Protection Act (NDP Act) 2023 General Application and Implementation Directive (GAID) 2024, ref. NDPC/NDP ACT-GAID/001/2024 (KB 2/Africa/Nigeria-Data-Protection-Act(NDP ACT)2023(GAID)2024.pdf) | Nigeria Data Protection Act, 2023 (Act No. 37), Federal Republic of Nigeria Official Gazette No. 119, Vol. 110, 1 July 2023 (KB 2/Africa/Nigeria_Data_Protection_Act_2023.pdf)',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023'})
MATCH (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023'})
WHERE NOT (:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_AbbreviatedTerm.csv  (28 rows, key abbreviatedterm_id)
node_abbreviatedterm = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.abbreviatedterm_id})
  SET
      n:AbbreviatedTerm,
      n.abbreviatedterm_id = row.abbreviatedterm_id,
      n.abbreviation = row.abbreviation,
      n.expanded_form = row.expanded_form,
      n.directive_id = row.directive_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Act.csv  (1 rows, key act_id)
node_act = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.act_id})
  SET
      n:Act,
      n.act_id = row.act_id,
      n.short_title = row.short_title,
      n.act_number = row.act_number,
      n.long_title = row.long_title,
      n.enacting_formula = row.enacting_formula,
      n.commencement = row.commencement,
      n.gazette = row.gazette,
      n.assented_by = row.assented_by,
      n.explanatory_memorandum = row.explanatory_memorandum,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Article.csv  (53 rows, key article_id)
node_article = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.article_id})
  SET
      n:Article,
      n.article_id = row.article_id,
      n.article_number = row.article_number,
      n.title = row.title,
      n.text = row.text,
      n.directive_id = row.directive_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ArticleItem.csv  (334 rows, key articleitem_id)
node_articleitem = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.articleitem_id})
  SET
      n:ArticleItem,
      n.articleitem_id = row.articleitem_id,
      n.item_label = row.item_label,
      n.parent_id = row.parent_id,
      n.parent_type = row.parent_type,
      n.article_number = row.article_number,
      n.reference = row.reference,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ArticleSubItem.csv  (50 rows, key articlesubitem_id)
node_articlesubitem = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.articlesubitem_id})
  SET
      n:ArticleSubItem,
      n.articlesubitem_id = row.articlesubitem_id,
      n.subitem_label = row.subitem_label,
      n.articleitem_id = row.articleitem_id,
      n.article_number = row.article_number,
      n.reference = row.reference,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Deadline.csv  (25 rows, key deadline_id)
node_deadline = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.deadline_id})
  SET
      n:Deadline,
      n.deadline_id = row.deadline_id,
      n.provision_id = row.provision_id,
      n.period = row.period,
      n.obligation = row.obligation,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (24 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.definition = row.definition,
      n.defined_in = row.defined_in,
      n.instrument = row.instrument,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Directive.csv  (1 rows, key directive_id)
node_directive = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.directive_id})
  SET
      n:Directive,
      n.directive_id = row.directive_id,
      n.title = row.title,
      n.reference_number = row.reference_number,
      n.issuing_body = row.issuing_body,
      n.authority = row.authority,
      n.implements_instrument = row.implements_instrument,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_DirectiveDefinition.csv  (18 rows, key directivedefinition_id)
node_directivedefinition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.directivedefinition_id})
  SET
      n:DirectiveDefinition,
      n.directivedefinition_id = row.directivedefinition_id,
      n.term = row.term,
      n.definition = row.definition,
      n.defined_in = row.defined_in,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_DirectiveSchedule.csv  (4 rows, key directiveschedule_id)
node_directiveschedule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.directiveschedule_id})
  SET
      n:DirectiveSchedule,
      n.directiveschedule_id = row.directiveschedule_id,
      n.label = row.label,
      n.title = row.title,
      n.directive_id = row.directive_id,
      n.text_present_in_source = row.text_present_in_source,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Paragraph.csv  (300 rows, key paragraph_id)
node_paragraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.paragraph_id})
  SET
      n:Paragraph,
      n.paragraph_id = row.paragraph_id,
      n.paragraph_letter = row.paragraph_letter,
      n.parent_id = row.parent_id,
      n.parent_type = row.parent_type,
      n.section_number = row.section_number,
      n.reference = row.reference,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Part.csv  (12 rows, key part_id)
node_part = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.part_id})
  SET
      n:Part,
      n.part_id = row.part_id,
      n.part_number = row.part_number,
      n.title = row.title,
      n.sections_covered = row.sections_covered,
      n.instrument = row.instrument,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Penalty.csv  (9 rows, key penalty_id)
node_penalty = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.penalty_id})
  SET
      n:Penalty,
      n.penalty_id = row.penalty_id,
      n.provision_id = row.provision_id,
      n.type = row.type,
      n.monetary_amount = row.monetary_amount,
      n.custodial_sanction = row.custodial_sanction,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Preamble.csv  (6 rows, key preamble_id)
node_preamble = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.preamble_id})
  SET
      n:Preamble,
      n.preamble_id = row.preamble_id,
      n.text = row.text,
      n.directive_id = row.directive_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Schedule.csv  (1 rows, key schedule_id)
node_schedule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.schedule_id})
  SET
      n:Schedule,
      n.schedule_id = row.schedule_id,
      n.title = row.title,
      n.enabling_provision = row.enabling_provision,
      n.instrument = row.instrument,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ScheduleParagraph.csv  (18 rows, key scheduleparagraph_id)
node_scheduleparagraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.scheduleparagraph_id})
  SET
      n:ScheduleParagraph,
      n.scheduleparagraph_id = row.scheduleparagraph_id,
      n.paragraph_number = row.paragraph_number,
      n.heading = row.heading,
      n.schedule_id = row.schedule_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Section.csv  (66 rows, key section_id)
node_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.section_id})
  SET
      n:Section,
      n.section_id = row.section_id,
      n.section_number = row.section_number,
      n.marginal_note = row.marginal_note,
      n.part_id = row.part_id,
      n.text = row.text,
      n.instrument = row.instrument,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_SubArticle.csv  (250 rows, key subarticle_id)
node_subarticle = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.subarticle_id})
  SET
      n:SubArticle,
      n.subarticle_id = row.subarticle_id,
      n.subarticle_number = row.subarticle_number,
      n.article_id = row.article_id,
      n.article_number = row.article_number,
      n.reference = row.reference,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Subparagraph.csv  (44 rows, key subparagraph_id)
node_subparagraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.subparagraph_id})
  SET
      n:Subparagraph,
      n.subparagraph_id = row.subparagraph_id,
      n.subparagraph_number = row.subparagraph_number,
      n.paragraph_id = row.paragraph_id,
      n.section_number = row.section_number,
      n.reference = row.reference,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Subsection.csv  (161 rows, key subsection_id)
node_subsection = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.subsection_id})
  SET
      n:Subsection,
      n.subsection_id = row.subsection_id,
      n.subsection_number = row.subsection_number,
      n.section_id = row.section_id,
      n.section_number = row.section_number,
      n.reference = row.reference,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_article_has_item.csv -> :HAS_ITEM  (334 rows)
rel_has_item = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ITEM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_ITEM]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_article_has_subarticle.csv -> :HAS_SUB_ARTICLE  (250 rows)
rel_has_sub_article = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUB_ARTICLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUB_ARTICLE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_cross_reference.csv -> :CROSS_REFERENCES  (61 rows)
rel_cross_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CROSS_REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:CROSS_REFERENCES]->(t)
  SET r.quoted_text = row.quoted_text
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_deadline_stated_in.csv -> :STATED_IN  (25 rows)
rel_stated_in = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'STATED_IN'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:STATED_IN]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_defines.csv -> :DEFINES  (24 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_directive_defines.csv -> :DEFINES  (18 rows)
rel_defines_2 = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_directive_has_article.csv -> :HAS_ARTICLE  (53 rows)
rel_has_article = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ARTICLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_ARTICLE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_directive_has_preamble.csv -> :HAS_PREAMBLE_RECITAL  (6 rows)
rel_has_preamble_recital = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PREAMBLE_RECITAL'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_PREAMBLE_RECITAL]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_directive_has_schedule.csv -> :HAS_SCHEDULE  (4 rows)
rel_has_schedule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SCHEDULE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_SCHEDULE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_directive_implements.csv -> :IMPLEMENTS  (49 rows)
rel_implements = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'IMPLEMENTS'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:IMPLEMENTS]->(t)
  SET r.quoted_text = row.quoted_text
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_directive_implements.csv -> :REFERS_TO_SCHEDULE  (4 rows)
rel_refers_to_schedule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERS_TO_SCHEDULE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:REFERS_TO_SCHEDULE]->(t)
  SET r.quoted_text = row.quoted_text
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_directive_uses_abbreviation.csv -> :USES_ABBREVIATION  (28 rows)
rel_uses_abbreviation = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'USES_ABBREVIATION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:USES_ABBREVIATION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_paragraph.csv -> :HAS_PARAGRAPH  (300 rows)
rel_has_paragraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PARAGRAPH'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_PARAGRAPH]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_part.csv -> :HAS_PART  (12 rows)
rel_has_part = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PART'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_PART]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_schedule.csv -> :HAS_SCHEDULE  (1 rows)
rel_has_schedule_2 = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SCHEDULE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_SCHEDULE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_schedule.csv -> :APPLIES_SCHEDULE  (1 rows)
rel_applies_schedule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'APPLIES_SCHEDULE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:APPLIES_SCHEDULE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_section.csv -> :HAS_SECTION  (66 rows)
rel_has_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_SECTION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_subparagraph.csv -> :HAS_SUBPARAGRAPH  (44 rows)
rel_has_subparagraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBPARAGRAPH'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBPARAGRAPH]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_subsection.csv -> :HAS_SUBSECTION  (161 rows)
rel_has_subsection = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBSECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBSECTION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_item_has_subitem.csv -> :HAS_SUB_ITEM  (50 rows)
rel_has_sub_item = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUB_ITEM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUB_ITEM]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_penalty_prescribed_by.csv -> :PRESCRIBED_BY  (9 rows)
rel_prescribed_by = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'PRESCRIBED_BY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:PRESCRIBED_BY]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_schedule_has_paragraph.csv -> :HAS_SCHEDULE_PARAGRAPH  (18 rows)
rel_has_schedule_paragraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SCHEDULE_PARAGRAPH'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIGERIA_DATA_PROTECTION_ACT_2023', node_id: row.target_id})
  MERGE (s)-[r:HAS_SCHEDULE_PARAGRAPH]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='Nigeria Data Protection Act 2023',
    folder=FOLDER,
    jurisdiction='Nigeria',
    source_document='Nigeria Data Protection Act (NDP Act) 2023 General Application and Implementation Directive (GAID) 2024, ref. NDPC/NDP ACT-GAID/001/2024 (KB 2/Africa/Nigeria-Data-Protection-Act(NDP ACT)2023(GAID)2024.pdf) | Nigeria Data Protection Act, 2023 (Act No. 37), Federal Republic of Nigeria Official Gazette No. 119, Vol. 110, 1 July 2023 (KB 2/Africa/Nigeria_Data_Protection_Act_2023.pdf)',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='AbbreviatedTerm', csv_name='nodes_AbbreviatedTerm.csv', id_column='abbreviatedterm_id',
                 properties=['abbreviation', 'expanded_form', 'directive_id', 'source_document'],
                 rows=28, loadable=28, cypher=node_abbreviatedterm),
        NodeStep(label='Act', csv_name='nodes_Act.csv', id_column='act_id',
                 properties=['short_title', 'act_number', 'long_title', 'enacting_formula', 'commencement', 'gazette', 'assented_by', 'explanatory_memorandum', 'source_document'],
                 rows=1, loadable=1, cypher=node_act),
        NodeStep(label='Article', csv_name='nodes_Article.csv', id_column='article_id',
                 properties=['article_number', 'title', 'text', 'directive_id', 'source_document'],
                 rows=53, loadable=53, cypher=node_article),
        NodeStep(label='ArticleItem', csv_name='nodes_ArticleItem.csv', id_column='articleitem_id',
                 properties=['item_label', 'parent_id', 'parent_type', 'article_number', 'reference', 'text', 'source_document'],
                 rows=334, loadable=334, cypher=node_articleitem),
        NodeStep(label='ArticleSubItem', csv_name='nodes_ArticleSubItem.csv', id_column='articlesubitem_id',
                 properties=['subitem_label', 'articleitem_id', 'article_number', 'reference', 'text', 'source_document'],
                 rows=50, loadable=50, cypher=node_articlesubitem),
        NodeStep(label='Deadline', csv_name='nodes_Deadline.csv', id_column='deadline_id',
                 properties=['provision_id', 'period', 'obligation', 'source_document'],
                 rows=25, loadable=25, cypher=node_deadline),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'definition', 'defined_in', 'instrument', 'source_document'],
                 rows=24, loadable=24, cypher=node_definition),
        NodeStep(label='Directive', csv_name='nodes_Directive.csv', id_column='directive_id',
                 properties=['title', 'reference_number', 'issuing_body', 'authority', 'implements_instrument', 'source_document'],
                 rows=1, loadable=1, cypher=node_directive),
        NodeStep(label='DirectiveDefinition', csv_name='nodes_DirectiveDefinition.csv', id_column='directivedefinition_id',
                 properties=['term', 'definition', 'defined_in', 'source_document'],
                 rows=18, loadable=18, cypher=node_directivedefinition),
        NodeStep(label='DirectiveSchedule', csv_name='nodes_DirectiveSchedule.csv', id_column='directiveschedule_id',
                 properties=['label', 'title', 'directive_id', 'text_present_in_source', 'source_document'],
                 rows=4, loadable=4, cypher=node_directiveschedule),
        NodeStep(label='Paragraph', csv_name='nodes_Paragraph.csv', id_column='paragraph_id',
                 properties=['paragraph_letter', 'parent_id', 'parent_type', 'section_number', 'reference', 'text', 'source_document'],
                 rows=300, loadable=300, cypher=node_paragraph),
        NodeStep(label='Part', csv_name='nodes_Part.csv', id_column='part_id',
                 properties=['part_number', 'title', 'sections_covered', 'instrument', 'source_document'],
                 rows=12, loadable=12, cypher=node_part),
        NodeStep(label='Penalty', csv_name='nodes_Penalty.csv', id_column='penalty_id',
                 properties=['provision_id', 'type', 'monetary_amount', 'custodial_sanction', 'text', 'source_document'],
                 rows=9, loadable=9, cypher=node_penalty),
        NodeStep(label='Preamble', csv_name='nodes_Preamble.csv', id_column='preamble_id',
                 properties=['text', 'directive_id', 'source_document'],
                 rows=6, loadable=6, cypher=node_preamble),
        NodeStep(label='Schedule', csv_name='nodes_Schedule.csv', id_column='schedule_id',
                 properties=['title', 'enabling_provision', 'instrument', 'source_document'],
                 rows=1, loadable=1, cypher=node_schedule),
        NodeStep(label='ScheduleParagraph', csv_name='nodes_ScheduleParagraph.csv', id_column='scheduleparagraph_id',
                 properties=['paragraph_number', 'heading', 'schedule_id', 'text', 'source_document'],
                 rows=18, loadable=18, cypher=node_scheduleparagraph),
        NodeStep(label='Section', csv_name='nodes_Section.csv', id_column='section_id',
                 properties=['section_number', 'marginal_note', 'part_id', 'text', 'instrument', 'source_document'],
                 rows=66, loadable=66, cypher=node_section),
        NodeStep(label='SubArticle', csv_name='nodes_SubArticle.csv', id_column='subarticle_id',
                 properties=['subarticle_number', 'article_id', 'article_number', 'reference', 'text', 'source_document'],
                 rows=250, loadable=250, cypher=node_subarticle),
        NodeStep(label='Subparagraph', csv_name='nodes_Subparagraph.csv', id_column='subparagraph_id',
                 properties=['subparagraph_number', 'paragraph_id', 'section_number', 'reference', 'text', 'source_document'],
                 rows=44, loadable=44, cypher=node_subparagraph),
        NodeStep(label='Subsection', csv_name='nodes_Subsection.csv', id_column='subsection_id',
                 properties=['subsection_number', 'section_id', 'section_number', 'reference', 'text', 'source_document'],
                 rows=161, loadable=161, cypher=node_subsection),
    ],
    rel_steps=[
        RelStep(rel_type='HAS_ITEM', csv_name='rels_article_has_item.csv',
                properties=[],
                rows=334, loadable=334, cypher=rel_has_item),
        RelStep(rel_type='HAS_SUB_ARTICLE', csv_name='rels_article_has_subarticle.csv',
                properties=[],
                rows=250, loadable=250, cypher=rel_has_sub_article),
        RelStep(rel_type='CROSS_REFERENCES', csv_name='rels_cross_reference.csv',
                properties=['quoted_text'],
                rows=61, loadable=61, cypher=rel_cross_references),
        RelStep(rel_type='STATED_IN', csv_name='rels_deadline_stated_in.csv',
                properties=[],
                rows=25, loadable=25, cypher=rel_stated_in),
        RelStep(rel_type='DEFINES', csv_name='rels_defines.csv',
                properties=[],
                rows=24, loadable=24, cypher=rel_defines),
        RelStep(rel_type='DEFINES', csv_name='rels_directive_defines.csv',
                properties=[],
                rows=18, loadable=18, cypher=rel_defines_2),
        RelStep(rel_type='HAS_ARTICLE', csv_name='rels_directive_has_article.csv',
                properties=[],
                rows=53, loadable=53, cypher=rel_has_article),
        RelStep(rel_type='HAS_PREAMBLE_RECITAL', csv_name='rels_directive_has_preamble.csv',
                properties=[],
                rows=6, loadable=6, cypher=rel_has_preamble_recital),
        RelStep(rel_type='HAS_SCHEDULE', csv_name='rels_directive_has_schedule.csv',
                properties=[],
                rows=4, loadable=4, cypher=rel_has_schedule),
        RelStep(rel_type='IMPLEMENTS', csv_name='rels_directive_implements.csv',
                properties=['quoted_text'],
                rows=49, loadable=49, cypher=rel_implements),
        RelStep(rel_type='REFERS_TO_SCHEDULE', csv_name='rels_directive_implements.csv',
                properties=['quoted_text'],
                rows=4, loadable=4, cypher=rel_refers_to_schedule),
        RelStep(rel_type='USES_ABBREVIATION', csv_name='rels_directive_uses_abbreviation.csv',
                properties=[],
                rows=28, loadable=28, cypher=rel_uses_abbreviation),
        RelStep(rel_type='HAS_PARAGRAPH', csv_name='rels_has_paragraph.csv',
                properties=[],
                rows=300, loadable=300, cypher=rel_has_paragraph),
        RelStep(rel_type='HAS_PART', csv_name='rels_has_part.csv',
                properties=[],
                rows=12, loadable=12, cypher=rel_has_part),
        RelStep(rel_type='HAS_SCHEDULE', csv_name='rels_has_schedule.csv',
                properties=[],
                rows=1, loadable=1, cypher=rel_has_schedule_2),
        RelStep(rel_type='APPLIES_SCHEDULE', csv_name='rels_has_schedule.csv',
                properties=[],
                rows=1, loadable=1, cypher=rel_applies_schedule),
        RelStep(rel_type='HAS_SECTION', csv_name='rels_has_section.csv',
                properties=[],
                rows=66, loadable=66, cypher=rel_has_section),
        RelStep(rel_type='HAS_SUBPARAGRAPH', csv_name='rels_has_subparagraph.csv',
                properties=[],
                rows=44, loadable=44, cypher=rel_has_subparagraph),
        RelStep(rel_type='HAS_SUBSECTION', csv_name='rels_has_subsection.csv',
                properties=[],
                rows=161, loadable=161, cypher=rel_has_subsection),
        RelStep(rel_type='HAS_SUB_ITEM', csv_name='rels_item_has_subitem.csv',
                properties=[],
                rows=50, loadable=50, cypher=rel_has_sub_item),
        RelStep(rel_type='PRESCRIBED_BY', csv_name='rels_penalty_prescribed_by.csv',
                properties=[],
                rows=9, loadable=9, cypher=rel_prescribed_by),
        RelStep(rel_type='HAS_SCHEDULE_PARAGRAPH', csv_name='rels_schedule_has_paragraph.csv',
                properties=[],
                rows=18, loadable=18, cypher=rel_has_schedule_paragraph),
    ],
    expected_nodes_total=1405,
    expected_rels_total=1518,
)

if __name__ == "__main__":
    run(LOADER)
