"""Loader — NIST SP 800-171r3.

Source folder : New sources/NIST SP 800-171r3
Source document(s):
    NIST SP 800-171r3, Protecting Controlled Unclassified Information in Nonfederal Systems and Organizations (May 2024) — KB 2/USA/NIST.SP.800-171r3.pdf

Graph shape   : 14 node labels, 20 relationship types
Expected size : 1,406 nodes / 2,520 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/nist_sp_800_171r3.py --dry-run   # validate, write nothing
    python App_new/nist_sp_800_171r3.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'NIST_SP_800_171R3'
FOLDER = 'NIST SP 800-171r3'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'NIST_SP_800_171R3'})
SET f.name = 'NIST SP 800-171r3',
    f.jurisdiction = 'United States',
    f.folder = 'NIST SP 800-171r3',
    f.source_document = 'NIST SP 800-171r3, Protecting Controlled Unclassified Information in Nonfederal Systems and Organizations (May 2024) — KB 2/USA/NIST.SP.800-171r3.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'NIST_SP_800_171R3'})
MATCH (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3'})
WHERE NOT (:NewSourceNode {framework_id: 'NIST_SP_800_171R3'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Acronym.csv  (33 rows, key acronym_id)
node_acronym = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.acronym_id})
  SET
      n:Acronym,
      n.acronym_id = row.acronym_id,
      n.acronym = row.acronym,
      n.expansion = row.expansion,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Appendix.csv  (5 rows, key appendix_id)
node_appendix = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.appendix_id})
  SET
      n:Appendix,
      n.appendix_id = row.appendix_id,
      n.letter = row.letter,
      n.title = row.title,
      n.introduction = row.introduction,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ChangeLogItem.csv  (16 rows, key changelogitem_id)
node_changelogitem = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.changelogitem_id})
  SET
      n:ChangeLogItem,
      n.changelogitem_id = row.changelogitem_id,
      n.sequence = row.sequence,
      n.change = row.change,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Clause.csv  (252 rows, key clause_id)
node_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.clause_id})
  SET
      n:Clause,
      n.clause_id = row.clause_id,
      n.securityrequirement_id = row.securityrequirement_id,
      n.parent_id = row.parent_id,
      n.label = row.label,
      n.level = row.level,
      n.text = row.text,
      n.contains_odp = row.contains_odp,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Family.csv  (17 rows, key family_id)
node_family = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.family_id})
  SET
      n:Family,
      n.family_id = row.family_id,
      n.section_number = row.section_number,
      n.name = row.name,
      n.abbreviation = row.abbreviation,
      n.requirement_prefix = row.requirement_prefix,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_GlossaryTerm.csv  (86 rows, key glossaryterm_id)
node_glossaryterm = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.glossaryterm_id})
  SET
      n:GlossaryTerm,
      n.glossaryterm_id = row.glossaryterm_id,
      n.term = row.term,
      n.definition = row.definition,
      n.source_reference = row.source_reference,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ODP.csv  (80 rows, key odp_id)
node_odp = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.odp_id})
  SET
      n:ODP,
      n.odp_id = row.odp_id,
      n.securityrequirement_id = row.securityrequirement_id,
      n.clause_reference = row.clause_reference,
      n.parameter_text = row.parameter_text,
      n.operation = row.operation,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Publication.csv  (1 rows, key publication_id)
node_publication = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.publication_id})
  SET
      n:Publication,
      n.publication_id = row.publication_id,
      n.identifier = row.identifier,
      n.series = row.series,
      n.title = row.title,
      n.authors = row.authors,
      n.organization = row.organization,
      n.publication_date = row.publication_date,
      n.approved_by_editorial_review_board = row.approved_by_editorial_review_board,
      n.supersedes = row.supersedes,
      n.doi = row.doi,
      n.requirements_derived_from = row.requirements_derived_from,
      n.baseline_source = row.baseline_source,
      n.companion_publication = row.companion_publication,
      n.keywords = row.keywords,
      n.how_to_cite = row.how_to_cite,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Reference.csv  (84 rows, key reference_id)
node_reference = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.reference_id})
  SET
      n:Reference,
      n.reference_id = row.reference_id,
      n.number = row.number,
      n.citation = row.citation,
      n.source_document = row.source_document,
      n.url = row.url
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Section.csv  (7 rows, key section_id)
node_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.section_id})
  SET
      n:Section,
      n.section_id = row.section_id,
      n.number = row.number,
      n.title = row.title,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_SecurityRequirement.csv  (130 rows, key securityrequirement_id)
node_securityrequirement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.securityrequirement_id})
  SET
      n:SecurityRequirement,
      n.securityrequirement_id = row.securityrequirement_id,
      n.family_id = row.family_id,
      n.title = row.title,
      n.status = row.status,
      n.statement = row.statement,
      n.withdrawal_disposition = row.withdrawal_disposition,
      n.discussion = row.discussion,
      n.source_controls = row.source_controls,
      n.supporting_publications = row.supporting_publications,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_SourceControl.csv  (345 rows, key sourcecontrol_id)
node_sourcecontrol = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.sourcecontrol_id})
  SET
      n:SourceControl,
      n.sourcecontrol_id = row.sourcecontrol_id,
      n.control_identifier = row.control_identifier,
      n.control_name = row.control_name,
      n.sp800_53_family = row.sp800_53_family,
      n.catalog = row.catalog,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_TailoringCriteria.csv  (5 rows, key tailoringcriteria_id)
node_tailoringcriteria = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.tailoringcriteria_id})
  SET
      n:TailoringCriteria,
      n.tailoringcriteria_id = row.tailoringcriteria_id,
      n.symbol = row.symbol,
      n.criteria = row.criteria,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_TailoringDecision.csv  (345 rows, key tailoringdecision_id)
node_tailoringdecision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.tailoringdecision_id})
  SET
      n:TailoringDecision,
      n.tailoringdecision_id = row.tailoringdecision_id,
      n.table = row.table,
      n.control_identifier = row.control_identifier,
      n.control_name = row.control_name,
      n.tailoring_criteria = row.tailoring_criteria,
      n.security_requirement = row.security_requirement,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_ASSIGNED_CRITERIA.csv -> :ASSIGNED_CRITERIA  (345 rows)
rel_assigned_criteria = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'ASSIGNED_CRITERIA'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:ASSIGNED_CRITERIA]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_CITES.csv -> :CITES  (84 rows)
rel_cites = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CITES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:CITES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_CROSS_REFERENCES.csv -> :CROSS_REFERENCES  (73 rows)
rel_cross_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CROSS_REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:CROSS_REFERENCES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DEFINES_ACRONYM.csv -> :DEFINES_ACRONYM  (33 rows)
rel_defines_acronym = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES_ACRONYM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:DEFINES_ACRONYM]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DEFINES_TERM.csv -> :DEFINES_TERM  (86 rows)
rel_defines_term = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES_TERM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:DEFINES_TERM]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DERIVED_FROM_CONTROL.csv -> :DERIVED_FROM_CONTROL  (157 rows)
rel_derived_from_control = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DERIVED_FROM_CONTROL'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:DERIVED_FROM_CONTROL]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_APPENDIX.csv -> :HAS_APPENDIX  (5 rows)
rel_has_appendix = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_APPENDIX'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:HAS_APPENDIX]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_CHANGE.csv -> :HAS_CHANGE  (16 rows)
rel_has_change = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CHANGE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:HAS_CHANGE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_CLAUSE.csv -> :HAS_CLAUSE  (252 rows)
rel_has_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:HAS_CLAUSE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_FAMILY.csv -> :HAS_FAMILY  (17 rows)
rel_has_family = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_FAMILY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:HAS_FAMILY]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_ODP.csv -> :HAS_ODP  (80 rows)
rel_has_odp = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ODP'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:HAS_ODP]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_REQUIREMENT.csv -> :HAS_REQUIREMENT  (130 rows)
rel_has_requirement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_REQUIREMENT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:HAS_REQUIREMENT]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_SECTION.csv -> :HAS_SECTION  (7 rows)
rel_has_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:HAS_SECTION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_TAILORING_DECISION.csv -> :HAS_TAILORING_DECISION  (345 rows)
rel_has_tailoring_decision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_TAILORING_DECISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:HAS_TAILORING_DECISION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_LISTS_ODP.csv -> :LISTS_ODP  (80 rows)
rel_lists_odp = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'LISTS_ODP'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:LISTS_ODP]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_MAPS_TO_REQUIREMENT.csv -> :MAPS_TO_REQUIREMENT  (156 rows)
rel_maps_to_requirement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'MAPS_TO_REQUIREMENT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:MAPS_TO_REQUIREMENT]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_ODP_APPLIES_TO_CLAUSE.csv -> :ODP_APPLIES_TO_CLAUSE  (72 rows)
rel_odp_applies_to_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'ODP_APPLIES_TO_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:ODP_APPLIES_TO_CLAUSE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_SUPPORTED_BY_PUBLICATION.csv -> :SUPPORTED_BY_PUBLICATION  (199 rows)
rel_supported_by_publication = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'SUPPORTED_BY_PUBLICATION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:SUPPORTED_BY_PUBLICATION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_TAILORS_CONTROL.csv -> :TAILORS_CONTROL  (345 rows)
rel_tailors_control = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'TAILORS_CONTROL'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:TAILORS_CONTROL]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_TERM_SOURCE.csv -> :TERM_SOURCE  (38 rows)
rel_term_source = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'TERM_SOURCE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'NIST_SP_800_171R3', node_id: row.target_id})
  MERGE (s)-[r:TERM_SOURCE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='NIST SP 800-171r3',
    folder=FOLDER,
    jurisdiction='United States',
    source_document='NIST SP 800-171r3, Protecting Controlled Unclassified Information in Nonfederal Systems and Organizations (May 2024) — KB 2/USA/NIST.SP.800-171r3.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Acronym', csv_name='nodes_Acronym.csv', id_column='acronym_id',
                 properties=['acronym', 'expansion', 'source_document'],
                 rows=33, loadable=33, cypher=node_acronym),
        NodeStep(label='Appendix', csv_name='nodes_Appendix.csv', id_column='appendix_id',
                 properties=['letter', 'title', 'introduction', 'source_document'],
                 rows=5, loadable=5, cypher=node_appendix),
        NodeStep(label='ChangeLogItem', csv_name='nodes_ChangeLogItem.csv', id_column='changelogitem_id',
                 properties=['sequence', 'change', 'source_document'],
                 rows=16, loadable=16, cypher=node_changelogitem),
        NodeStep(label='Clause', csv_name='nodes_Clause.csv', id_column='clause_id',
                 properties=['securityrequirement_id', 'parent_id', 'label', 'level', 'text', 'contains_odp', 'source_document'],
                 rows=252, loadable=252, cypher=node_clause),
        NodeStep(label='Family', csv_name='nodes_Family.csv', id_column='family_id',
                 properties=['section_number', 'name', 'abbreviation', 'requirement_prefix', 'source_document'],
                 rows=17, loadable=17, cypher=node_family),
        NodeStep(label='GlossaryTerm', csv_name='nodes_GlossaryTerm.csv', id_column='glossaryterm_id',
                 properties=['term', 'definition', 'source_reference', 'source_document'],
                 rows=86, loadable=86, cypher=node_glossaryterm),
        NodeStep(label='ODP', csv_name='nodes_ODP.csv', id_column='odp_id',
                 properties=['securityrequirement_id', 'clause_reference', 'parameter_text', 'operation', 'source_document'],
                 rows=80, loadable=80, cypher=node_odp),
        NodeStep(label='Publication', csv_name='nodes_Publication.csv', id_column='publication_id',
                 properties=['identifier', 'series', 'title', 'authors', 'organization', 'publication_date', 'approved_by_editorial_review_board', 'supersedes', 'doi', 'requirements_derived_from', 'baseline_source', 'companion_publication', 'keywords', 'how_to_cite', 'source_document'],
                 rows=1, loadable=1, cypher=node_publication),
        NodeStep(label='Reference', csv_name='nodes_Reference.csv', id_column='reference_id',
                 properties=['number', 'citation', 'source_document', 'url'],
                 rows=84, loadable=84, cypher=node_reference),
        NodeStep(label='Section', csv_name='nodes_Section.csv', id_column='section_id',
                 properties=['number', 'title', 'text', 'source_document'],
                 rows=7, loadable=7, cypher=node_section),
        NodeStep(label='SecurityRequirement', csv_name='nodes_SecurityRequirement.csv', id_column='securityrequirement_id',
                 properties=['family_id', 'title', 'status', 'statement', 'withdrawal_disposition', 'discussion', 'source_controls', 'supporting_publications', 'source_document'],
                 rows=130, loadable=130, cypher=node_securityrequirement),
        NodeStep(label='SourceControl', csv_name='nodes_SourceControl.csv', id_column='sourcecontrol_id',
                 properties=['control_identifier', 'control_name', 'sp800_53_family', 'catalog', 'source_document'],
                 rows=345, loadable=345, cypher=node_sourcecontrol),
        NodeStep(label='TailoringCriteria', csv_name='nodes_TailoringCriteria.csv', id_column='tailoringcriteria_id',
                 properties=['symbol', 'criteria', 'source_document'],
                 rows=5, loadable=5, cypher=node_tailoringcriteria),
        NodeStep(label='TailoringDecision', csv_name='nodes_TailoringDecision.csv', id_column='tailoringdecision_id',
                 properties=['table', 'control_identifier', 'control_name', 'tailoring_criteria', 'security_requirement', 'source_document'],
                 rows=345, loadable=345, cypher=node_tailoringdecision),
    ],
    rel_steps=[
        RelStep(rel_type='ASSIGNED_CRITERIA', csv_name='rels_ASSIGNED_CRITERIA.csv',
                properties=[],
                rows=345, loadable=345, cypher=rel_assigned_criteria),
        RelStep(rel_type='CITES', csv_name='rels_CITES.csv',
                properties=[],
                rows=84, loadable=84, cypher=rel_cites),
        RelStep(rel_type='CROSS_REFERENCES', csv_name='rels_CROSS_REFERENCES.csv',
                properties=[],
                rows=73, loadable=73, cypher=rel_cross_references),
        RelStep(rel_type='DEFINES_ACRONYM', csv_name='rels_DEFINES_ACRONYM.csv',
                properties=[],
                rows=33, loadable=33, cypher=rel_defines_acronym),
        RelStep(rel_type='DEFINES_TERM', csv_name='rels_DEFINES_TERM.csv',
                properties=[],
                rows=86, loadable=86, cypher=rel_defines_term),
        RelStep(rel_type='DERIVED_FROM_CONTROL', csv_name='rels_DERIVED_FROM_CONTROL.csv',
                properties=[],
                rows=157, loadable=157, cypher=rel_derived_from_control),
        RelStep(rel_type='HAS_APPENDIX', csv_name='rels_HAS_APPENDIX.csv',
                properties=[],
                rows=5, loadable=5, cypher=rel_has_appendix),
        RelStep(rel_type='HAS_CHANGE', csv_name='rels_HAS_CHANGE.csv',
                properties=[],
                rows=16, loadable=16, cypher=rel_has_change),
        RelStep(rel_type='HAS_CLAUSE', csv_name='rels_HAS_CLAUSE.csv',
                properties=[],
                rows=252, loadable=252, cypher=rel_has_clause),
        RelStep(rel_type='HAS_FAMILY', csv_name='rels_HAS_FAMILY.csv',
                properties=[],
                rows=17, loadable=17, cypher=rel_has_family),
        RelStep(rel_type='HAS_ODP', csv_name='rels_HAS_ODP.csv',
                properties=[],
                rows=80, loadable=80, cypher=rel_has_odp),
        RelStep(rel_type='HAS_REQUIREMENT', csv_name='rels_HAS_REQUIREMENT.csv',
                properties=[],
                rows=130, loadable=130, cypher=rel_has_requirement),
        RelStep(rel_type='HAS_SECTION', csv_name='rels_HAS_SECTION.csv',
                properties=[],
                rows=7, loadable=7, cypher=rel_has_section),
        RelStep(rel_type='HAS_TAILORING_DECISION', csv_name='rels_HAS_TAILORING_DECISION.csv',
                properties=[],
                rows=345, loadable=345, cypher=rel_has_tailoring_decision),
        RelStep(rel_type='LISTS_ODP', csv_name='rels_LISTS_ODP.csv',
                properties=[],
                rows=80, loadable=80, cypher=rel_lists_odp),
        RelStep(rel_type='MAPS_TO_REQUIREMENT', csv_name='rels_MAPS_TO_REQUIREMENT.csv',
                properties=[],
                rows=156, loadable=156, cypher=rel_maps_to_requirement),
        RelStep(rel_type='ODP_APPLIES_TO_CLAUSE', csv_name='rels_ODP_APPLIES_TO_CLAUSE.csv',
                properties=[],
                rows=72, loadable=72, cypher=rel_odp_applies_to_clause),
        RelStep(rel_type='SUPPORTED_BY_PUBLICATION', csv_name='rels_SUPPORTED_BY_PUBLICATION.csv',
                properties=[],
                rows=199, loadable=199, cypher=rel_supported_by_publication),
        RelStep(rel_type='TAILORS_CONTROL', csv_name='rels_TAILORS_CONTROL.csv',
                properties=[],
                rows=345, loadable=345, cypher=rel_tailors_control),
        RelStep(rel_type='TERM_SOURCE', csv_name='rels_TERM_SOURCE.csv',
                properties=[],
                rows=38, loadable=38, cypher=rel_term_source),
    ],
    expected_nodes_total=1406,
    expected_rels_total=2520,
)

if __name__ == "__main__":
    run(LOADER)
