"""Loader — Philippines DPA IRR.

Source folder : New sources/Philippines DPA IRR
Source document(s):
    KB 2/Philippines/IRR-of-the-DPA.pdf

Graph shape   : 8 node labels, 5 relationship types
Expected size : 452 nodes / 507 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/philippines_dpa_irr.py --dry-run   # validate, write nothing
    python App_new/philippines_dpa_irr.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'PHILIPPINES_DPA_IRR'
FOLDER = 'Philippines DPA IRR'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'PHILIPPINES_DPA_IRR'})
SET f.name = 'Philippines DPA IRR',
    f.jurisdiction = 'Philippines',
    f.folder = 'Philippines DPA IRR',
    f.source_document = 'KB 2/Philippines/IRR-of-the-DPA.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'PHILIPPINES_DPA_IRR'})
MATCH (n:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR'})
WHERE NOT (:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Clause.csv  (311 rows, key clause_id)
node_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.clause_id})
  SET
      n:Clause,
      n.clause_id = row.clause_id,
      n.label = row.label,
      n.level = row.level,
      n.citation = row.citation,
      n.text = row.text,
      n.section_id = row.section_id,
      n.parent_id = row.parent_id,
      n.parent_type = row.parent_type,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (20 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.definition_text = row.definition_text,
      n.clause_id = row.clause_id,
      n.section_id = row.section_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ExternalReference.csv  (13 rows, key externalreference_id)
node_externalreference = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.externalreference_id})
  SET
      n:ExternalReference,
      n.externalreference_id = row.externalreference_id,
      n.name = row.name,
      n.note = row.note,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Instrument.csv  (1 rows, key instrument_id)
node_instrument = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.instrument_id})
  SET
      n:Instrument,
      n.instrument_id = row.instrument_id,
      n.title = row.title,
      n.short_title = row.short_title,
      n.issuing_body = row.issuing_body,
      n.promulgated = row.promulgated,
      n.effectivity = row.effectivity,
      n.instrument_type = row.instrument_type,
      n.implements = row.implements,
      n.act_text_in_kb = row.act_text_in_kb,
      n.preamble = row.preamble,
      n.signatories = row.signatories,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Penalty.csv  (14 rows, key penalty_id)
node_penalty = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.penalty_id})
  SET
      n:Penalty,
      n.penalty_id = row.penalty_id,
      n.offense = row.offense,
      n.imprisonment = row.imprisonment,
      n.fine_minimum = row.fine_minimum,
      n.fine_maximum = row.fine_maximum,
      n.text = row.text,
      n.source_node_id = row.source_node_id,
      n.source_node_type = row.source_node_type,
      n.section_id = row.section_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Right.csv  (7 rows, key right_id)
node_right = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.right_id})
  SET
      n:Right,
      n.right_id = row.right_id,
      n.name = row.name,
      n.text = row.text,
      n.clause_id = row.clause_id,
      n.section_id = row.section_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Rule.csv  (14 rows, key rule_id)
node_rule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.rule_id})
  SET
      n:Rule,
      n.rule_id = row.rule_id,
      n.rule_number = row.rule_number,
      n.title = row.title,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Section.csv  (72 rows, key section_id)
node_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.section_id})
  SET
      n:Section,
      n.section_id = row.section_id,
      n.section_number = row.section_number,
      n.title = row.title,
      n.text = row.text,
      n.rule_id = row.rule_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_CITES_EXTERNAL.csv -> :CITES_EXTERNAL  (69 rows)
rel_cites_external = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CITES_EXTERNAL'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.target_id})
  MERGE (s)-[r:CITES_EXTERNAL]->(t)
  SET r.source_node_type = row.source_node_type,
      r.matched_text = row.matched_text
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_CONTAINS.csv -> :CONTAINS  (397 rows)
rel_contains = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CONTAINS'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.target_id})
  MERGE (s)-[r:CONTAINS]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DEFINES.csv -> :DEFINES  (20 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
  SET r.clause_id = row.clause_id
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_GRANTS_RIGHT.csv -> :GRANTS_RIGHT  (7 rows)
rel_grants_right = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'GRANTS_RIGHT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.target_id})
  MERGE (s)-[r:GRANTS_RIGHT]->(t)
  SET r.clause_id = row.clause_id
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_IMPOSES_PENALTY.csv -> :IMPOSES_PENALTY  (14 rows)
rel_imposes_penalty = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'IMPOSES_PENALTY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'PHILIPPINES_DPA_IRR', node_id: row.target_id})
  MERGE (s)-[r:IMPOSES_PENALTY]->(t)
  SET r.source_node_type = row.source_node_type
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='Philippines DPA IRR',
    folder=FOLDER,
    jurisdiction='Philippines',
    source_document='KB 2/Philippines/IRR-of-the-DPA.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Clause', csv_name='nodes_Clause.csv', id_column='clause_id',
                 properties=['label', 'level', 'citation', 'text', 'section_id', 'parent_id', 'parent_type', 'source_document'],
                 rows=311, loadable=311, cypher=node_clause),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'definition_text', 'clause_id', 'section_id', 'source_document'],
                 rows=20, loadable=20, cypher=node_definition),
        NodeStep(label='ExternalReference', csv_name='nodes_ExternalReference.csv', id_column='externalreference_id',
                 properties=['name', 'note', 'source_document'],
                 rows=13, loadable=13, cypher=node_externalreference),
        NodeStep(label='Instrument', csv_name='nodes_Instrument.csv', id_column='instrument_id',
                 properties=['title', 'short_title', 'issuing_body', 'promulgated', 'effectivity', 'instrument_type', 'implements', 'act_text_in_kb', 'preamble', 'signatories', 'source_document'],
                 rows=1, loadable=1, cypher=node_instrument),
        NodeStep(label='Penalty', csv_name='nodes_Penalty.csv', id_column='penalty_id',
                 properties=['offense', 'imprisonment', 'fine_minimum', 'fine_maximum', 'text', 'source_node_id', 'source_node_type', 'section_id', 'source_document'],
                 rows=14, loadable=14, cypher=node_penalty),
        NodeStep(label='Right', csv_name='nodes_Right.csv', id_column='right_id',
                 properties=['name', 'text', 'clause_id', 'section_id', 'source_document'],
                 rows=7, loadable=7, cypher=node_right),
        NodeStep(label='Rule', csv_name='nodes_Rule.csv', id_column='rule_id',
                 properties=['rule_number', 'title', 'source_document'],
                 rows=14, loadable=14, cypher=node_rule),
        NodeStep(label='Section', csv_name='nodes_Section.csv', id_column='section_id',
                 properties=['section_number', 'title', 'text', 'rule_id', 'source_document'],
                 rows=72, loadable=72, cypher=node_section),
    ],
    rel_steps=[
        RelStep(rel_type='CITES_EXTERNAL', csv_name='rels_CITES_EXTERNAL.csv',
                properties=['source_node_type', 'matched_text'],
                rows=69, loadable=69, cypher=rel_cites_external),
        RelStep(rel_type='CONTAINS', csv_name='rels_CONTAINS.csv',
                properties=[],
                rows=397, loadable=397, cypher=rel_contains),
        RelStep(rel_type='DEFINES', csv_name='rels_DEFINES.csv',
                properties=['clause_id'],
                rows=20, loadable=20, cypher=rel_defines),
        RelStep(rel_type='GRANTS_RIGHT', csv_name='rels_GRANTS_RIGHT.csv',
                properties=['clause_id'],
                rows=7, loadable=7, cypher=rel_grants_right),
        RelStep(rel_type='IMPOSES_PENALTY', csv_name='rels_IMPOSES_PENALTY.csv',
                properties=['source_node_type'],
                rows=14, loadable=14, cypher=rel_imposes_penalty),
    ],
    expected_nodes_total=452,
    expected_rels_total=507,
)

if __name__ == "__main__":
    run(LOADER)
