"""Loader — Qatar PDPPL.

Source folder : New sources/Qatar PDPPL
Source document(s):
    KB 2/Qatar/Qatar Personal Data Privacy Protection Law.pdf

Graph shape   : 11 node labels, 13 relationship types
Expected size : 150 nodes / 183 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/qatar_pdppl.py --dry-run   # validate, write nothing
    python App_new/qatar_pdppl.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'QATAR_PDPPL'
FOLDER = 'Qatar PDPPL'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'QATAR_PDPPL'})
SET f.name = 'Qatar PDPPL',
    f.jurisdiction = 'Qatar',
    f.folder = 'Qatar PDPPL',
    f.source_document = 'KB 2/Qatar/Qatar Personal Data Privacy Protection Law.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'QATAR_PDPPL'})
MATCH (n:NewSourceNode {framework_id: 'QATAR_PDPPL'})
WHERE NOT (:NewSourceNode {framework_id: 'QATAR_PDPPL'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Article.csv  (32 rows, key article_id)
node_article = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.article_id})
  SET
      n:Article,
      n.article_id = row.article_id,
      n.label = row.label,
      n.number = row.number,
      n.chapter_id = row.chapter_id,
      n.chapter_title = row.chapter_title,
      n.text = row.text,
      n.subject_actor = row.subject_actor,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Chapter.csv  (8 rows, key chapter_id)
node_chapter = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.chapter_id})
  SET
      n:Chapter,
      n.chapter_id = row.chapter_id,
      n.label = row.label,
      n.number = row.number,
      n.title = row.title,
      n.article_range = row.article_range,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Clause.csv  (61 rows, key clause_id)
node_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.clause_id})
  SET
      n:Clause,
      n.clause_id = row.clause_id,
      n.article_id = row.article_id,
      n.article_number = row.article_number,
      n.clause_number = row.clause_number,
      n.clause_type = row.clause_type,
      n.text = row.text,
      n.modal = row.modal,
      n.citation = row.citation,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Deadline.csv  (3 rows, key deadline_id)
node_deadline = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.deadline_id})
  SET
      n:Deadline,
      n.deadline_id = row.deadline_id,
      n.provision_id = row.provision_id,
      n.period = row.period,
      n.text = row.text,
      n.trigger = row.trigger,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (17 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.definition_text = row.definition_text,
      n.defined_in_article = row.defined_in_article,
      n.citation = row.citation,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ExternalInstrument.csv  (7 rows, key externalinstrument_id)
node_externalinstrument = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.externalinstrument_id})
  SET
      n:ExternalInstrument,
      n.externalinstrument_id = row.externalinstrument_id,
      n.title = row.title,
      n.reference = row.reference,
      n.cited_in = row.cited_in,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Law.csv  (1 rows, key law_id)
node_law = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.law_id})
  SET
      n:Law,
      n.law_id = row.law_id,
      n.title = row.title,
      n.short_title = row.short_title,
      n.jurisdiction = row.jurisdiction,
      n.promulgated_by = row.promulgated_by,
      n.issue_date_hijri = row.issue_date_hijri,
      n.issue_date_gregorian = row.issue_date_gregorian,
      n.place_of_issue = row.place_of_issue,
      n.official_status_note = row.official_status_note,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Penalty.csv  (3 rows, key penalty_id)
node_penalty = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.penalty_id})
  SET
      n:Penalty,
      n.penalty_id = row.penalty_id,
      n.article_id = row.article_id,
      n.max_amount = row.max_amount,
      n.currency = row.currency,
      n.amount_text = row.amount_text,
      n.applies_to = row.applies_to,
      n.without_prejudice_clause = row.without_prejudice_clause,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Preamble.csv  (1 rows, key preamble_id)
node_preamble = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.preamble_id})
  SET
      n:Preamble,
      n.preamble_id = row.preamble_id,
      n.law_id = row.law_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Right.csv  (10 rows, key right_id)
node_right = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.right_id})
  SET
      n:Right,
      n.right_id = row.right_id,
      n.right_name = row.right_name,
      n.provision_id = row.provision_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_SpecialNatureDataCategory.csv  (7 rows, key specialnaturedatacategory_id)
node_specialnaturedatacategory = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.specialnaturedatacategory_id})
  SET
      n:SpecialNatureDataCategory,
      n.specialnaturedatacategory_id = row.specialnaturedatacategory_id,
      n.category = row.category,
      n.text = row.text,
      n.provision_id = row.provision_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_CLASSIFIES_AS_SPECIAL_NATURE.csv -> :CLASSIFIES_AS_SPECIAL_NATURE  (7 rows)
rel_classifies_as_special_nature = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CLASSIFIES_AS_SPECIAL_NATURE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:CLASSIFIES_AS_SPECIAL_NATURE]->(t)
  SET r.category = row.category
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_CROSS_REFERENCES.csv -> :CROSS_REFERENCES  (9 rows)
rel_cross_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CROSS_REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:CROSS_REFERENCES]->(t)
  SET r.reference_text = row.reference_text
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DEFINES.csv -> :DEFINES  (17 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
  SET r.term = row.term
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_EXEMPTS_FROM.csv -> :EXEMPTS_FROM  (11 rows)
rel_exempts_from = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'EXEMPTS_FROM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:EXEMPTS_FROM]->(t)
  SET r.basis_text = row.basis_text
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_GRANTS_RIGHT.csv -> :GRANTS_RIGHT  (10 rows)
rel_grants_right = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'GRANTS_RIGHT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:GRANTS_RIGHT]->(t)
  SET r.right_name = row.right_name
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_ARTICLE.csv -> :HAS_ARTICLE  (32 rows)
rel_has_article = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ARTICLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:HAS_ARTICLE]->(t)
  SET r.article_number = row.article_number
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_CHAPTER.csv -> :HAS_CHAPTER  (8 rows)
rel_has_chapter = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CHAPTER'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:HAS_CHAPTER]->(t)
  SET r.chapter_number = row.chapter_number
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_CLAUSE.csv -> :HAS_CLAUSE  (61 rows)
rel_has_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:HAS_CLAUSE]->(t)
  SET r.clause_number = row.clause_number
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_PREAMBLE.csv -> :HAS_PREAMBLE  (1 rows)
rel_has_preamble = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PREAMBLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:HAS_PREAMBLE]->(t)
  SET r.note = row.note
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_IMPOSED_BY.csv -> :IMPOSED_BY  (3 rows)
rel_imposed_by = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'IMPOSED_BY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:IMPOSED_BY]->(t)
  SET r.note = row.note
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_PENALISES.csv -> :PENALISES  (13 rows)
rel_penalises = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'PENALISES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:PENALISES]->(t)
  SET r.note = row.note
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_REFERENCES_INSTRUMENT.csv -> :REFERENCES_INSTRUMENT  (8 rows)
rel_references_instrument = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES_INSTRUMENT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES_INSTRUMENT]->(t)
  SET r.context = row.context
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_SETS_DEADLINE.csv -> :SETS_DEADLINE  (3 rows)
rel_sets_deadline = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'SETS_DEADLINE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'QATAR_PDPPL', node_id: row.target_id})
  MERGE (s)-[r:SETS_DEADLINE]->(t)
  SET r.period = row.period
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='Qatar PDPPL',
    folder=FOLDER,
    jurisdiction='Qatar',
    source_document='KB 2/Qatar/Qatar Personal Data Privacy Protection Law.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Article', csv_name='nodes_Article.csv', id_column='article_id',
                 properties=['label', 'number', 'chapter_id', 'chapter_title', 'text', 'subject_actor', 'source_document'],
                 rows=32, loadable=32, cypher=node_article),
        NodeStep(label='Chapter', csv_name='nodes_Chapter.csv', id_column='chapter_id',
                 properties=['label', 'number', 'title', 'article_range', 'source_document'],
                 rows=8, loadable=8, cypher=node_chapter),
        NodeStep(label='Clause', csv_name='nodes_Clause.csv', id_column='clause_id',
                 properties=['article_id', 'article_number', 'clause_number', 'clause_type', 'text', 'modal', 'citation', 'source_document'],
                 rows=61, loadable=61, cypher=node_clause),
        NodeStep(label='Deadline', csv_name='nodes_Deadline.csv', id_column='deadline_id',
                 properties=['provision_id', 'period', 'text', 'trigger', 'source_document'],
                 rows=3, loadable=3, cypher=node_deadline),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'definition_text', 'defined_in_article', 'citation', 'source_document'],
                 rows=17, loadable=17, cypher=node_definition),
        NodeStep(label='ExternalInstrument', csv_name='nodes_ExternalInstrument.csv', id_column='externalinstrument_id',
                 properties=['title', 'reference', 'cited_in', 'source_document'],
                 rows=7, loadable=7, cypher=node_externalinstrument),
        NodeStep(label='Law', csv_name='nodes_Law.csv', id_column='law_id',
                 properties=['title', 'short_title', 'jurisdiction', 'promulgated_by', 'issue_date_hijri', 'issue_date_gregorian', 'place_of_issue', 'official_status_note', 'source_document'],
                 rows=1, loadable=1, cypher=node_law),
        NodeStep(label='Penalty', csv_name='nodes_Penalty.csv', id_column='penalty_id',
                 properties=['article_id', 'max_amount', 'currency', 'amount_text', 'applies_to', 'without_prejudice_clause', 'source_document'],
                 rows=3, loadable=3, cypher=node_penalty),
        NodeStep(label='Preamble', csv_name='nodes_Preamble.csv', id_column='preamble_id',
                 properties=['law_id', 'text', 'source_document'],
                 rows=1, loadable=1, cypher=node_preamble),
        NodeStep(label='Right', csv_name='nodes_Right.csv', id_column='right_id',
                 properties=['right_name', 'provision_id', 'text', 'source_document'],
                 rows=10, loadable=10, cypher=node_right),
        NodeStep(label='SpecialNatureDataCategory', csv_name='nodes_SpecialNatureDataCategory.csv', id_column='specialnaturedatacategory_id',
                 properties=['category', 'text', 'provision_id', 'source_document'],
                 rows=7, loadable=7, cypher=node_specialnaturedatacategory),
    ],
    rel_steps=[
        RelStep(rel_type='CLASSIFIES_AS_SPECIAL_NATURE', csv_name='rels_CLASSIFIES_AS_SPECIAL_NATURE.csv',
                properties=['category'],
                rows=7, loadable=7, cypher=rel_classifies_as_special_nature),
        RelStep(rel_type='CROSS_REFERENCES', csv_name='rels_CROSS_REFERENCES.csv',
                properties=['reference_text'],
                rows=9, loadable=9, cypher=rel_cross_references),
        RelStep(rel_type='DEFINES', csv_name='rels_DEFINES.csv',
                properties=['term'],
                rows=17, loadable=17, cypher=rel_defines),
        RelStep(rel_type='EXEMPTS_FROM', csv_name='rels_EXEMPTS_FROM.csv',
                properties=['basis_text'],
                rows=11, loadable=11, cypher=rel_exempts_from),
        RelStep(rel_type='GRANTS_RIGHT', csv_name='rels_GRANTS_RIGHT.csv',
                properties=['right_name'],
                rows=10, loadable=10, cypher=rel_grants_right),
        RelStep(rel_type='HAS_ARTICLE', csv_name='rels_HAS_ARTICLE.csv',
                properties=['article_number'],
                rows=32, loadable=32, cypher=rel_has_article),
        RelStep(rel_type='HAS_CHAPTER', csv_name='rels_HAS_CHAPTER.csv',
                properties=['chapter_number'],
                rows=8, loadable=8, cypher=rel_has_chapter),
        RelStep(rel_type='HAS_CLAUSE', csv_name='rels_HAS_CLAUSE.csv',
                properties=['clause_number'],
                rows=61, loadable=61, cypher=rel_has_clause),
        RelStep(rel_type='HAS_PREAMBLE', csv_name='rels_HAS_PREAMBLE.csv',
                properties=['note'],
                rows=1, loadable=1, cypher=rel_has_preamble),
        RelStep(rel_type='IMPOSED_BY', csv_name='rels_IMPOSED_BY.csv',
                properties=['note'],
                rows=3, loadable=3, cypher=rel_imposed_by),
        RelStep(rel_type='PENALISES', csv_name='rels_PENALISES.csv',
                properties=['note'],
                rows=13, loadable=13, cypher=rel_penalises),
        RelStep(rel_type='REFERENCES_INSTRUMENT', csv_name='rels_REFERENCES_INSTRUMENT.csv',
                properties=['context'],
                rows=8, loadable=8, cypher=rel_references_instrument),
        RelStep(rel_type='SETS_DEADLINE', csv_name='rels_SETS_DEADLINE.csv',
                properties=['period'],
                rows=3, loadable=3, cypher=rel_sets_deadline),
    ],
    expected_nodes_total=150,
    expected_rels_total=183,
)

if __name__ == "__main__":
    run(LOADER)
