"""Loader — South Africa POPIA.

Source folder : New sources/South Africa POPIA
Source document(s):
    Protection of Personal Information Act, 2013 (Act 4 of 2013): Amendment of the Regulations relating to the Protection of Personal Information, 2018 (tabled 21 January 2025) [KB 2/Africa/Protection of Personal Information Act.pdf]

Graph shape   : 10 node labels, 12 relationship types
Expected size : 159 nodes / 186 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/south_africa_popia.py --dry-run   # validate, write nothing
    python App_new/south_africa_popia.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'SOUTH_AFRICA_POPIA'
FOLDER = 'South Africa POPIA'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'SOUTH_AFRICA_POPIA'})
SET f.name = 'South Africa POPIA',
    f.jurisdiction = 'South Africa',
    f.folder = 'South Africa POPIA',
    f.source_document = 'Protection of Personal Information Act, 2013 (Act 4 of 2013): Amendment of the Regulations relating to the Protection of Personal Information, 2018 (tabled 21 January 2025) [KB 2/Africa/Protection of Personal Information Act.pdf]',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'SOUTH_AFRICA_POPIA'})
MATCH (n:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA'})
WHERE NOT (:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_ActSection.csv  (21 rows, key actsection_id)
node_actsection = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.actsection_id})
  SET
      n:ActSection,
      n.actsection_id = row.actsection_id,
      n.citation = row.citation,
      n.act = row.act,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_AmendmentItem.csv  (11 rows, key amendmentitem_id)
node_amendmentitem = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.amendmentitem_id})
  SET
      n:AmendmentItem,
      n.amendmentitem_id = row.amendmentitem_id,
      n.number = row.number,
      n.heading = row.heading,
      n.kind = row.kind,
      n.target_regulation = row.target_regulation,
      n.text = row.text,
      n.substituted_regulation_heading = row.substituted_regulation_heading,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (6 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.definition_text = row.definition_text,
      n.introduced_by_provision = row.introduced_by_provision,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_DefinitionParagraph.csv  (5 rows, key definitionparagraph_id)
node_definitionparagraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.definitionparagraph_id})
  SET
      n:DefinitionParagraph,
      n.definitionparagraph_id = row.definitionparagraph_id,
      n.definition_id = row.definition_id,
      n.label = row.label,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ExternalInstrument.csv  (4 rows, key externalinstrument_id)
node_externalinstrument = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.externalinstrument_id})
  SET
      n:ExternalInstrument,
      n.externalinstrument_id = row.externalinstrument_id,
      n.citation = row.citation,
      n.cited_provision = row.cited_provision,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Form.csv  (8 rows, key form_id)
node_form = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.form_id})
  SET
      n:Form,
      n.form_id = row.form_id,
      n.label = row.label,
      n.title = row.title,
      n.prescribed_by_regulation = row.prescribed_by_regulation,
      n.status = row.status,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_FormSection.csv  (25 rows, key formsection_id)
node_formsection = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.formsection_id})
  SET
      n:FormSection,
      n.formsection_id = row.formsection_id,
      n.form_id = row.form_id,
      n.label = row.label,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Instrument.csv  (1 rows, key instrument_id)
node_instrument = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.instrument_id})
  SET
      n:Instrument,
      n.instrument_id = row.instrument_id,
      n.title = row.title,
      n.parent_act = row.parent_act,
      n.jurisdiction = row.jurisdiction,
      n.issuing_authority = row.issuing_authority,
      n.date_signed = row.date_signed,
      n.enabling_provision = row.enabling_provision,
      n.short_title_and_commencement = row.short_title_and_commencement,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Provision.csv  (74 rows, key provision_id)
node_provision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.provision_id})
  SET
      n:Provision,
      n.provision_id = row.provision_id,
      n.number = row.number,
      n.parent_provision_id = row.parent_provision_id,
      n.amendment_item_id = row.amendment_item_id,
      n.text = row.text,
      n.deadline = row.deadline,
      n.obligated_party = row.obligated_party,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_TablingNotice.csv  (4 rows, key tablingnotice_id)
node_tablingnotice = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.tablingnotice_id})
  SET
      n:TablingNotice,
      n.tablingnotice_id = row.tablingnotice_id,
      n.label = row.label,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_CONTAINS.csv -> :CONTAINS  (23 rows)
rel_contains = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CONTAINS'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.target_id})
  MERGE (s)-[r:CONTAINS]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_CROSS_REFERENCES.csv -> :CROSS_REFERENCES  (8 rows)
rel_cross_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CROSS_REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.target_id})
  MERGE (s)-[r:CROSS_REFERENCES]->(t)
  SET r.quote = row.quote
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_DEFINES.csv -> :DEFINES  (6 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_FORM_SECTION.csv -> :HAS_FORM_SECTION  (25 rows)
rel_has_form_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_FORM_SECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.target_id})
  MERGE (s)-[r:HAS_FORM_SECTION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_PARAGRAPH.csv -> :HAS_PARAGRAPH  (5 rows)
rel_has_paragraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PARAGRAPH'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.target_id})
  MERGE (s)-[r:HAS_PARAGRAPH]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_PROVISION.csv -> :HAS_PROVISION  (38 rows)
rel_has_provision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PROVISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.target_id})
  MERGE (s)-[r:HAS_PROVISION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_HAS_PROVISION.csv -> :HAS_SUBPROVISION  (36 rows)
rel_has_subprovision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBPROVISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBPROVISION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_PRESCRIBES_FORM.csv -> :PRESCRIBES_FORM  (6 rows)
rel_prescribes_form = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'PRESCRIBES_FORM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.target_id})
  MERGE (s)-[r:PRESCRIBES_FORM]->(t)
  SET r.quote = row.quote
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_PRESCRIBES_FORM.csv -> :DELETES_FORM  (3 rows)
rel_deletes_form = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DELETES_FORM'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.target_id})
  MERGE (s)-[r:DELETES_FORM]->(t)
  SET r.quote = row.quote
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_REFERENCES_ACT_SECTION.csv -> :REFERENCES_ACT_SECTION  (30 rows)
rel_references_act_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES_ACT_SECTION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES_ACT_SECTION]->(t)
  SET r.quote = row.quote
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_REFERENCES_STATUTE.csv -> :REFERENCES_STATUTE  (5 rows)
rel_references_statute = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'REFERENCES_STATUTE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.target_id})
  MERGE (s)-[r:REFERENCES_STATUTE]->(t)
  SET r.quote = row.quote
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_REFERENCES_STATUTE.csv -> :AMENDS  (1 rows)
rel_amends = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'AMENDS'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'SOUTH_AFRICA_POPIA', node_id: row.target_id})
  MERGE (s)-[r:AMENDS]->(t)
  SET r.quote = row.quote
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='South Africa POPIA',
    folder=FOLDER,
    jurisdiction='South Africa',
    source_document='Protection of Personal Information Act, 2013 (Act 4 of 2013): Amendment of the Regulations relating to the Protection of Personal Information, 2018 (tabled 21 January 2025) [KB 2/Africa/Protection of Personal Information Act.pdf]',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='ActSection', csv_name='nodes_ActSection.csv', id_column='actsection_id',
                 properties=['citation', 'act', 'source_document'],
                 rows=21, loadable=21, cypher=node_actsection),
        NodeStep(label='AmendmentItem', csv_name='nodes_AmendmentItem.csv', id_column='amendmentitem_id',
                 properties=['number', 'heading', 'kind', 'target_regulation', 'text', 'substituted_regulation_heading', 'source_document'],
                 rows=11, loadable=11, cypher=node_amendmentitem),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'definition_text', 'introduced_by_provision', 'source_document'],
                 rows=6, loadable=6, cypher=node_definition),
        NodeStep(label='DefinitionParagraph', csv_name='nodes_DefinitionParagraph.csv', id_column='definitionparagraph_id',
                 properties=['definition_id', 'label', 'text', 'source_document'],
                 rows=5, loadable=5, cypher=node_definitionparagraph),
        NodeStep(label='ExternalInstrument', csv_name='nodes_ExternalInstrument.csv', id_column='externalinstrument_id',
                 properties=['citation', 'cited_provision', 'source_document'],
                 rows=4, loadable=4, cypher=node_externalinstrument),
        NodeStep(label='Form', csv_name='nodes_Form.csv', id_column='form_id',
                 properties=['label', 'title', 'prescribed_by_regulation', 'status', 'source_document'],
                 rows=8, loadable=8, cypher=node_form),
        NodeStep(label='FormSection', csv_name='nodes_FormSection.csv', id_column='formsection_id',
                 properties=['form_id', 'label', 'text', 'source_document'],
                 rows=25, loadable=25, cypher=node_formsection),
        NodeStep(label='Instrument', csv_name='nodes_Instrument.csv', id_column='instrument_id',
                 properties=['title', 'parent_act', 'jurisdiction', 'issuing_authority', 'date_signed', 'enabling_provision', 'short_title_and_commencement', 'source_document'],
                 rows=1, loadable=1, cypher=node_instrument),
        NodeStep(label='Provision', csv_name='nodes_Provision.csv', id_column='provision_id',
                 properties=['number', 'parent_provision_id', 'amendment_item_id', 'text', 'deadline', 'obligated_party', 'source_document'],
                 rows=74, loadable=74, cypher=node_provision),
        NodeStep(label='TablingNotice', csv_name='nodes_TablingNotice.csv', id_column='tablingnotice_id',
                 properties=['label', 'text', 'source_document'],
                 rows=4, loadable=4, cypher=node_tablingnotice),
    ],
    rel_steps=[
        RelStep(rel_type='CONTAINS', csv_name='rels_CONTAINS.csv',
                properties=[],
                rows=23, loadable=23, cypher=rel_contains),
        RelStep(rel_type='CROSS_REFERENCES', csv_name='rels_CROSS_REFERENCES.csv',
                properties=['quote'],
                rows=8, loadable=8, cypher=rel_cross_references),
        RelStep(rel_type='DEFINES', csv_name='rels_DEFINES.csv',
                properties=[],
                rows=6, loadable=6, cypher=rel_defines),
        RelStep(rel_type='HAS_FORM_SECTION', csv_name='rels_HAS_FORM_SECTION.csv',
                properties=[],
                rows=25, loadable=25, cypher=rel_has_form_section),
        RelStep(rel_type='HAS_PARAGRAPH', csv_name='rels_HAS_PARAGRAPH.csv',
                properties=[],
                rows=5, loadable=5, cypher=rel_has_paragraph),
        RelStep(rel_type='HAS_PROVISION', csv_name='rels_HAS_PROVISION.csv',
                properties=[],
                rows=38, loadable=38, cypher=rel_has_provision),
        RelStep(rel_type='HAS_SUBPROVISION', csv_name='rels_HAS_PROVISION.csv',
                properties=[],
                rows=36, loadable=36, cypher=rel_has_subprovision),
        RelStep(rel_type='PRESCRIBES_FORM', csv_name='rels_PRESCRIBES_FORM.csv',
                properties=['quote'],
                rows=6, loadable=6, cypher=rel_prescribes_form),
        RelStep(rel_type='DELETES_FORM', csv_name='rels_PRESCRIBES_FORM.csv',
                properties=['quote'],
                rows=3, loadable=3, cypher=rel_deletes_form),
        RelStep(rel_type='REFERENCES_ACT_SECTION', csv_name='rels_REFERENCES_ACT_SECTION.csv',
                properties=['quote'],
                rows=30, loadable=30, cypher=rel_references_act_section),
        RelStep(rel_type='REFERENCES_STATUTE', csv_name='rels_REFERENCES_STATUTE.csv',
                properties=['quote'],
                rows=5, loadable=5, cypher=rel_references_statute),
        RelStep(rel_type='AMENDS', csv_name='rels_REFERENCES_STATUTE.csv',
                properties=['quote'],
                rows=1, loadable=1, cypher=rel_amends),
    ],
    expected_nodes_total=159,
    expected_rels_total=186,
)

if __name__ == "__main__":
    run(LOADER)
