"""Loader — UAE PDPL.

Source folder : New sources/UAE PDPL
Source document(s):
    KB 2/UAE/Federal Decree by Law No. (45) of 2021 Concerning the Protection of Personal Data.pdf

Graph shape   : 6 node labels, 6 relationship types
Expected size : 229 nodes / 249 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/uae_pdpl.py --dry-run   # validate, write nothing
    python App_new/uae_pdpl.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'UAE_PDPL'
FOLDER = 'UAE PDPL'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'UAE_PDPL'})
SET f.name = 'UAE PDPL',
    f.jurisdiction = 'United Arab Emirates',
    f.folder = 'UAE PDPL',
    f.source_document = 'KB 2/UAE/Federal Decree by Law No. (45) of 2021 Concerning the Protection of Personal Data.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'UAE_PDPL'})
MATCH (n:NewSourceNode {framework_id: 'UAE_PDPL'})
WHERE NOT (:NewSourceNode {framework_id: 'UAE_PDPL'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_Article.csv  (31 rows, key article_id)
node_article = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.article_id})
  SET
      n:Article,
      n.article_id = row.article_id,
      n.article_number = row.article_number,
      n.article_title = row.article_title,
      n.article_text = row.article_text,
      n.citation = row.citation,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_CitedLegislation.csv  (9 rows, key citedlegislation_id)
node_citedlegislation = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.citedlegislation_id})
  SET
      n:CitedLegislation,
      n.citedlegislation_id = row.citedlegislation_id,
      n.citation_text = row.citation_text,
      n.amendment_note = row.amendment_note,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Clause.csv  (88 rows, key clause_id)
node_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.clause_id})
  SET
      n:Clause,
      n.clause_id = row.clause_id,
      n.article_id = row.article_id,
      n.clause_number = row.clause_number,
      n.clause_text = row.clause_text,
      n.citation = row.citation,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (20 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.definition_text = row.definition_text,
      n.defined_in_article = row.defined_in_article,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Instrument.csv  (1 rows, key instrument_id)
node_instrument = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.instrument_id})
  SET
      n:Instrument,
      n.instrument_id = row.instrument_id,
      n.title = row.title,
      n.instrument_type = row.instrument_type,
      n.number = row.number,
      n.year = row.year,
      n.jurisdiction = row.jurisdiction,
      n.promulgated_by = row.promulgated_by,
      n.issue_date_hijri = row.issue_date_hijri,
      n.issue_date_gregorian = row.issue_date_gregorian,
      n.place_of_issue = row.place_of_issue,
      n.publication_and_enforcement = row.publication_and_enforcement,
      n.entry_into_force = row.entry_into_force,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_SubClause.csv  (80 rows, key subclause_id)
node_subclause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.subclause_id})
  SET
      n:SubClause,
      n.subclause_id = row.subclause_id,
      n.clause_id = row.clause_id,
      n.article_id = row.article_id,
      n.item_label = row.item_label,
      n.subclause_text = row.subclause_text,
      n.citation = row.citation,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_cites.csv -> :CITES  (9 rows)
rel_cites = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CITES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.target_id})
  MERGE (s)-[r:CITES]->(t)
  SET r.context = row.context
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_cross_references.csv -> :CROSS_REFERENCES  (21 rows)
rel_cross_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CROSS_REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.target_id})
  MERGE (s)-[r:CROSS_REFERENCES]->(t)
  SET r.reference_text = row.reference_text
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_defines.csv -> :DEFINES  (20 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
  SET r.term = row.term
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_article.csv -> :HAS_ARTICLE  (31 rows)
rel_has_article = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_ARTICLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.target_id})
  MERGE (s)-[r:HAS_ARTICLE]->(t)
  SET r.order = row.order
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_clause.csv -> :HAS_CLAUSE  (88 rows)
rel_has_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_CLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.target_id})
  MERGE (s)-[r:HAS_CLAUSE]->(t)
  SET r.clause_number = row.clause_number
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_subclause.csv -> :HAS_SUBCLAUSE  (80 rows)
rel_has_subclause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBCLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UAE_PDPL', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBCLAUSE]->(t)
  SET r.item_label = row.item_label
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='UAE PDPL',
    folder=FOLDER,
    jurisdiction='United Arab Emirates',
    source_document='KB 2/UAE/Federal Decree by Law No. (45) of 2021 Concerning the Protection of Personal Data.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='Article', csv_name='nodes_Article.csv', id_column='article_id',
                 properties=['article_number', 'article_title', 'article_text', 'citation', 'source_document'],
                 rows=31, loadable=31, cypher=node_article),
        NodeStep(label='CitedLegislation', csv_name='nodes_CitedLegislation.csv', id_column='citedlegislation_id',
                 properties=['citation_text', 'amendment_note', 'source_document'],
                 rows=9, loadable=9, cypher=node_citedlegislation),
        NodeStep(label='Clause', csv_name='nodes_Clause.csv', id_column='clause_id',
                 properties=['article_id', 'clause_number', 'clause_text', 'citation', 'source_document'],
                 rows=88, loadable=88, cypher=node_clause),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'definition_text', 'defined_in_article', 'source_document'],
                 rows=20, loadable=20, cypher=node_definition),
        NodeStep(label='Instrument', csv_name='nodes_Instrument.csv', id_column='instrument_id',
                 properties=['title', 'instrument_type', 'number', 'year', 'jurisdiction', 'promulgated_by', 'issue_date_hijri', 'issue_date_gregorian', 'place_of_issue', 'publication_and_enforcement', 'entry_into_force', 'source_document'],
                 rows=1, loadable=1, cypher=node_instrument),
        NodeStep(label='SubClause', csv_name='nodes_SubClause.csv', id_column='subclause_id',
                 properties=['clause_id', 'article_id', 'item_label', 'subclause_text', 'citation', 'source_document'],
                 rows=80, loadable=80, cypher=node_subclause),
    ],
    rel_steps=[
        RelStep(rel_type='CITES', csv_name='rels_cites.csv',
                properties=['context'],
                rows=9, loadable=9, cypher=rel_cites),
        RelStep(rel_type='CROSS_REFERENCES', csv_name='rels_cross_references.csv',
                properties=['reference_text'],
                rows=21, loadable=21, cypher=rel_cross_references),
        RelStep(rel_type='DEFINES', csv_name='rels_defines.csv',
                properties=['term'],
                rows=20, loadable=20, cypher=rel_defines),
        RelStep(rel_type='HAS_ARTICLE', csv_name='rels_has_article.csv',
                properties=['order'],
                rows=31, loadable=31, cypher=rel_has_article),
        RelStep(rel_type='HAS_CLAUSE', csv_name='rels_has_clause.csv',
                properties=['clause_number'],
                rows=88, loadable=88, cypher=rel_has_clause),
        RelStep(rel_type='HAS_SUBCLAUSE', csv_name='rels_has_subclause.csv',
                properties=['item_label'],
                rows=80, loadable=80, cypher=rel_has_subclause),
    ],
    expected_nodes_total=229,
    expected_rels_total=249,
)

if __name__ == "__main__":
    run(LOADER)
