"""Loader — UK Cyber Essentials.

Source folder : New sources/UK Cyber Essentials
Source document(s):
    KB 2/Europe/cyber-essentials-requirements-for-it-infrastructure-v3-3.pdf

Graph shape   : 10 node labels, 10 relationship types
Expected size : 241 nodes / 369 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/uk_cyber_essentials.py --dry-run   # validate, write nothing
    python App_new/uk_cyber_essentials.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'UK_CYBER_ESSENTIALS'
FOLDER = 'UK Cyber Essentials'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'UK_CYBER_ESSENTIALS'})
SET f.name = 'UK Cyber Essentials',
    f.jurisdiction = 'United Kingdom',
    f.folder = 'UK Cyber Essentials',
    f.source_document = 'KB 2/Europe/cyber-essentials-requirements-for-it-infrastructure-v3-3.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'UK_CYBER_ESSENTIALS'})
MATCH (n:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS'})
WHERE NOT (:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_AssetType.csv  (12 rows, key assettype_id)
node_assettype = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.assettype_id})
  SET
      n:AssetType,
      n.assettype_id = row.assettype_id,
      n.name = row.name,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Clause.csv  (166 rows, key clause_id)
node_clause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.clause_id})
  SET
      n:Clause,
      n.clause_id = row.clause_id,
      n.container_id = row.container_id,
      n.parent_clause_id = row.parent_clause_id,
      n.clause_ref = row.clause_ref,
      n.heading = row.heading,
      n.obligation_type = row.obligation_type,
      n.text = row.text,
      n.page = row.page,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_CloudServiceModel.csv  (3 rows, key cloudservicemodel_id)
node_cloudservicemodel = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.cloudservicemodel_id})
  SET
      n:CloudServiceModel,
      n.cloudservicemodel_id = row.cloudservicemodel_id,
      n.name = row.name,
      n.abbreviation = row.abbreviation,
      n.description = row.description,
      n.examples = row.examples,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ControlTheme.csv  (5 rows, key controltheme_id)
node_controltheme = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.controltheme_id})
  SET
      n:ControlTheme,
      n.controltheme_id = row.controltheme_id,
      n.number = row.number,
      n.name = row.name,
      n.applies_to = row.applies_to,
      n.aim = row.aim,
      n.page = row.page,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (14 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.definition_text = row.definition_text,
      n.section_id = row.section_id,
      n.page = row.page,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Instrument.csv  (1 rows, key instrument_id)
node_instrument = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.instrument_id})
  SET
      n:Instrument,
      n.instrument_id = row.instrument_id,
      n.title = row.title,
      n.version = row.version,
      n.publisher = row.publisher,
      n.effective_date = row.effective_date,
      n.copyright = row.copyright,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_OwnershipCategory.csv  (3 rows, key ownershipcategory_id)
node_ownershipcategory = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.ownershipcategory_id})
  SET
      n:OwnershipCategory,
      n.ownershipcategory_id = row.ownershipcategory_id,
      n.name = row.name,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Role.csv  (8 rows, key role_id)
node_role = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.role_id})
  SET
      n:Role,
      n.role_id = row.role_id,
      n.name = row.name,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Section.csv  (17 rows, key section_id)
node_section = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.section_id})
  SET
      n:Section,
      n.section_id = row.section_id,
      n.section_type = row.section_type,
      n.title = row.title,
      n.parent_section_id = row.parent_section_id,
      n.page = row.page,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Threshold.csv  (12 rows, key threshold_id)
node_threshold = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.threshold_id})
  SET
      n:Threshold,
      n.threshold_id = row.threshold_id,
      n.name = row.name,
      n.value = row.value,
      n.verbatim_text = row.verbatim_text,
      n.clause_id = row.clause_id,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_applies_to_asset.csv -> :APPLIES_TO  (43 rows)
rel_applies_to = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'APPLIES_TO'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.target_id})
  MERGE (s)-[r:APPLIES_TO]->(t)
  SET r.as_stated = row.as_stated
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_clause_contained_in.csv -> :CONTAINED_IN  (166 rows)
rel_contained_in = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CONTAINED_IN'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.target_id})
  MERGE (s)-[r:CONTAINED_IN]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_clause_subclause_of.csv -> :SUBCLAUSE_OF  (69 rows)
rel_subclause_of = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'SUBCLAUSE_OF'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.target_id})
  MERGE (s)-[r:SUBCLAUSE_OF]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_cloud_responsibility.csv -> :IMPLEMENTED_BY  (15 rows)
rel_implemented_by = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'IMPLEMENTED_BY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.target_id})
  MERGE (s)-[r:IMPLEMENTED_BY]->(t)
  SET r.responsible_party = row.responsible_party
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_cross_reference.csv -> :CROSS_REFERENCES  (11 rows)
rel_cross_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CROSS_REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.target_id})
  MERGE (s)-[r:CROSS_REFERENCES]->(t)
  SET r.as_stated = row.as_stated
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_defines.csv -> :DEFINES  (14 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
  SET r.term = row.term
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_device_scope.csv -> :DEVICE_SCOPE  (24 rows)
rel_device_scope = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEVICE_SCOPE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.target_id})
  MERGE (s)-[r:DEVICE_SCOPE]->(t)
  SET r.scope_status = row.scope_status
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_section_part_of.csv -> :PART_OF  (10 rows)
rel_part_of = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'PART_OF'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.target_id})
  MERGE (s)-[r:PART_OF]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_theme_part_of_section.csv -> :PART_OF  (5 rows)
rel_part_of_2 = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'PART_OF'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.target_id})
  MERGE (s)-[r:PART_OF]->(t)
  SET r.number = row.number
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_threshold_stated_in.csv -> :STATED_IN  (12 rows)
rel_stated_in = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'STATED_IN'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_CYBER_ESSENTIALS', node_id: row.target_id})
  MERGE (s)-[r:STATED_IN]->(t)
  SET r.value = row.value
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='UK Cyber Essentials',
    folder=FOLDER,
    jurisdiction='United Kingdom',
    source_document='KB 2/Europe/cyber-essentials-requirements-for-it-infrastructure-v3-3.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='AssetType', csv_name='nodes_AssetType.csv', id_column='assettype_id',
                 properties=['name', 'source_document'],
                 rows=12, loadable=12, cypher=node_assettype),
        NodeStep(label='Clause', csv_name='nodes_Clause.csv', id_column='clause_id',
                 properties=['container_id', 'parent_clause_id', 'clause_ref', 'heading', 'obligation_type', 'text', 'page', 'source_document'],
                 rows=166, loadable=166, cypher=node_clause),
        NodeStep(label='CloudServiceModel', csv_name='nodes_CloudServiceModel.csv', id_column='cloudservicemodel_id',
                 properties=['name', 'abbreviation', 'description', 'examples', 'source_document'],
                 rows=3, loadable=3, cypher=node_cloudservicemodel),
        NodeStep(label='ControlTheme', csv_name='nodes_ControlTheme.csv', id_column='controltheme_id',
                 properties=['number', 'name', 'applies_to', 'aim', 'page', 'source_document'],
                 rows=5, loadable=5, cypher=node_controltheme),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'definition_text', 'section_id', 'page', 'source_document'],
                 rows=14, loadable=14, cypher=node_definition),
        NodeStep(label='Instrument', csv_name='nodes_Instrument.csv', id_column='instrument_id',
                 properties=['title', 'version', 'publisher', 'effective_date', 'copyright', 'source_document'],
                 rows=1, loadable=1, cypher=node_instrument),
        NodeStep(label='OwnershipCategory', csv_name='nodes_OwnershipCategory.csv', id_column='ownershipcategory_id',
                 properties=['name', 'source_document'],
                 rows=3, loadable=3, cypher=node_ownershipcategory),
        NodeStep(label='Role', csv_name='nodes_Role.csv', id_column='role_id',
                 properties=['name', 'source_document'],
                 rows=8, loadable=8, cypher=node_role),
        NodeStep(label='Section', csv_name='nodes_Section.csv', id_column='section_id',
                 properties=['section_type', 'title', 'parent_section_id', 'page', 'source_document'],
                 rows=17, loadable=17, cypher=node_section),
        NodeStep(label='Threshold', csv_name='nodes_Threshold.csv', id_column='threshold_id',
                 properties=['name', 'value', 'verbatim_text', 'clause_id', 'source_document'],
                 rows=12, loadable=12, cypher=node_threshold),
    ],
    rel_steps=[
        RelStep(rel_type='APPLIES_TO', csv_name='rels_applies_to_asset.csv',
                properties=['as_stated'],
                rows=43, loadable=43, cypher=rel_applies_to),
        RelStep(rel_type='CONTAINED_IN', csv_name='rels_clause_contained_in.csv',
                properties=[],
                rows=166, loadable=166, cypher=rel_contained_in),
        RelStep(rel_type='SUBCLAUSE_OF', csv_name='rels_clause_subclause_of.csv',
                properties=[],
                rows=69, loadable=69, cypher=rel_subclause_of),
        RelStep(rel_type='IMPLEMENTED_BY', csv_name='rels_cloud_responsibility.csv',
                properties=['responsible_party'],
                rows=15, loadable=15, cypher=rel_implemented_by),
        RelStep(rel_type='CROSS_REFERENCES', csv_name='rels_cross_reference.csv',
                properties=['as_stated'],
                rows=11, loadable=11, cypher=rel_cross_references),
        RelStep(rel_type='DEFINES', csv_name='rels_defines.csv',
                properties=['term'],
                rows=14, loadable=14, cypher=rel_defines),
        RelStep(rel_type='DEVICE_SCOPE', csv_name='rels_device_scope.csv',
                properties=['scope_status'],
                rows=24, loadable=24, cypher=rel_device_scope),
        RelStep(rel_type='PART_OF', csv_name='rels_section_part_of.csv',
                properties=[],
                rows=10, loadable=10, cypher=rel_part_of),
        RelStep(rel_type='PART_OF', csv_name='rels_theme_part_of_section.csv',
                properties=['number'],
                rows=5, loadable=5, cypher=rel_part_of_2),
        RelStep(rel_type='STATED_IN', csv_name='rels_threshold_stated_in.csv',
                properties=['value'],
                rows=12, loadable=12, cypher=rel_stated_in),
    ],
    expected_nodes_total=241,
    expected_rels_total=369,
)

if __name__ == "__main__":
    run(LOADER)
