"""Loader — UK NIS Regulations 2018.

Source folder : New sources/UK NIS Regulations 2018
Source document(s):
    KB 2/Europe/UK Network and Information Systems (NIS) Regulations 2018.pdf

Graph shape   : 17 node labels, 24 relationship types
Expected size : 1,031 nodes / 1,226 relationships

Generated by App_new/tools/gen_new_source_loaders.py from the CSV
headers on disk. Edit the generator, not this file.

    python App_new/uk_nis_regulations_2018.py --dry-run   # validate, write nothing
    python App_new/uk_nis_regulations_2018.py             # load into Neo4j
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from new_sources_runtime import Loader, NodeStep, RelStep, run

FRAMEWORK_ID = 'UK_NIS_REGULATIONS_2018'
FOLDER = 'UK NIS Regulations 2018'

# --------------------------------------------------------------------------
# Framework root node. Labelled :NewSourceFramework, not :Framework —
# four folders ship a node of their own labelled Framework, and a bare
# :Framework merge key would silently fuse the root into it.
# --------------------------------------------------------------------------

constraint = """
CREATE CONSTRAINT new_source_node_key IF NOT EXISTS
FOR (n:NewSourceNode) REQUIRE (n.framework_id, n.node_id) IS UNIQUE;
"""

framework = """
MERGE (f:NewSourceFramework {framework_id: 'UK_NIS_REGULATIONS_2018'})
SET f.name = 'UK NIS Regulations 2018',
    f.jurisdiction = 'United Kingdom',
    f.folder = 'UK NIS Regulations 2018',
    f.source_document = 'KB 2/Europe/UK Network and Information Systems (NIS) Regulations 2018.pdf',
    f.status = 'extracted';
"""

# Attach the framework to every node that nothing else points at, so each
# of the 64 graphs has a single entry point and can be traversed or deleted
# independently of the other 63.
roots = """
MATCH (f:NewSourceFramework {framework_id: 'UK_NIS_REGULATIONS_2018'})
MATCH (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018'})
WHERE NOT (:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018'})-->(n)
MERGE (f)-[:HAS_ROOT]->(n);
"""

# --------------------------------------------------------------------------
# Nodes — one statement per nodes_<Label>.csv
# --------------------------------------------------------------------------

# nodes_CompetentAuthority.csv  (17 rows, key competentauthority_id)
node_competentauthority = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.competentauthority_id})
  SET
      n:CompetentAuthority,
      n.competentauthority_id = row.competentauthority_id,
      n.name = row.name,
      n.column = row.column,
      n.source = row.source,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_CompetentAuthorityDesignation.csv  (23 rows, key competentauthoritydesignation_id)
node_competentauthoritydesignation = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.competentauthoritydesignation_id})
  SET
      n:CompetentAuthorityDesignation,
      n.competentauthoritydesignation_id = row.competentauthoritydesignation_id,
      n.schedule = row.schedule,
      n.row = row.row,
      n.relevant_sector = row.relevant_sector,
      n.subsector = row.subsector,
      n.designated_competent_authority = row.designated_competent_authority,
      n.territorial_jurisdiction = row.territorial_jurisdiction,
      n.designating_provision = row.designating_provision,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Deadline.csv  (21 rows, key deadline_id)
node_deadline = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.deadline_id})
  SET
      n:Deadline,
      n.deadline_id = row.deadline_id,
      n.expressions = row.expressions,
      n.provision_id = row.provision_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Definition.csv  (107 rows, key definition_id)
node_definition = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.definition_id})
  SET
      n:Definition,
      n.definition_id = row.definition_id,
      n.term = row.term,
      n.definition_text = row.definition_text,
      n.defined_in = row.defined_in,
      n.scope = row.scope,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_EssentialService.csv  (33 rows, key essentialservice_id)
node_essentialservice = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.essentialservice_id})
  SET
      n:EssentialService,
      n.essentialservice_id = row.essentialservice_id,
      n.name = row.name,
      n.subsector = row.subsector,
      n.specified_in = row.specified_in,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ExplanatoryNote.csv  (18 rows, key explanatorynote_id)
node_explanatorynote = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.explanatorynote_id})
  SET
      n:ExplanatoryNote,
      n.explanatorynote_id = row.explanatorynote_id,
      n.sequence = row.sequence,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Instrument.csv  (1 rows, key instrument_id)
node_instrument = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.instrument_id})
  SET
      n:Instrument,
      n.instrument_id = row.instrument_id,
      n.title = row.title,
      n.si_number = row.si_number,
      n.subject_heading = row.subject_heading,
      n.made_date = row.made_date,
      n.laid_before_parliament = row.laid_before_parliament,
      n.coming_into_force = row.coming_into_force,
      n.signed_by = row.signed_by,
      n.treasury_consent = row.treasury_consent,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Part.csv  (6 rows, key part_id)
node_part = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.part_id})
  SET
      n:Part,
      n.part_id = row.part_id,
      n.number = row.number,
      n.title = row.title,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_PenaltyTier.csv  (4 rows, key penaltytier_id)
node_penaltytier = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.penaltytier_id})
  SET
      n:PenaltyTier,
      n.penaltytier_id = row.penaltytier_id,
      n.tier = row.tier,
      n.maximum_amount = row.maximum_amount,
      n.text = row.text,
      n.specified_in = row.specified_in,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Preamble.csv  (3 rows, key preamble_id)
node_preamble = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.preamble_id})
  SET
      n:Preamble,
      n.preamble_id = row.preamble_id,
      n.sequence = row.sequence,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Provision.csv  (713 rows, key provision_id)
node_provision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.provision_id})
  SET
      n:Provision,
      n.provision_id = row.provision_id,
      n.marker = row.marker,
      n.level = row.level,
      n.clause_type = row.clause_type,
      n.citation = row.citation,
      n.parent_id = row.parent_id,
      n.text = row.text,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Regulation.csv  (25 rows, key regulation_id)
node_regulation = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.regulation_id})
  SET
      n:Regulation,
      n.regulation_id = row.regulation_id,
      n.number = row.number,
      n.heading = row.heading,
      n.part = row.part,
      n.citation = row.citation,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Schedule.csv  (2 rows, key schedule_id)
node_schedule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.schedule_id})
  SET
      n:Schedule,
      n.schedule_id = row.schedule_id,
      n.number = row.number,
      n.title = row.title,
      n.referenced_by = row.referenced_by,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_SchedulePara.csv  (10 rows, key schedulepara_id)
node_schedulepara = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.schedulepara_id})
  SET
      n:SchedulePara,
      n.schedulepara_id = row.schedulepara_id,
      n.schedule = row.schedule,
      n.number = row.number,
      n.heading = row.heading,
      n.citation = row.citation,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Sector.csv  (5 rows, key sector_id)
node_sector = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.sector_id})
  SET
      n:Sector,
      n.sector_id = row.sector_id,
      n.name = row.name,
      n.column = row.column,
      n.source = row.source,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_Subsector.csv  (10 rows, key subsector_id)
node_subsector = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.subsector_id})
  SET
      n:Subsector,
      n.subsector_id = row.subsector_id,
      n.name = row.name,
      n.sector = row.sector,
      n.column = row.column,
      n.source = row.source,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# nodes_ThresholdRequirement.csv  (33 rows, key thresholdrequirement_id)
node_thresholdrequirement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
CALL (row) {
  MERGE (n:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.thresholdrequirement_id})
  SET
      n:ThresholdRequirement,
      n.thresholdrequirement_id = row.thresholdrequirement_id,
      n.essential_service = row.essential_service,
      n.text = row.text,
      n.specified_in = row.specified_in,
      n.source_document = row.source_document
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
# Relationships — one statement per rel_type. The rel_type column is
# authoritative; a single rels_*.csv may carry several types.
# --------------------------------------------------------------------------

# rels_designation_for_subsector.csv -> :FOR_SUBSECTOR  (23 rows)
rel_for_subsector = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'FOR_SUBSECTOR'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:FOR_SUBSECTOR]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_designation_names_authority.csv -> :DESIGNATES_AUTHORITY  (23 rows)
rel_designates_authority = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DESIGNATES_AUTHORITY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:DESIGNATES_AUTHORITY]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_essentialservice_has_threshold.csv -> :HAS_THRESHOLD_REQUIREMENT  (33 rows)
rel_has_threshold_requirement = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_THRESHOLD_REQUIREMENT'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_THRESHOLD_REQUIREMENT]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_essentialservice_in_subsector.csv -> :IN_SUBSECTOR  (33 rows)
rel_in_subsector = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'IN_SUBSECTOR'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:IN_SUBSECTOR]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_has_preamble.csv -> :HAS_PREAMBLE  (3 rows)
rel_has_preamble = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PREAMBLE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_PREAMBLE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_instrument_has_explanatory_note.csv -> :HAS_EXPLANATORY_NOTE  (18 rows)
rel_has_explanatory_note = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_EXPLANATORY_NOTE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_EXPLANATORY_NOTE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_instrument_has_part.csv -> :HAS_PART  (6 rows)
rel_has_part = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PART'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_PART]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_instrument_has_schedule.csv -> :HAS_SCHEDULE  (2 rows)
rel_has_schedule = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SCHEDULE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_SCHEDULE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_part_has_regulation.csv -> :HAS_REGULATION  (25 rows)
rel_has_regulation = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_REGULATION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_REGULATION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_provision_cross_references.csv -> :CROSS_REFERENCES  (70 rows)
rel_cross_references = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'CROSS_REFERENCES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:CROSS_REFERENCES]->(t)
  SET r.target_kind = row.target_kind
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_provision_defines_term.csv -> :DEFINES  (107 rows)
rel_defines = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DEFINES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:DEFINES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_provision_designates.csv -> :DESIGNATES  (23 rows)
rel_designates = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DESIGNATES'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:DESIGNATES]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_provision_designates_authority.csv -> :DESIGNATES_AUTHORITY  (3 rows)
rel_designates_authority_2 = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'DESIGNATES_AUTHORITY'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:DESIGNATES_AUTHORITY]->(t)
  SET r.designation_text = row.designation_text
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_provision_has_deadline.csv -> :HAS_DEADLINE  (21 rows)
rel_has_deadline = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_DEADLINE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_DEADLINE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_provision_has_subclause.csv -> :HAS_SUBCLAUSE  (506 rows)
rel_has_subclause = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBCLAUSE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBCLAUSE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_provision_sets_penalty_tier.csv -> :SETS_PENALTY_TIER  (4 rows)
rel_sets_penalty_tier = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'SETS_PENALTY_TIER'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:SETS_PENALTY_TIER]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_provision_specifies_threshold.csv -> :SPECIFIES_THRESHOLD  (33 rows)
rel_specifies_threshold = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'SPECIFIES_THRESHOLD'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:SPECIFIES_THRESHOLD]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_regulation_has_provision.csv -> :HAS_PROVISION  (150 rows)
rel_has_provision = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PROVISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_PROVISION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_schedule_has_designation.csv -> :HAS_DESIGNATION  (23 rows)
rel_has_designation = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_DESIGNATION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_DESIGNATION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_schedule_has_para.csv -> :HAS_PARAGRAPH  (10 rows)
rel_has_paragraph = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PARAGRAPH'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_PARAGRAPH]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_schedulepara_covers_subsector.csv -> :COVERS_SUBSECTOR  (10 rows)
rel_covers_subsector = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'COVERS_SUBSECTOR'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:COVERS_SUBSECTOR]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_schedulepara_has_provision.csv -> :HAS_PROVISION  (57 rows)
rel_has_provision_2 = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_PROVISION'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_PROVISION]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_schedulepara_specifies_service.csv -> :SPECIFIES_ESSENTIAL_SERVICE  (33 rows)
rel_specifies_essential_service = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'SPECIFIES_ESSENTIAL_SERVICE'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:SPECIFIES_ESSENTIAL_SERVICE]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# rels_sector_has_subsector.csv -> :HAS_SUBSECTOR  (10 rows)
rel_has_subsector = """
LOAD CSV WITH HEADERS FROM '$file_path' AS row
WITH row WHERE row.rel_type = 'HAS_SUBSECTOR'
CALL (row) {
  MATCH (s:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.source_id})
  MATCH (t:NewSourceNode {framework_id: 'UK_NIS_REGULATIONS_2018', node_id: row.target_id})
  MERGE (s)-[r:HAS_SUBSECTOR]->(t)
} IN TRANSACTIONS OF 500 ROWS;
"""

# --------------------------------------------------------------------------
LOADER = Loader(
    framework_id=FRAMEWORK_ID,
    name='UK NIS Regulations 2018',
    folder=FOLDER,
    jurisdiction='United Kingdom',
    source_document='KB 2/Europe/UK Network and Information Systems (NIS) Regulations 2018.pdf',
    constraint_cypher=constraint,
    framework_cypher=framework,
    root_cypher=roots,
    node_steps=[
        NodeStep(label='CompetentAuthority', csv_name='nodes_CompetentAuthority.csv', id_column='competentauthority_id',
                 properties=['name', 'column', 'source', 'source_document'],
                 rows=17, loadable=17, cypher=node_competentauthority),
        NodeStep(label='CompetentAuthorityDesignation', csv_name='nodes_CompetentAuthorityDesignation.csv', id_column='competentauthoritydesignation_id',
                 properties=['schedule', 'row', 'relevant_sector', 'subsector', 'designated_competent_authority', 'territorial_jurisdiction', 'designating_provision', 'source_document'],
                 rows=23, loadable=23, cypher=node_competentauthoritydesignation),
        NodeStep(label='Deadline', csv_name='nodes_Deadline.csv', id_column='deadline_id',
                 properties=['expressions', 'provision_id', 'text', 'source_document'],
                 rows=21, loadable=21, cypher=node_deadline),
        NodeStep(label='Definition', csv_name='nodes_Definition.csv', id_column='definition_id',
                 properties=['term', 'definition_text', 'defined_in', 'scope', 'source_document'],
                 rows=107, loadable=107, cypher=node_definition),
        NodeStep(label='EssentialService', csv_name='nodes_EssentialService.csv', id_column='essentialservice_id',
                 properties=['name', 'subsector', 'specified_in', 'source_document'],
                 rows=33, loadable=33, cypher=node_essentialservice),
        NodeStep(label='ExplanatoryNote', csv_name='nodes_ExplanatoryNote.csv', id_column='explanatorynote_id',
                 properties=['sequence', 'text', 'source_document'],
                 rows=18, loadable=18, cypher=node_explanatorynote),
        NodeStep(label='Instrument', csv_name='nodes_Instrument.csv', id_column='instrument_id',
                 properties=['title', 'si_number', 'subject_heading', 'made_date', 'laid_before_parliament', 'coming_into_force', 'signed_by', 'treasury_consent', 'source_document'],
                 rows=1, loadable=1, cypher=node_instrument),
        NodeStep(label='Part', csv_name='nodes_Part.csv', id_column='part_id',
                 properties=['number', 'title', 'source_document'],
                 rows=6, loadable=6, cypher=node_part),
        NodeStep(label='PenaltyTier', csv_name='nodes_PenaltyTier.csv', id_column='penaltytier_id',
                 properties=['tier', 'maximum_amount', 'text', 'specified_in', 'source_document'],
                 rows=4, loadable=4, cypher=node_penaltytier),
        NodeStep(label='Preamble', csv_name='nodes_Preamble.csv', id_column='preamble_id',
                 properties=['sequence', 'text', 'source_document'],
                 rows=3, loadable=3, cypher=node_preamble),
        NodeStep(label='Provision', csv_name='nodes_Provision.csv', id_column='provision_id',
                 properties=['marker', 'level', 'clause_type', 'citation', 'parent_id', 'text', 'source_document'],
                 rows=713, loadable=713, cypher=node_provision),
        NodeStep(label='Regulation', csv_name='nodes_Regulation.csv', id_column='regulation_id',
                 properties=['number', 'heading', 'part', 'citation', 'source_document'],
                 rows=25, loadable=25, cypher=node_regulation),
        NodeStep(label='Schedule', csv_name='nodes_Schedule.csv', id_column='schedule_id',
                 properties=['number', 'title', 'referenced_by', 'source_document'],
                 rows=2, loadable=2, cypher=node_schedule),
        NodeStep(label='SchedulePara', csv_name='nodes_SchedulePara.csv', id_column='schedulepara_id',
                 properties=['schedule', 'number', 'heading', 'citation', 'source_document'],
                 rows=10, loadable=10, cypher=node_schedulepara),
        NodeStep(label='Sector', csv_name='nodes_Sector.csv', id_column='sector_id',
                 properties=['name', 'column', 'source', 'source_document'],
                 rows=5, loadable=5, cypher=node_sector),
        NodeStep(label='Subsector', csv_name='nodes_Subsector.csv', id_column='subsector_id',
                 properties=['name', 'sector', 'column', 'source', 'source_document'],
                 rows=10, loadable=10, cypher=node_subsector),
        NodeStep(label='ThresholdRequirement', csv_name='nodes_ThresholdRequirement.csv', id_column='thresholdrequirement_id',
                 properties=['essential_service', 'text', 'specified_in', 'source_document'],
                 rows=33, loadable=33, cypher=node_thresholdrequirement),
    ],
    rel_steps=[
        RelStep(rel_type='FOR_SUBSECTOR', csv_name='rels_designation_for_subsector.csv',
                properties=[],
                rows=23, loadable=23, cypher=rel_for_subsector),
        RelStep(rel_type='DESIGNATES_AUTHORITY', csv_name='rels_designation_names_authority.csv',
                properties=[],
                rows=23, loadable=23, cypher=rel_designates_authority),
        RelStep(rel_type='HAS_THRESHOLD_REQUIREMENT', csv_name='rels_essentialservice_has_threshold.csv',
                properties=[],
                rows=33, loadable=33, cypher=rel_has_threshold_requirement),
        RelStep(rel_type='IN_SUBSECTOR', csv_name='rels_essentialservice_in_subsector.csv',
                properties=[],
                rows=33, loadable=33, cypher=rel_in_subsector),
        RelStep(rel_type='HAS_PREAMBLE', csv_name='rels_has_preamble.csv',
                properties=[],
                rows=3, loadable=3, cypher=rel_has_preamble),
        RelStep(rel_type='HAS_EXPLANATORY_NOTE', csv_name='rels_instrument_has_explanatory_note.csv',
                properties=[],
                rows=18, loadable=18, cypher=rel_has_explanatory_note),
        RelStep(rel_type='HAS_PART', csv_name='rels_instrument_has_part.csv',
                properties=[],
                rows=6, loadable=6, cypher=rel_has_part),
        RelStep(rel_type='HAS_SCHEDULE', csv_name='rels_instrument_has_schedule.csv',
                properties=[],
                rows=2, loadable=2, cypher=rel_has_schedule),
        RelStep(rel_type='HAS_REGULATION', csv_name='rels_part_has_regulation.csv',
                properties=[],
                rows=25, loadable=25, cypher=rel_has_regulation),
        RelStep(rel_type='CROSS_REFERENCES', csv_name='rels_provision_cross_references.csv',
                properties=['target_kind'],
                rows=70, loadable=70, cypher=rel_cross_references),
        RelStep(rel_type='DEFINES', csv_name='rels_provision_defines_term.csv',
                properties=[],
                rows=107, loadable=107, cypher=rel_defines),
        RelStep(rel_type='DESIGNATES', csv_name='rels_provision_designates.csv',
                properties=[],
                rows=23, loadable=23, cypher=rel_designates),
        RelStep(rel_type='DESIGNATES_AUTHORITY', csv_name='rels_provision_designates_authority.csv',
                properties=['designation_text'],
                rows=3, loadable=3, cypher=rel_designates_authority_2),
        RelStep(rel_type='HAS_DEADLINE', csv_name='rels_provision_has_deadline.csv',
                properties=[],
                rows=21, loadable=21, cypher=rel_has_deadline),
        RelStep(rel_type='HAS_SUBCLAUSE', csv_name='rels_provision_has_subclause.csv',
                properties=[],
                rows=506, loadable=506, cypher=rel_has_subclause),
        RelStep(rel_type='SETS_PENALTY_TIER', csv_name='rels_provision_sets_penalty_tier.csv',
                properties=[],
                rows=4, loadable=4, cypher=rel_sets_penalty_tier),
        RelStep(rel_type='SPECIFIES_THRESHOLD', csv_name='rels_provision_specifies_threshold.csv',
                properties=[],
                rows=33, loadable=33, cypher=rel_specifies_threshold),
        RelStep(rel_type='HAS_PROVISION', csv_name='rels_regulation_has_provision.csv',
                properties=[],
                rows=150, loadable=150, cypher=rel_has_provision),
        RelStep(rel_type='HAS_DESIGNATION', csv_name='rels_schedule_has_designation.csv',
                properties=[],
                rows=23, loadable=23, cypher=rel_has_designation),
        RelStep(rel_type='HAS_PARAGRAPH', csv_name='rels_schedule_has_para.csv',
                properties=[],
                rows=10, loadable=10, cypher=rel_has_paragraph),
        RelStep(rel_type='COVERS_SUBSECTOR', csv_name='rels_schedulepara_covers_subsector.csv',
                properties=[],
                rows=10, loadable=10, cypher=rel_covers_subsector),
        RelStep(rel_type='HAS_PROVISION', csv_name='rels_schedulepara_has_provision.csv',
                properties=[],
                rows=57, loadable=57, cypher=rel_has_provision_2),
        RelStep(rel_type='SPECIFIES_ESSENTIAL_SERVICE', csv_name='rels_schedulepara_specifies_service.csv',
                properties=[],
                rows=33, loadable=33, cypher=rel_specifies_essential_service),
        RelStep(rel_type='HAS_SUBSECTOR', csv_name='rels_sector_has_subsector.csv',
                properties=[],
                rows=10, loadable=10, cypher=rel_has_subsector),
    ],
    expected_nodes_total=1030,
    expected_rels_total=1226,
)

if __name__ == "__main__":
    run(LOADER)
